### ISSUE TITLE
Cannot be pinned to Windows Taskbar

### ISSUE THREAD

**Issue by kitze** [Aluxian/Facebook-Messenger-Desktop#1]
When you pin the .exe file in the Windows taskbar when you click the taskbar icon it opens another taskbar item, and if you try to pin that one when you close it it shows a broken icon...

**Comment by Aluxian** [comment]
Thanks, I will test this and get back to you.

**Comment by Aluxian** [comment]
Since 1.2.0, the Windows app is distributed through an installer. It should fix this problem.

**Comment by kitze** [comment]
Thank you!
