### ISSUE TITLE
Would you like the app to keep state between restarts?

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#10]
I.e. when you close the app (completely) and open it again, should it be in the same position and have the same size as before?

**Comment by jkaberg** [comment]
Yeah, I think it should :)

**Comment by tomvest** [comment]
It definitely should retain the size, but position is not that important to me though.

**Comment by szhu** [comment]
Please retain both. Rationale: See Spotify, Transmission and many other single-window apps.

**Comment by Aluxian** [comment]
Okay, I will try to implement this too.

**Comment by alopix** [comment]
yeah, would be nice to retain size and position (make it an option though ;))

**Comment by jllodra** [comment]
+1

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/f98eaab34e290b4f250bf02c1c1bb276d57c372e
