### ISSUE TITLE
Windows 10 Integration

### ISSUE THREAD

**Issue by thejtshow** [Aluxian/Facebook-Messenger-Desktop#110]
Hello, awesome app that I loved using on Windows 8.1, but in the Windows 10 Pro Insider Preview (build 10074) The app displays nothing but a white screen. Taskbar menu functions fine, does not lock up with not responding messages, just does not display after logging in. Login screen works just fine.

**Comment by Aluxian** [comment]
I tested the app on build 10130 and it worked. Please try the [latest app update](https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/latest), update your Windows or maybe wait until Microsoft releases more Windows updates. I have no idea what the issue could be.

**Comment by thejtshow** [comment]
Will do. Thanks mate

There is no freedom if there is but one who does not possess it. -- Joshua Bennett

**Comment by vaclavkadera** [comment]
hello, first of all, best app which works on windows 10 like nothing else but... second - notification center is implemented perfectly, BUT taskbar implementation in last stable release of Win10 (no insider preview) has no actions, no overlay icons (badges) definitely nothing what can show me that I have unread messages. Please is it possible to fix it?  :) thanks!
