### ISSUE TITLE
URL about:blank

### ISSUE THREAD

**Issue by jsf15** [Aluxian/Facebook-Messenger-Desktop#114]
Every time that you open a conversation this box opens.
Mac OSX Yosemite - Middle 2010

![captura de ecra 2015-06-3 as 12 00 17](https://cloud.githubusercontent.com/assets/12023386/7958523/2c0c05bc-09e8-11e5-9173-30f300f2e20e.png)

**Comment by Aluxian** [comment]
Hi, have you tried quitting the app and opening it again? Or reloading?

**Comment by jsf15** [comment]
Yes I did. On launch it open 3 of these windows

**Comment by jsf15** [comment]
Console entries:

03/06/15 12:48:59,355 Messenger[775]: Sparkle: ===== Messenger =====
03/06/15 12:49:01,128 com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
03/06/15 12:49:01,559 mdworker[778]: iWork MDI raised an exception: Could not read: Is a directory
03/06/15 12:49:01,564 mdworker[778]: iWork MDI raised an exception: Could not read: Is a directory

**Comment by cgrin** [comment]
I'm seeing the same thing on OS X 10.10.3. Just started in the last few days.

**Comment by Aluxian** [comment]
@all does this still occur?

**Comment by jsf15** [comment]
I reinstalled it and the problem disappeared

**Comment by Aluxian** [comment]
@jsf15 Thanks!
