### ISSUE TITLE
[enhancement] popup notification for new messages for better visibility

### ISSUE THREAD

**Issue by naox** [Aluxian/Facebook-Messenger-Desktop#117]
Facebook-Messenger-Desktop notifies about new messages only by blinking very tiny red dot on system tray icon. Its not easy to spot this. There is a great need for another visual notification, preferably bigger popup in bottom right saying "xxxx send you a message" (and clicking on it opens this conversation).

**Comment by HRoland1** [comment]
There is notifications...

Gear icon -> Settings - > Enable desktop notifications

**Comment by HRoland1** [comment]
There are notifications.

Gear icon -> Settings -> Enable Desktop Notifications

**Comment by naox** [comment]
Oh, you are right. I don't know why I missed it. Sorry.
