### ISSUE TITLE
Startup problems when no network

### ISSUE THREAD

**Issue by naox** [Aluxian/Facebook-Messenger-Desktop#118]
Facebook-Messenger-Desktop has problems starting when there is no network connection (and then reconnect when there is). For me it happens every time I restart windows os - for few seconds I can't access network (via onboard 100mbit lan port) and since I want Facebook-Messenger-Desktop to start every time winows starts ("launch on startup" is checked) it dies with a window like this http://i.imgur.com/XT5pwJ8.png
It does not reconnect when 1-2 seconds later network works fine. I have to close Facebook-Messenger-Desktop and open it again - and then it works.

Another thing is that when starting Facebook-Messenger-Desktop with os ("launch on startup") it should be minimalized to tray and not visible - Messenger.exe sould have /tray switch or something

**Comment by HRoland1** [comment]
I would love to see the tray thing ;)

**Comment by Aluxian** [comment]
Since 1.4.0, the app keeps reloading every 15 seconds until it connects to the internet.

Start minimized on startup is tracked here: #60.

**Comment by naox** [comment]
Version 1.4.3 - problem is still present as described. Hangs with http://i.imgur.com/XT5pwJ8.png during windows startup.
