### ISSUE TITLE
The application uses a lot of battery power on OS X

### ISSUE THREAD

**Issue by MathiasOki** [Aluxian/Facebook-Messenger-Desktop#119]
Is it possible to try making it more battery friendly? 

I'm using version 1.4.0 (1.4.0)

See screenshot of activity monitor (Norwegian):
![rqmht](https://cloud.githubusercontent.com/assets/3447456/8032351/b291a51a-0dd5-11e5-8eec-5b99dfb117ec.png)

**Comment by alyh** [comment]
Same problem here! 

![screen shot 2015-06-10 at 10 12 21 am](https://cloud.githubusercontent.com/assets/1329372/8084472/38607f20-0f59-11e5-89bc-c6e25726e6cf.png)

**Comment by Aluxian** [comment]
I will see what I can do.

**Comment by psyclip-r** [comment]
It's nw.js general problem. Another nw.js apps act just the same way, often using 100% CPU

**Comment by Aluxian** [comment]
Unfortunately, as @psyclip-r said, it's a nw.js problem and I can't just fix it. However, Google is focusing right now on bringing speed and battery improvements to Chrome. These changes will, most probably, get integrated into nw.js too.

**Comment by iBobik** [comment]
http://www.goofyapp.com/ (similar to this app, but build in Cocoa) is much more efficient.

**Comment by kevinnguy** [comment]
@iBobik thanks for the suggestion! I was suffering from this too, will test out goofy
