### ISSUE TITLE
Flattr donation support

### ISSUE THREAD

**Issue by orschiro** [Aluxian/Facebook-Messenger-Desktop#120]
Hi @Aluxian,

I would like to donate to your project on a monthly, recurring basis. 

Do you support flattr?

Warmly,

Robert

**Comment by Aluxian** [comment]
Hey Robert,

I appreciate your kindness. I've just added a Flattr button on the website, check it out http://messengerfordesktop.com/.

Thank you! :)

**Comment by orschiro** [comment]
@Aluxian 

You're welcome! Facebook Messenger is a great piece of software that improves my workflow since I don't have to visit the awfully slow Facebook page.
