### ISSUE TITLE
¿How to install Ubuntu 14.04?

### ISSUE THREAD

**Issue by leninalbertolp** [Aluxian/Facebook-Messenger-Desktop#13]
I'm sorry I'm a noob at linux and do not know how to install it if someone can explain to you be grateful.

**Comment by faizaanceg** [comment]
First install ***npm*** (Node Package Manager) and ***node***. This should [help](https://ariejan.net/2011/10/24/installing-node-js-and-npm-on-ubuntu-debian).

Then
* `git clone` this repo to your workarea
* `cd` to the new directory
* `sudo npm install` to install  the dependencies
* `node build.js` to build the app
* The newly built app will reside in build/Messenger/linux{32|64} 
* You can run it directly with `./build/Messenger/linux32/Messenger`

**Comment by Aluxian** [comment]
Probably he was only interested in running, not building.

@leninalbertolp Download the latest release for your OS from [here](https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/latest). 

Then you have to extract it and open Messenger. I'm working on an easier install procedure.

**Comment by leninalbertolp** [comment]
Okay, thank you very much

**Comment by Aluxian** [comment]
@leninalbertolp The latest release is just an installer now, instead of an archive. You have to run it and it will install by itself, that's it. I hope this is easier for you.

**Comment by orschiro** [comment]
Has anyone already packaged this great app as a `.deb.` or provides a `ppa` for it?

**Comment by faizaanceg** [comment]
@orschiro Not yet. @Aluxian has used `makeself` to create an installer for Linux.

**Comment by Aluxian** [comment]
@orschiro @faizaanceg Now I'm packaging .deb directly. It will be released soon.

**Comment by faizaanceg** [comment]
@Aluxian :+1:  That's good news :) !

**Comment by orschiro** [comment]
@Aluxian 

Great news! Let me know if you can provide a ppa for it. I am happy to add it to [ppa.orzanna.de](http://ppa.orzanna.de/)!

**Comment by Aluxian** [comment]
@orschiro The .deb is up at https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/latest. If you add it to your ppa I'll add it on the website.

**Comment by orschiro** [comment]
@Aluxian 

What a great release! Integrates perfectly into the elementary OS desktop. One minor thing. Can we get rid of the menubar containing the `File` entry which only has one entry `Quit`? I would save we can save this space. :)

![image](https://cloud.githubusercontent.com/assets/170947/7176915/037c4746-e423-11e4-866e-04013dd231dc.png)

Regarding the PPA. I don't have any experience in packaging a package for a PPA myself but I will ask [@quassy](http://quassy.github.io/elementary-apps/) if he wants to package it in his PPA. Will let you know!

**Comment by Aluxian** [comment]
@orschiro I'm still experimenting with how the app should work on each platform. I agree that's a waste of space and could be integrated better.

Thanks for the submission!

**Comment by JustSomeDood** [comment]
If the application is packaged in a deb already, honestly most of the work is already done,  I'm downloading the apps now (32 and 64 bit) and it should be up in my ppa shortly.

As soon as it is i'll report back with the link, once I confirm it's working.

**Comment by orschiro** [comment]
Thanks a lot @JustSomeDood! Did it work out?
