### ISSUE TITLE
Lag on Ubuntu after last update (1.4.2)

### ISSUE THREAD

**Issue by tudor07** [Aluxian/Facebook-Messenger-Desktop#131]
It was working perfect until I updated to version 1.4.2
Now if I run Messenger I have a lot of lag and all computer runs slowly.
Also the new icon (the one near wi-fi, clock etc) is flashing continuously.

I am running Linux Ubuntu 14.04 LTS.

P.S.: Foarte utila aplicatia, o folosesc zilnic :D

**Comment by Aluxian** [comment]
Salut! :D

Îmi reinstalez acum Ubuntu 14.04 să văd ce are.


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Sat, Jun 13, 2015 at 6:50 pm, Prodan Tudor < notifications@github.com [notifications@github.com] > wrote:
It was working perfect until I updated to version 1.4.2
Now if I run Messenger I have a lot of lag and all computer runs slowly.
Also the new icon (the one near wi-fi, clock etc) is flashing continuously.

I am running Linux Ubuntu 14.04 LTS.

P.S.: Foarte utila aplicatia, o folosesc zilnic :D

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/131] .[https://github.com/notifications/beacon/ABWmdhF890AF2iqF0pinxDkptQuRqBX5ks5oTEi0gaJpZM4FCCQI.gif]

**Comment by e7aso** [comment]
I have the same issue. After launching new version of messanger compiz process suddenly occupies above 20% of CPU. I refer to Ubuntu 14.04.

**Comment by pandaconqueso** [comment]
it's happening to me too (ubuntu 15.04)

**Comment by Aluxian** [comment]
@all Please check the latest release: https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/latest

Let me know if the issue is gone. I removed the tray icon, but I'm not sure whether this was the problem. I suspect another change might cause this too, I'll undo it if you still have problems.

**Comment by tudor07** [comment]
It works now. No more lag :)

**Comment by Aluxian** [comment]
Nice! Can anyone else confirm?

**Comment by e7aso** [comment]
Yeah, no more lags. Thanks for quick fix.

**Comment by xfoxawy** [comment]
ubuntu 12.04 .. no lag confirmed .. thnx
