### ISSUE TITLE
Space disappear

### ISSUE THREAD

**Issue by NitsuSaiNeko** [Aluxian/Facebook-Messenger-Desktop#134]
When I chat using this application, sometimes the space between each words will disappear completely making text difficult to read. It can only be fixed by restarting the application.

![ss 2015-06-14 at 02 08 29](https://cloud.githubusercontent.com/assets/12886318/8150440/261c2852-129f-11e5-8279-4cce85bdf937.png)

This don't happen that often but it happens about once a week. I do not know what caused the issue and it never happens when I tries to make it happen. I can type normally in the text box but when I hit backspace, all the spaces disappear. If I don't hit backspace, the text will look normal until I send it out just like my space bar never exist. This happens in every previous versions I had and I just updated to 1.4.3, not sure if this latest version fixed the issue but I'm assuming not.

For extra information, I'm using Win7 Ultimate 64bit and I type in Chinese too, but I only notice the issue in English since Chinese don't require space between words.

**Comment by Aluxian** [comment]
I'm clueless... I would ask you to check if it happens on messenger.com too (if it did, I'd tell you to report the bug to Facebook), but since It happens so rarely and you can't reproduce it...

**Comment by NitsuSaiNeko** [comment]
Just confirmed, this happens in messenger.com too. It happened twice. I created an application shortcut for it with chrome so it looks just like the Messenger for Desktop and use just like how I use it before (keep it open without quitting, computer always sleep not shut off.. etc.). Though the bug disappears when I change chat room. Spaces disappear when I hit backspace but I don't want to test sending it out when I'm in the middle of the chat with my friends.
I assume this bug report post can now be closed since it's not the application issue? I hope it's not my keyboard software (Corsair Utiliity Engine) issue..

**Comment by Aluxian** [comment]
Thanks for testing it. And yes, it should be sent to Facebook.
