### ISSUE TITLE
copy/paste don't appear in the message field's context menu

### ISSUE THREAD

**Issue by hangyas** [Aluxian/Facebook-Messenger-Desktop#138]
It would happen on &lt;input>-s, but the html looks like this: ![http://i.imgur.com/9ZP9KtA.png](http://i.imgur.com/9ZP9KtA.png)

btw the 'search for people' is &lt;input>

**Comment by Sytten** [comment]
Doesnt seem to be a problem anymore.
Please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you still have the problem, please open a new issue
