### ISSUE TITLE
license

### ISSUE THREAD

**Issue by karan** [Aluxian/Facebook-Messenger-Desktop#14]
i want to fork this repo and maybe work on it but I'm not sure if I can because there is no OSS license.

I recommend MIT

**Comment by DomT4** [comment]
Oh yeah. Technically it's not open-source without a LICENSE saying so; Copyright law presumes without a license you intend copyright to apply to your work. Per Github's T&Cs though, people can view and fork the code... They just can't play with it.

MIT, BSD Simplified or Mozilla are solid licenses.

**Comment by MatthD** [comment]
Yeah author , can you describe the way to contribute ?

I supose clone , then install & build but When I start the builded app for my system It only show a window with "NW.JS" wrotte in ..

**Comment by Aluxian** [comment]
I've jut added the MIT license, I'll push today some commits. @MatthD I'll get back to you.

**Comment by karan** [comment]
Thanks!
