### ISSUE TITLE
Really slow

### ISSUE THREAD

**Issue by JPedroBorges** [Aluxian/Facebook-Messenger-Desktop#144]
Hello,

I'm using version 1.4.3

And since last versions the app is getting slower.

1. When I type on keyboard the letters take some time to appear on the screen.
2. the "Auto-Hide Sidebar" is on, and when I put my mouse over to expand it take some time expand. Even get stuck before gets full expanded. 
3. After some time with it open notification have a big delay to appear. I heard the sounds from facebook.com and in some cases takes some minutes to show up on the app. Even if I press reload.
4. At the same time of point 3, when I click on the try icon, nothing shows up. (screenshot_1)

![screenshot_1](https://cloud.githubusercontent.com/assets/12955328/8236997/8867e78a-15ec-11e5-8eec-e285d1a0accc.png)

Thanks

**Comment by Sytten** [comment]
I have not notice this performances issue.
Pleas try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you still have problems, please open a new issue.
