### ISSUE TITLE
Click outside window to close.

### ISSUE THREAD

**Issue by Excitor** [Aluxian/Facebook-Messenger-Desktop#146]
Once you've replied to a message the ability to click outside the main windows (like clicking on the desktop or Firefox for example) will close the messenger window. This is a great feature for messenger style programs where you need to jump in and out quikcly (reading/replying to messages). Removed the need for clicking that extra button "x" in the corner or reaching for esc.

**Comment by Aluxian** [comment]
I haven't seen this behaviour before. I will let the OS handle this kind of window management. When you click another window, that window is focused. The Messenger window shouldn't have to close it, it will just remain unfocused.

**Comment by Excitor** [comment]
Thanks you for the reply let me me show you a video from a browser extension that does the same thing. (sorry for the bad quality/weird angle did it that way to make it quick/not reveal too much personal information)
https://drive.google.com/file/d/0B8a1ZTJDlaVIRER0VVZmUzlCN1E/view?usp=sharing

I appreaciate that you don't think this is something the application needs, thought I'd make a suggestion anyway. Keep up the good work.

**Comment by Aluxian** [comment]
I see. Well, that’s a browser extension. It makes sense on a webpage, but not so much on the OS.

Good work means saying “no” sometimes, too. Enjoy the app :)

	Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On 19 Jun 2015 at 14:00:25, Robin Backman (notifications@github.com) wrote:

Thanks you for the reply let me me show you a video from a browser extension that does the same thing. (sorry for the bad quality/weird angle did it that way to make it quick/not reveal too much personal information)
https://drive.google.com/file/d/0B8a1ZTJDlaVIRER0VVZmUzlCN1E/view?usp=sharing

I appreaciate that you don't think this is something the application needs, thought I'd make a suggestion anyway. Keep up the good work.
