### ISSUE TITLE
High CPU usage while idle.

### ISSUE THREAD

**Issue by Excitor** [Aluxian/Facebook-Messenger-Desktop#147]
There seems ti be quite a high CPU usage while the applicaiton just sits idle minimised to taskbar.
Windows 8.1 x64. 0.30 average cpu usage from the recourse monitor jumping up to 0.5-1.5 percent in every few seconds in taskmanager. 
Compared to other larger applications firefox with facebook tab, email, youtube open minimised takes less CPU while idle.

**Comment by mrjefftang** [comment]
The same on OS X.  On idle, there are 2 nwjs Helpers that consume 10% CPU.

**Comment by Aluxian** [comment]
This is because, basically, the app runs on top of a browser (a custom Chromium build). It's an issue with NW.js which is used to run my app and I can't fix it. I'm sorry, everyone.

**Comment by lazywei** [comment]
Maybe using electron? Maybe it would be more efficient in terms of CPU / memeory.

**Comment by Aluxian** [comment]
Yes, that's what I plan to do. https://github.com/Aluxian/electron-superkit is
almost finished.

--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Tue, Jul 07, 2015 at 8:16 am, Chih-Wei (Bert) Chang < notifications@github.com [notifications@github.com] > wrote:
Maybe using electron? Maybe it would be more efficient in terms of CPU /
memeory.

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/147#issuecomment-119075264] .[https://github.com/notifications/beacon/ABWmdtY2osc9Rxqd3t0DwJQKtOY_YG1Dks5oa1hCgaJpZM4FHC8M.gif]
