### ISSUE TITLE
WINDOWS

### ISSUE THREAD

**Issue by stoklasa** [Aluxian/Facebook-Messenger-Desktop#149]
Hey man, i have suggestion, put this app to Windows Store, it would be amazing!

thanks for the app :-)

**Comment by Aluxian** [comment]
There's already a Messenger app in the store, but not made by me. Have you searched? :)

**Comment by stoklasa** [comment]
Yes, but its the metro app, and i dont want metro. Desktop messenger is what i want. Btw: in first launch the app title on taskbar was changing "facebook" and "messenger" in really short intervals, so i seen just blinking. After restart no issue, just so you know possible bugs :-)

**Comment by stoklasa** [comment]
Are you planning on to write universal app? I don't know facebook's plans on messenger on windows desktop, it would be totally sweet if there were notifications in windows 10, which would be possible to respond instantly (app running in the background)

**Comment by Aluxian** [comment]
I've noticed that bug too, new issue: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/150

Even if I published it to the store, it wouldn't be a .NET app thus not an universal app. I hope I'm not making any confusions here.

I've found some links, I think I can publish it. Will look into it later. Thanks for the suggestion.

https://msdn.microsoft.com/en-us/library/windows/desktop/dn374786(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/dn322034(v=vs.85).aspx

**Comment by stoklasa** [comment]
No you are not :-) i clearly understand.But for future, it would be amazing, I don't know how much you are into windows 10 beta testing and and so. Im quite interested in future of windows.

**Comment by stoklasa** [comment]
1 more issue: resizing. It would be awesome if you could get here just active conversation instead of menu. App could act like on phone. I hope im not annoying, i just want to make app better :) +1
![wp_2015032fdsyfsd](https://cloud.githubusercontent.com/assets/12977596/8267108/27629782-1754-11e5-9095-2bb58f2006c9.png)

**Comment by Aluxian** [comment]
You're not annoying, I'm open to suggestions. I don't think this UI would work for desktops, and to be honest I don't really like it.

**Comment by stoklasa** [comment]
Okay, its matter of opinion, i do all my projects responsive to be maximally usefull in these small modes. But well, not that big like messenger

**Comment by Sytten** [comment]
All issues listed above are resolved in the latest beta,
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
As for the windows store, we don't plan to upload our software there...
