### ISSUE TITLE
Lo siento, no se instalar el programa en UBUNTU 15.04 alguien me puede ayudar.

### ISSUE THREAD

**Issue by juanmiravete** [Aluxian/Facebook-Messenger-Desktop#15]

**Comment by Aluxian** [comment]
Hey @juanmiravete! Please try to download an installer for your OS from here:

http://messengerfordesktop.com/#download

I've updated the app and now it's easier to install. Let me know if you're still having trouble.

**Comment by juanmiravete** [comment]
Lo siento sigue dando error
![captura de pantalla de 2015-04-15 02 21 31](https://cloud.githubusercontent.com/assets/11907350/7150087/5b86f7c8-e316-11e4-9e5a-114dafa1d55e.png)

**Comment by Aluxian** [comment]
Ah, I see. Let's try something else.

1. Launch the application called Terminal 
2. Write `cd Descargar` (move `Messenger_linux64.run` in ~/Descargar if it's not there) then press enter
3. Write `chmod +x Messenger_linux64.run` then enter
4. Write `sudo ./Messenger_linux64.run` then enter

This will install the app and you'll be able to find it in the launcher.
