### ISSUE TITLE
Screen transition problem

### ISSUE THREAD

**Issue by oPhuongXuongQuang** [Aluxian/Facebook-Messenger-Desktop#151]
On Mac OS, when you switch to Mosaic theme on right-click action and click on Info icon on the right top Navigation bar, the screen of 2 section is not cleared and overlapped.

**Comment by Aluxian** [comment]
Thanks, I will fix it.

**Comment by Sytten** [comment]
Since we removed the settings from the context menu this should not be an issue anymore.
Please try our new beta.
More Information here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you still have problems, please open a new issue
