### ISSUE TITLE
Dark theme issue

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#152]
![11046544_783527321767814_1391402360223661592_n](https://cloud.githubusercontent.com/assets/1418870/8280749/0833d132-18e9-11e5-8762-733b5be6fa89.jpg)

**Comment by auscompgeek** [comment]
This specific issue was fixed in auscompgeek/fb-messenger-dark@0055901792d7669ce54408c2064e0a9e3d44d278.

**Comment by Sytten** [comment]
This issue is fixed in the latest beta.
Please see #458
