### ISSUE TITLE
Add RPMs for Fedora  openSUSE Mandriva and derivates

### ISSUE THREAD

**Issue by sergioad** [Aluxian/Facebook-Messenger-Desktop#155]
Hello, could you add Messenger for desktop RPMs for Fedora  openSUSE Mandriva and their derivates?

**Comment by Aluxian** [comment]
I've tried it before, but they didn't work. Probably because I packaged them on my Mac. I'll try again.

**Comment by sergioad** [comment]
thank you very  much, if you get them please advice me :smile:

**Comment by Markieta** [comment]
+1
For now I use Pidgin/Finch with the [Purple Facebook](https://github.com/jgeboski/purple-facebook) plugin.

**Comment by nelson6e65** [comment]
:+1:

**Comment by bodywithoutorgans** [comment]
+1

**Comment by AlexCzar** [comment]
@Aluxian there is no need to package locally on your Mac when there's OpenSUSE Build Service ;)

I'm willing to try to package for OpenSUSE if you point me in the direction of your previous try - I'm not very good in writing specs but I could fix one that fails :)

**Comment by Aluxian** [comment]
I'll see how that service works. I wasn't aware of it, thanks for letting me
know.

On Thu, Oct 08, 2015 at 10:55 am, Alex Czar < notifications@github.com [notifications@github.com] > wrote:
@Aluxian [https://github.com/Aluxian] there is no need to package locally on your Mac when there's OpenSUSE Build
Service ;)

I'm willing to try to package for OpenSUSE if you point me in the direction of
your previous try - I'm not very good in writing specs but I could fix one that
fails :)

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/155#issuecomment-146448738] .[https://github.com/notifications/beacon/ABWmdp1m_M_kd-A0zAudzEyo1JXdd0Znks5o5hjzgaJpZM4FKSzK.gif]

**Comment by cydrobolt** [comment]
+1 on an RPM build
I can help with a potential Fedora RPM build, but if you've already started, I would be interested

**Comment by aia832003** [comment]
I'd also like to see this in RPM form. Any development on this front?

**Comment by Aluxian** [comment]
Yep, I'm working on Messenger for Desktop 2. Yesterday I tested the rpm and it
worked. I can't wait to release it :)

On Mon, Dec 21, 2015 at 1:53 am, aia832003 < notifications@github.com [notifications@github.com] > wrote:
I'd also like to see this in RPM form. Any development on this front?

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/155#issuecomment-166165954] .[https://github.com/notifications/beacon/ABWmdg80bUJxeDzeH92ZblGjp7_J1meLks5pRzb2gaJpZM4FKSzK.gif]

**Comment by aia832003** [comment]
Aluxian, that sounds great! I look forward to it in the New Year!

**Comment by aia832003** [comment]
Also, I would be more than willing to beta test the RPM if need be.

**Comment by Aluxian** [comment]
Join https://gitter.im/Aluxian/Facebook-Messenger-Desktop, I'll upload the beta release there.

**Comment by aia832003** [comment]
Sweet! Chat room joined!

**Comment by Sytten** [comment]
The RPM are available in the current beta release.
Please see #458 for more information about it
