### ISSUE TITLE
Merge Messenger, WhatsApp and Skype in one app

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#158]
Suggested by 2 persons

**Comment by Sjano** [comment]
The only way to do that, would be to make an addon to skype, or else skype would need to be installed and run seperatly anyways,

**Comment by sethk** [comment]
@Sjano Skype has a web client now: https://web.skype.com/en/

**Comment by marcoas** [comment]
Please merge only Facebook and WhatsApp

**Comment by Sytten** [comment]
I also support that suggestion

**Comment by cassiodoroVicinetti** [comment]
Support **provided that** multiple tray icons are created, one for each service.

**Comment by Sytten** [comment]
Don't you prefer, one tab for each service?

**Comment by Aluxian** [comment]
Messenger for Desktop and my other apps won't be merged with other services. There's Franz for that.

**Comment by cassiodoroVicinetti** [comment]
@Sytten Not at all! Tray icons are also useful to see whether you received a message.

**Comment by Sytten** [comment]
@cassiodoroVicinetti ok ok :)
