### ISSUE TITLE
[REQ] Chat Privacy / Unseen

### ISSUE THREAD

**Issue by qKa** [Aluxian/Facebook-Messenger-Desktop#159]
Can you implement "unseen feature" ? (Block any "seen" and "is typing" footprint)
It would be great, thanks :)
Like these extensions for Chrome:
Chat Privacy - https://chrome.google.com/webstore/detail/facebook-chat-privacy/gfpgaanechfneiboempkfjghninbibjn

Facebook Unseen - https://chrome.google.com/webstore/detail/facebook-unseen/iicapmagmhahddefgokbabbgieiogjop

**Comment by Sytten** [comment]
We will continue the discussion here https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/359
