### ISSUE TITLE
Battery/Power Performance

### ISSUE THREAD

**Issue by ghost** [Aluxian/Facebook-Messenger-Desktop#162]
I have been using both messenger and whatsapp for desktop on my macbook air and have seen significantly decreased battery performance.

The reported 'average energy impact' is ~20 - whatever that means - (19.55 & 18.51 respectively) for each application. I had been running as menu bar apps but I have reverted back to running them as usual just in case that had any impact. I haven't noticed any yet.

For comparison dropbox (which is always running in the background) reports 0.42 and airmail (which i also run in the menu bar) uses around 2.12.

Chrome also reports ~20 (21.39) but this a a known memory/energy hog.

The messenger and whatsapp programmes work well for me but I would suggest there are perhaps inefficiencies in the code that result in such poor battery performance. I'm no coder though so it's probably not as simple as that.

Anyway, any improvements in battery performance would be greatly appreciated as I'd like to have these running constantly in the background.

Thanks

**Comment by Aluxian** [comment]
I’m working on porting the apps to Electron, which should be more battery efficient.

	Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On 27 Jun 2015 at 12:40:48, murraysroystonward (notifications@github.com) wrote:

I have been using both messenger and whatsapp for desktop on my macbook air and have seen significantly decreased battery performance.

The reported 'average energy impact' is ~20 - whatever that means - (19.55 & 18.51 respectively) for each application. I had been running as menu bar apps but I have reverted back to running them as usual just in case that had any impact. I haven't noticed any yet.

For comparison dropbox (which is always running in the background) reports 0.42 and airmail (which i also run in the menu bar) uses around 2.12.

Chrome also reports ~20 (21.39) but this a a known memory/energy hog.

The messenger and whatsapp programmes work well for me but I would suggest there are perhaps inefficiencies in the code that result in such poor battery performance. I'm no coder though so it's probably not as simple as that.

Anyway, any improvements in battery performance would be greatly appreciated as I'd like to have these running constantly in the background.

Thanks

**Comment by murraysroystonward** [comment]
great, many thanks.

**Comment by ivancuric** [comment]
Awesome! Any ETA on it?

**Comment by Aluxian** [comment]
I can't provide an ETA, sorry.

**Comment by aarodynamics** [comment]
This is also an issue on **Windows**. 

Any chance of making this a Modern App for Windows 10 while porting?

Great work so far. Extremely useful and good looking app!

**Comment by imsys** [comment]
I noticed that there is also this `/proc/self/exe` that runs together.

probably porting to Electron would fix that too.

```
top -c

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND 
 1512 arthur    20   0  404564 104136  67372 S  11.9  1.3   0:04.64 /proc/self/exe --type=gpu-process --channel=1487.0.1585591208 --no-sandbox --enable-crash-reporter --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,24,27,40,48 --disable-accelerated-video-decode --gpu-vendor-id=0x10de --gpu-device-id=0x0df2 --gpu-driver-vendor=NVIDIA --gpu-driver-version=346.72 --enable-crash-reporter
 1522 arthur    20   0 1021832 155644  49404 S   6.9  1.9   0:05.64 /opt/MessengerForDesktop/Messenger --type=zygote --no-sandbox --enable-crash-reporter 
```

**Comment by HRoland1** [comment]
Look what Google did with the memory
https://www.youtube.com/watch?v=jnCxYypAFbk

**Comment by Sytten** [comment]
We still have this issue, it is well known. 
I'm working closely with the developer of NWJS to find the issue.
Still we made some improvements since and I encourage you to test the beta release.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information. Since there is a lot of issue already opened for this bug I will close it.
