### ISSUE TITLE
Escape Button Bug

### ISSUE THREAD

**Issue by chedster** [Aluxian/Facebook-Messenger-Desktop#163]
Pressing the Escape Button on Windows closes Messenger even when it is not the app in focus. For example, if messenger is open and I open Google Hangouts Chrome Extension, pressing escape to close Hangouts also closes Messenger. For clarity, I am only pressing the escape button once.

**Comment by jkugler** [comment]
Could not replicate the above, but did find this: when a picture is showing, hovering over the X says "Press Esc to close." Pressing escape closes the picture, and then immediately closes Messenger.

**Comment by Sytten** [comment]
This issue is resolved in the new beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it
