### ISSUE TITLE
No Indicator Icon on Linux

### ISSUE THREAD

**Issue by cdelahousse** [Aluxian/Facebook-Messenger-Desktop#165]
I've just installed version 1.4.3 on Ubuntu running XFCE.

I have the indicator plugin (ie. the Desktop.org version of the Windows system tray) on my panel and it works with all my other applications. Unfortunately, the indicator icon for Messenger is nowhere to be seen. When clicking the [x] close button on the app, it exits completely.

This very well may be a NW.js problem, but I thought you should know.

**Comment by cdelahousse** [comment]
I see #131 and cdbf434e023ab877c6a2e6856eddd0b7853de3a2 removed the indicator icon on Linux.

**Comment by Aluxian** [comment]
I removed the tray icon on Linux because of inconsistent behaviour. Right now I'm porting the app to Electron, then I'll bring the tray icon back.

**Comment by Majki** [comment]
Cool - when we will get icon working? :)

**Comment by Aluxian** [comment]
I'm building the new release right now.


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Mon, Jul 06, 2015 at 11:02 pm, Majki < notifications@github.com [notifications@github.com] > wrote:
Cool - when we will get icon working? :)

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/165#issuecomment-118979569] .[https://github.com/notifications/beacon/ABWmdoex_pCGpQPYm9sXQEdS7D_nMXYvks5oatZHgaJpZM4FOPB7.gif]

**Comment by Majki** [comment]
This is wonderful! :) Can't wait!

**Comment by Aluxian** [comment]
Oh, wait. I replied to this without reading what it's about. I thought this was about my WhatsApp app. Sorry to disappoint :(

**Comment by Aluxian** [comment]
For the past weeks, I've been working on https://github.com/Aluxian/electron-superkit. After I finish it I'll port both apps to it and you'll get the tray icon :)

**Comment by Majki** [comment]
Tray icon is what stops me from using your app. And maybe themes, at least colors customization.

**Comment by Aluxian** [comment]
There are 2 available themes, besides the default white one. Perhaps you'll use it when I release the new update, stay around :)

**Comment by Sytten** [comment]
This is fixed in the new beta,
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
