### ISSUE TITLE
https://messengerfordesktop.com/ times out

### ISSUE THREAD

**Issue by jkugler** [Aluxian/Facebook-Messenger-Desktop#167]
When doing an apt-cache show for this package, it links to https://messengerfordesktop.com/ but that site times out, while http://messengerfordesktop.com/ works.

**Comment by Sytten** [comment]
Ho, thank you I will update the link.

**Comment by Aluxian** [comment]
I don't think this is a problem anymore, we have https now.

**Comment by Sytten** [comment]
I checked and the link is correct with the command apt-cache show.
Issue resolved
