### ISSUE TITLE
Please add the version to the package name.

### ISSUE THREAD

**Issue by jkugler** [Aluxian/Facebook-Messenger-Desktop#168]
When I download a new version, the package name stays the same. The version should be part of the package name.

I also echo the request for an official repo. That would enable signed packages and the like.

**Comment by Sytten** [comment]
That should be easy to do. I agree it is important (version in the name).
As for an official repo, its not in my early plans. I would much rather update our update system so it works on all OS.
Meanwhile please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by Sytten** [comment]
Will be added in the next beta
