### ISSUE TITLE
Adobe Flash Player issue

### ISSUE THREAD

**Issue by johnmac92** [Aluxian/Facebook-Messenger-Desktop#169]
i cant play videos within the messenger because it asks for adobe flash player and its already installed on my desktop. please fix this

**Comment by liang6141** [comment]
Download ffmpegsumo file (win32/64) latest version add to Messenger folder

**Comment by johnmac92** [comment]
can you send me a download link?

**Comment by Sytten** [comment]
We will be able to play video in the next beta release.
I will mark this issue as duplicated since we are already aware of the problem and many reported it.
Meanwhile please try our new beta release. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
