### ISSUE TITLE
Support for dragging and dropping files

### ISSUE THREAD

**Issue by stefannitsche** [Aluxian/Facebook-Messenger-Desktop#171]
It would be nice if it was possible to send files by dragging them to the chat. Right now it just seems to download a copy of the file.

**Comment by Aluxian** [comment]
I will fix this, I've got an idea and I think it will work.

**Comment by Sytten** [comment]
This feature is already working right now.
Please see our new beta: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If still can't do it, please open a new issue
