### ISSUE TITLE
BUG- Pressing ESC to Close Picture/Video View, Closes Entire Application Window Too

### ISSUE THREAD

**Issue by thekevlau** [Aluxian/Facebook-Messenger-Desktop#174]
This is on OS X:
Normally when viewing messages in facebook.com/messages, if I click on an image or a video, the picture or video comes up in a separate "mini window" and the rest of the webpage, now in the background, enters "theatre mode" and darkens.

I can press ESC to close said mini-window after I am done looking at the picture/video (which closes the mini-window, and reverts "theatre mode").

Pressing ESC in the app currently will do all of the above, however it will also close the main messenger window.

This may or may not be related to #46?

**Comment by Sytten** [comment]
This is fixed in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
