### ISSUE TITLE
Tray icon not flashing, changing color when i got a messege

### ISSUE THREAD

**Issue by mqmq0** [Aluxian/Facebook-Messenger-Desktop#175]
Most of the (all of the?) messenging apps  on the tray turn to orange and even flash, when I have a non read messege, its not, which is disturbing, if I dont catch the pop-up notification, I miss messeges for hours.

Windows 8.1, latest version of the app.
I'm missing some setup to enable it?

**Comment by Ravasco** [comment]
Same happening to me... Win 8.1
No notifications at all :/

**Comment by bl4ckd0g** [comment]
I haven't gotten any pop-up notification (not a problem) but yes the absence of a color indication is noticeable.

**Comment by laci009** [comment]
It would be a good feature because when you use messenger at work, you dont want to popup the entire message, you just want a notification in case somebody sit next to you. And of course you can miss the pop-up like mqmq0 said.

**Comment by mizipzor** [comment]
I would really like to see this added, not having to constantly bring up the window to see if there are any new messages would be super useful.

**Comment by Sytten** [comment]
The icon gets a reb blob when receiving a new message.
It also shows a notification if enabled in the facebook settings.
Please try our new beta too! See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
