### ISSUE TITLE
Minimal Window Option

### ISSUE THREAD

**Issue by samuelcouch** [Aluxian/Facebook-Messenger-Desktop#176]
Would love an option for a more minimal display (just avatar cirlcles on the left side pane) so that I can make the window smaller. Currently, if you scale the window down the name section on the left takes up a lot of screen real estate.

Side-by-side of FB messenger vs. OSX Messages at the same window size:
![](http://i.imgur.com/pKBYSwm.png)

Primarily putting this here as a feature request and to gauge interest of others; may be able to tackle this at some point in the future though.

**Comment by Sytten** [comment]
This seems to be resolved now.
We can mess up the css to change the responsive settings if needed.
Please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
I will close the issue, but please comment here if you still have the problem with the beta so we can reopen it.
