### ISSUE TITLE
Escape key exits application entirely

### ISSUE THREAD

**Issue by chrylis** [Aluxian/Facebook-Messenger-Desktop#178]
On Linux, pressing Esc closes the window and the entire application, as opposed to minimizing it to the taskbar or (as I understand is coming back soon) the tray.

**Comment by Majki** [comment]
Confirming, Linux Mint 17 x64 here.

**Comment by bl4ckd0g** [comment]
I can confirm this happens on Windows 8.1 as well.

**Comment by danwatco** [comment]
Same issue here, Windows 8.1. 
ESC on a picture an application is closed.

**Comment by kevinwlau** [comment]
In Windows 8.1, I noticed that pressing (and holding ESC) on a picture would close the picture. On release, the application window would close as well, but Messenger remained hidden in the system tray.

**Comment by devilirium** [comment]
Aluxian is busy with porting to _Electron_. Once it's stable we'll fix these issues.

**Comment by mindworker** [comment]
Any updates?

**Comment by jackwilsdon** [comment]
I opened the pull request #209 a while ago, but nothing has happened since (not merged :disappointed:).

**Comment by Majki** [comment]
Ping :)

**Comment by eallik** [comment]
Also on Mac OS X — doesn't quit the app but hides the window; Cmd-Tab won't bring it back either; need to click on the Dock icon.

**Comment by Sytten** [comment]
This is fixed in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
