### ISSUE TITLE
video chat

### ISSUE THREAD

**Issue by toonamo** [Aluxian/Facebook-Messenger-Desktop#180]
windows 7 and using version 1.4.3 i am not able to video chat. my screen says they don't support video chat and their device says my connection doesn't support voice chat. Other users using iOS

**Comment by artemrizhov** [comment]
Same problem when trying to call from Ubuntu to Android and vice versa. Both sides report that the opposite side does not support video chat.

**Comment by Sytten** [comment]
Can you confirm that it is still a problem?
Also please try the new beta version (more info here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458).
That won't help your problem right now though, I have an idea why it might do that (will investigate).

**Comment by Sytten** [comment]
Tested and not a problem anymore
