### ISSUE TITLE
[BUG] [Edited] Multiple instances of Messenger running at once

### ISSUE THREAD

**Issue by bl4ckd0g** [Aluxian/Facebook-Messenger-Desktop#181]
I have installed Messenger for Desktop yesterday and enjoyed it. Closed it by mistake using the ESC key, but wasn't a problem as I was going to bed.

This morning when I woke the computer, I could hear all the pinging from the messages coming in, although the application was closed!

I can assure you that I didn't have Facebook (sound is different anyway) or the web Messenger opened.

**Comment by HRoland1** [comment]
If you are using Windows, then I think you just minimized it to the tray on the taskbar :)

**Comment by bl4ckd0g** [comment]
You are right Roland... am I wrong or all the other applications when closed, they are closed, whether if they are active in the clock tray they are highlighted on the taskbar?

Anyway, then the application is bugged as it seems to be running several instances at once:

![messenger_bug](https://cloud.githubusercontent.com/assets/81601/8680767/5fb368d6-2a5b-11e5-9af2-aa4b70b553b9.png)

clicking on the several icons i opened windows with chat running or trying to log in.

**Comment by scottrussy** [comment]
An ideal solution would be that closing the window via Esc or the upper right X just minimizes it to the taskbar, with a taskbar jump list item to fully close the program, much like how other IM apps work (i.e. Trillian). Tray icons seem a bit archaic and remind me of the days of AIM.

**Comment by HRoland1** [comment]
Personally I really like the traybar solution, I'm not a big fan of a bunch of icons on my taskbar, I prefer hiding applications running in the background on the tray :) 
Please @Aluxian don't remove the tray icon feature completely ;)

**Comment by bl4ckd0g** [comment]
There's nothing wrong with applications going to tray, it's an established staple in Windows. The problem here is (was? it's not happening at the moment) that multiple instances were running at the same time.

Also to consider though, that another UX staple in Windows is that X kills the application, so keeping it running (without displaying a notification like other apps do when you do it first time) in background is wrong in this status.

If Windows adopts more and more the OSX model of keeping apps running, then there should be a more clear differentiation and notification of what's running.

**Comment by Sytten** [comment]
This issue is resolved in the new beta, please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it.
