### ISSUE TITLE
Auto-Hide Sidebar Bugs

### ISSUE THREAD

**Issue by x0xcdrx0x** [Aluxian/Facebook-Messenger-Desktop#182]
Sidebar is not fully hidden when auto-hide is enabled + again transparency issue with auto-hide but this time with the dark theme.

Windows 7 x64 / Ubuntu 15.04 x64 (AMD64)

**Comment by Sytten** [comment]
The sidebar still have some issues with the new beta (see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it), but since this issue is very old I will close it.
If you still have problems, please open a new issue with clear screenshots
