### ISSUE TITLE
Energy consumption is huge

### ISSUE THREAD

**Issue by k-bx** [Aluxian/Facebook-Messenger-Desktop#185]
Here's an energy tab while Messenger is running:

https://i.imgur.com/taohgrN.png

This looks VERY bad. Do you have any ideas how to fix this?

**Comment by k-bx** [comment]
I just leave it open, it just stands still and continues having energy-load at ~80 mark.

**Comment by HRoland1** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/162
