### ISSUE TITLE
Open conversation doesn't get marked as read

### ISSUE THREAD

**Issue by dasavi** [Aluxian/Facebook-Messenger-Desktop#186]
When a message arrives in a conversation that's already open, it won't get marked as read unless you click a different chat and then click back to the current chat. I suggest marking the conversation as read when the reply box comes into focus.

**Comment by Sytten** [comment]
Well fro my own experience it does mark it as read as soon as you open the window.
Please try the beta to see if you still have that problem.
More information here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
