### ISSUE TITLE
Messenger start menu shortcut being readded upon reboot (Windows)

### ISSUE THREAD

**Issue by darrylr** [Aluxian/Facebook-Messenger-Desktop#187]
What the title says. I delete it every time only for it to come back. I don't need it there. Thanks for the great app by the way.

**Comment by Sytten** [comment]
Not sure what you want to say, not very clear.
Please try the app to see if you still have that problem.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it.
Feel free to open a new issue if you still have that problem.
