### ISSUE TITLE
OS X: Nwjs window stuck above menu bar

### ISSUE THREAD

**Issue by sedouard** [Aluxian/Facebook-Messenger-Desktop#188]
Seems really silly but I can't actually the window from under the menu bar. I think this happened while moving things around in my dual screen setup.
<img width="926" alt="screen shot 2015-07-20 at 9 46 08 am" src="https://cloud.githubusercontent.com/assets/3053263/8781497/39b37b04-2ec4-11e5-8703-c79bd4128813.png">

**Comment by Redeagle48** [comment]
I had the same issue as you. I was working with my dual screen setup and the app windows got "stuck" in the external monitor. I can't use this app since I can see the window.

**Comment by sedouard** [comment]
I figured it out @Redeagle48 . Dumb UX from OS X. You can grab windows on the left or right edge. Just 'grab' it with your mouse and it should readjust itself on the screen. Closing this one out.
