### ISSUE TITLE
VKontakte Chat for Desktop

### ISSUE THREAD

**Issue by nalexeyev** [Aluxian/Facebook-Messenger-Desktop#190]
VKontakte (http://www.similarweb.com/website/vk.com) is a Wolrd's 5th and CIS' first social network and as for moment they don't have good desktop messaging app (IMHO). Would you consider it?

**Comment by Aluxian** [comment]
Do they have a website/page with just the chat?


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Tue, Jul 21, 2015 at 8:23 pm, Nikolay Alexeyev < notifications@github.com [notifications@github.com] > wrote:
VKontakte ( http://www.similarweb.com/website/vk.com
[http://www.similarweb.com/website/vk.com] ) is a Wolrd's 5th and CIS' first social network and as for moment they don't
have good desktop messaging app (IMHO). Would you consider it?

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/190] .[https://github.com/notifications/beacon/ABWmdmwdlVRFBoSh2gGz7JckhFe2AXQJks5ofnepgaJpZM4Fc78W.gif]

**Comment by nalexeyev** [comment]
vk.com/im

**Comment by Aluxian** [comment]
Thanks, I'll look into it when I have time (next month).


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Tue, Jul 21, 2015 at 8:26 pm, Nikolay Alexeyev < notifications@github.com [notifications@github.com] > wrote:
vk.com/im

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/190#issuecomment-123408991] .[https://github.com/notifications/beacon/ABWmduM2-Feca0wxQvbCmxBVjdJyCD14ks5ofng3gaJpZM4Fc78W.gif]

**Comment by nalexeyev** [comment]
Thank you so much! Think, you can estimate at couple millions of downloads. I'll be the first)

**Comment by Sytten** [comment]
Should be easy to do a web wrapper around that website, but I dont have the time nor the interest.
