### ISSUE TITLE
Menu bar & dock icon to show number of unread messages

### ISSUE THREAD

**Issue by GandalfSaxe** [Aluxian/Facebook-Messenger-Desktop#193]
I would like an option to have the menu bar icon show a number for the amount of unread messages - just like Telegram.

EDIT: The same for the dock icon would be great.

**Comment by devilirium** [comment]
The [current library](https://github.com/nwjs/nw.js/wiki/Tray) only enables the loading of images from the filesystem. While we could certainly generate png and tiff images for your requested behaviour: that would take time, processing power and space from our drive. If Aluxian thinks that this is a good idea I could hop on it.

**Comment by Aluxian** [comment]
@devilirium I like the idea of showing the number of unread messages, but I'm not going to do it in this repo. I am switching to Electron. After I finish https://github.com/Aluxian/electron-superkit I will start rewriting the app on top of it. It'd be great if you could join in then! Actually, now that I think about it, I'd really like to chat with users will working on the app. For the next 2 weeks I'm going to be working on something, but after that, I'll start working on the new app.

**Comment by devilirium** [comment]
Sure, I'll join when you are ready :) 
I'll be working on something else until then

**Comment by Sytten** [comment]
As said before its not a feature we can easily do right now.
Meanwhile feel free to test the new beta, see this post https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
