### ISSUE TITLE
Toggle app (through Alfred) does not work

### ISSUE THREAD

**Issue by GandalfSaxe** [Aluxian/Facebook-Messenger-Desktop#194]
I use Alfred for shortcuts to all kinds of apps with the option “Toggle visibility for apps”. This feature works with Goofy but not Messenger for Desktop, so I’ll probably go back to Goofy for now (though it’s missing call / video call features.

I use Opt + 3 to open/close my main messenger app. Pressing Opt + 3 opens the app, pressing Opt + 3 hides the app again. In that way, it’s really fast to open the app, use it and hide it again just simply by toggling Opt + 3. With Messenger for Desktop this doesn’t work so I have to use Opt + 3 to show the app and Cmd+H to hide the app.

EDIT: I've noticed that the app doesn't show up in the upper left corner as all apps usually does when in focus. This could be the cause?

**Comment by kitze** [comment]
@GandalfSaxe off-topic, but can you share your workflow please? :)

**Comment by GandalfSaxe** [comment]
Sure. Do you mean my overall workflow or specifically my Alfred workflow as a file?

**Comment by GandalfSaxe** [comment]
This is just a rough / quick description I made from hammering on the keyboard for 10 minutes.
Simply put, the Opt button is perfect for application shortcuts in OS X. I don't need to have access to a lot of rarely used symbols as much as I need to quickly switch between applications.

1. APP SHORTCUTS (via Alfred)

Opt + ` : Sublime Text
Opt + 1: Finder
Opt + 2: Safari
Opt + 3: Goofy
Opt + 4: Spotify

Opt + 8: VLC
Opt + 9: Mathematica
Opt + 0: iTerm 2

Opt + Shift + ` : Skim
Opt + Shift + 1: Preview
Opt + Shift + 2: Chrome
Opt + Shift + 3: Telegram
Opt + Shift + 4: Radiant Player

Opt + Q: Reminders
Opt + W: Evernote
Opt + L: Lastpass

Opt + S: A frequently used GDrive doc
Opt + D: A frequently used GDrive doc

Opt + Z: Mail
Opt + C: Sunrise Calendar
Opt + X: Beeminder (website) - will soon change this to "Do not disturb" via script

Cmd+Shift+5: Screenshots folder (from screenshots taken from Cmd+Shift+3 etc.)

2. WINDOWS MANAGEMENT (via BetterSnapTool)
Opt+Ctrl+Shift+Left: Moves any window to left half of screen - similar to Win + left on windows
Opt+Ctrl+Shift+Right: Moves any window to right half of screen - similar to Win + right on windows
Opt+Ctrl+Shift+Up: Maximizes any window - similar to Win + up on windows

3. CLIPBOARD MANAGER (via Alfred)

4. CheatSheet

5. TextExpander

**Comment by Aluxian** [comment]
I think I’ll use this too, thanks for sharing!


On 24 Jul 2015 at 18:24:29, GandalfSaxe (notifications@github.com) wrote:

This is just a rough / quick description I made from hammering on the keyboard for 10 minutes.
Simply put, the Opt button is perfect for application shortcuts in OS X. I don't need to have access to a lot of rarely used symbols as much as I need to quickly switch between applications.

APP SHORTCUTS (via Alfred)
Opt + ` : Sublime Text
Opt + 1: Finder
Opt + 2: Safari
Opt + 3: Goofy
Opt + 4: Spotify

Opt + 8: VLC
Opt + 9: Mathematica
Opt + 0: iTerm 2

Opt + Shift + ` : Skim
Opt + Shift + 1: Preview
Opt + Shift + 2: Chrome
Opt + Shift + 3: Telegram
Opt + Shift + 4: Radiant Player

Opt + Q: Reminders
Opt + W: Evernote
Opt + L: Lastpass

Opt + S: A frequently used GDrive doc
Opt + D: A frequently used GDrive doc

Opt + Z: Mail
Opt + C: Sunrise Calendar
Opt + X: Beeminder (website) - will soon change this to "Do not disturb" via script

Cmd+Shift+5: Screenshots folder (from screenshots taken from Cmd+Shift+3 etc.)

WINDOWS MANAGEMENT (via BetterSnapTool)
Opt+Ctrl+Shift+Left: Moves any window to left half of screen - similar to Win + left on windows
Opt+Ctrl+Shift+Right: Moves any window to right half of screen - similar to Win + right on windows
Opt+Ctrl+Shift+Up: Maximizes any window - similar to Win + up on windows

CLIPBOARD MANAGER (via Alfred)

CheatSheet

TextExpander

**Comment by GandalfSaxe** [comment]
Np. Link for the workflows as files so you can download an import, then change to your needs: https://dl.dropboxusercontent.com/u/15389385/mathematica_tutorials/alfred_workflows.zip

**Comment by kitze** [comment]
Thank you very much!

**Comment by Sytten** [comment]
Is this issue resolved?
Adding shortcut to the software is a feature I want to implement in the future.
Meanwhile please see the beta.
More information here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

For the record, I'm also adding a link to the Goofy app (https://github.com/danielbuechele/goofy)

**Comment by GandalfSaxe** [comment]
Just re-installed to test this. Yes, this issue is resolved 👍
