### ISSUE TITLE
Ubuntu Touch

### ISSUE THREAD

**Issue by fredrikfritte** [Aluxian/Facebook-Messenger-Desktop#197]
I really really wanna have this app for my BQ 5HD phone, guess the Meizu guys wanna have it aswell :)

Is it possible?

**Comment by Aluxian** [comment]
Sorry, this is not something I'm interested in doing.

1. If `messenger.com` doesn't work on your phone, it won't work if I create an app either (or I'd have to find some fixes, i.e. hacks).
2. Are you running Flyme OS? Isn't that based on Android? If it is, I doubt that Android apps don't work on it. Try to install Facebook's mobile messenger from the app store.

**Comment by fredrikfritte** [comment]
Okidoki, no im Using an updated Ubuntu Touch, got the BQ Ubuntu edition

**Comment by Sytten** [comment]
Closing
