### ISSUE TITLE
Giphy Support

### ISSUE THREAD

**Issue by CheezeCoder** [Aluxian/Facebook-Messenger-Desktop#198]
Hi, great app!

I'd love to see some way of integrating support for 3rd party apps for messenger for desktop.  Mainly I use giphy on the mobile facebook messenger, but it would be great to somehow get them working for the desktop version.  

Keep up the awesome work!

**Comment by HRoland1** [comment]
That's Facebook's task not @Aluxian's. :(

**Comment by CheezeCoder** [comment]
How is it Facebook's task?  3rd party apps ARE available via Facebook's messenger app.  So I am assuming there might be a way to support for example GIPHY in Facebook-Messenger-Desktop.  If not through Facebook directly, then through Giphy's multiple methods of embedding GIFs....  or even custom solution using Giphy's API

**Comment by HRoland1** [comment]
No I was just telling you that this doesn't depend on @Aluxian. Btw it's Facebook's task to make messenger.com compatible with these 3rd party apps.

**Comment by Sytten** [comment]
Yes as @HRoland1 said, we don't have any control on that since we are only a web wrapper ariound their website.
Meanwhile, please try the new beta.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
