### ISSUE TITLE
Window refuses to draw.

### ISSUE THREAD

**Issue by vtmarik** [Aluxian/Facebook-Messenger-Desktop#199]
I was using messenger alongside VLC media player, and i selected VLC to always on top. Shortly after, I found that I could no longer call up the window for messenger to chat in. I'm not sure if that was the actual cause, but it's the only thing unusual i've done while running the program.

Windows 8.1
Intel Core i7, nVidia Geforce 840M

**Comment by Sytten** [comment]
Please try the new beta to see if your problem is still present.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Feel free to open a new issue if you still have the problem.
