### ISSUE TITLE
View links on default browser

### ISSUE THREAD

**Issue by glimy** [Aluxian/Facebook-Messenger-Desktop#20]
Since the preferences is coming later, I guess maybe you can allow users to view links via your app or default browsers. Or maybe CMD + click to view on default browsers while normal click remains the same as what you did.

**Comment by sgultekin** [comment]
+1

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/54b2b01a5626666228fdae7ef92b893849260cf7
