### ISSUE TITLE
Minimizing issue

### ISSUE THREAD

**Issue by ramodin91** [Aluxian/Facebook-Messenger-Desktop#204]
When I try to minimize the windows so I can see only the bubbles for contacts, it also breaks the chat window and it doesn't bring my text bubbles to the left.

**Comment by Sytten** [comment]
The window must be at a minimum size at all time, their is a limit on how responsive the messenger.com website is. 
If you still like the software, please try the beta recently released.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458.
