### ISSUE TITLE
Sticky conversations

### ISSUE THREAD

**Issue by orschiro** [Aluxian/Facebook-Messenger-Desktop#206]
Hi all, 

Does the Facebook API support to make certain conversations sticky at the top?

Thankfully,

Robert

**Comment by Sytten** [comment]
Hi,

First of all I must say that we don't use the facebook API. 
The software is only a wrapper around the website messenger.com
Our framework doesnt allow us to do sticky conversations...
sorry about that

**Comment by orschiro** [comment]
Alright. Thanks for your feedback though!
