### ISSUE TITLE
Extras

### ISSUE THREAD

**Issue by Radien21** [Aluxian/Facebook-Messenger-Desktop#211]
Hi could you please add the following features to this wonderful app: Allow the app to run in the background so that msgs can be received and notifications will show but the GUI is not running. Add some kind of emoji input.

Thanks

**Comment by lesmo** [comment]
It now supports background running and notifications. Emojis are something apparently not yet explored.

**Comment by Sytten** [comment]
This is not an issue, it can already runs in background.
Please see the beta for a more up to date software: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
