### ISSUE TITLE
Multiple process instances

### ISSUE THREAD

**Issue by AlexanderB1290** [Aluxian/Facebook-Messenger-Desktop#212]
After installing, the app is shown in the notification bar. If the user pin the app in the taskbar and closes the app, he closes also the process instance, which is pinned to the taskbar, but the process continue to work in the notification area. If he start the app from the same pinned icon in the taskbar, a new process is created in the notification area (not opening the existing one) or it is not open at all. This cause several instances of the process to appear in the notification area and in the task manager.
This problem appear on Windows 8.1 and 10.

**Comment by Sytten** [comment]
This issue is resolved in the beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
