### ISSUE TITLE
Please Make a Facebook Messenger support for Windows Apps

### ISSUE THREAD

**Issue by DevHamid** [Aluxian/Facebook-Messenger-Desktop#214]
Hello, I trying Facebook Messenger for Dekstop and I Like that, but please make Facebook Messenger available for Windows 10 Apps with live tile support, thanks :+1:

**Comment by AlexanderB1290** [comment]
Turn on the notifications for Windows and you will get them in the notification area.

**Comment by sinagat96** [comment]
Use

**Comment by sinagat96** [comment]
Ok

**Comment by Sytten** [comment]
Their is already an application on the windows store if you want to use it. Our current framework doesn't allow us to make Windows App sorry.
