### ISSUE TITLE
Active contact can sometimes change by itself.

### ISSUE THREAD

**Issue by darrylr** [Aluxian/Facebook-Messenger-Desktop#216]
Sometimes when I'm typing, the active contact can change seemingly of its own accord - so say I'm typing a message to Person A, sometimes the chat window will change to Person B (with the message continuing on in that chat) which can and has lead to me sending the wrong people messages.

It seems almost entirely random but only happens when I'm actually typing, almost as though it's a hotkey I'm pressing, but I'm not using abnormal inputs, simply alphanumeric. Thanks.

**Comment by Sytten** [comment]
I have not seen that issue in more than a year of daily usage.
Please try the beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you still have the problem, please open a new issue
