### ISSUE TITLE
Width of text-cloud box

### ISSUE THREAD

**Issue by Atteru** [Aluxian/Facebook-Messenger-Desktop#220]
![bez tytulu](https://cloud.githubusercontent.com/assets/13839075/9317242/9fd703c4-453a-11e5-9cc2-65eae073a8eb.jpg)
Could you delete or set to much lower min-width of chat window??
As it is in attached screenshot. Unfortunately I did it by editing html code in temp folder, so it last only until I close app.

It is really bothersome for people with small screens on laptops like me :)

**Comment by Sytten** [comment]
Please try the new beta, we reduced it.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you feel its still a problem, please open a new issue
