### ISSUE TITLE
Windows 10 notifications not showing

### ISSUE THREAD

**Issue by binarydad** [Aluxian/Facebook-Messenger-Desktop#223]
Fresh install, rebooted Windows, and notifications aren't popping out or showing in the notifications panel. All I see is the tiny, red icon on the tray icon.

**Comment by frostfire64** [comment]
Did you try to enable desktop noitifications in the web-app?

**Comment by Sytten** [comment]
Please try the new beta, this should be resolved.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Feel free to open a new issue if you still have problems.
