### ISSUE TITLE
Right click menu gets in the way when right clicking a message to delete it or see its timestamp

### ISSUE THREAD

**Issue by ekolis** [Aluxian/Facebook-Messenger-Desktop#225]
The menu should not be displayed if you're right clicking on a message.

**Comment by sotosgray** [comment]
When you right click on the message you can just scroll the mouse a bit and the menu should disappear, leaving only the timestamp and the delete option

**Comment by ekolis** [comment]
No, that doesn't work. Maybe Mac menus disappear or something, but Windows menus don't work that way...

**Comment by Sytten** [comment]
I deleted this ugly right click menu in the beta.
Please see: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
