### ISSUE TITLE
Small window size cuts the chat window

### ISSUE THREAD

**Issue by Aceship** [Aluxian/Facebook-Messenger-Desktop#227]
![ss 2015-08-23 at 11 10 48](https://cloud.githubusercontent.com/assets/5337323/9426762/c01dfd30-4987-11e5-8cfe-5e0b1cc8e947.png)
when using small window , the window only show half of the window, making it almost impossible to see chat on small window

**Comment by Sytten** [comment]
This problem isnt present anymore in the new beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
