### ISSUE TITLE
App window stays blank when trying to report a issue.

### ISSUE THREAD

**Issue by skimnd** [Aluxian/Facebook-Messenger-Desktop#231]
I see a bug at messenger notifying that someone chats me in, is too fast. then when i try to report it in app using the report in settings its stay in blank page.

![messager_error](https://cloud.githubusercontent.com/assets/7055111/9539862/72844e9c-4d8a-11e5-9147-a08c98b9c75d.png)

Im using windows 10

**Comment by Sytten** [comment]
The problem isn't there anymore, at least on my computers.
Please try our new beta. See #458 
If you still have that problem, please open a new issue...
