### ISSUE TITLE
Video playback dont work

### ISSUE THREAD

**Issue by TheHaso** [Aluxian/Facebook-Messenger-Desktop#232]
If a friend send a video with his phone using messenger, the desktop app wont play them. Only loads and black playback screen.

**Comment by liang6141** [comment]
Download ffmpegsumo file (win32/64) latest version add to Messenger folder

**Comment by TheHaso** [comment]
it is already in the folder

**Comment by liang6141** [comment]
Replace the new file in  the destination~ pls try ffmpegsumo file 32/64bit

**Comment by TheHaso** [comment]
Hmm, replaced it from dll-files and it seems to be working now. Thanks

**Comment by Takuaraa** [comment]
Where can I download the ffmpegsumo file?
Sorry, I'm new.
