### ISSUE TITLE
How to fixed Unicode font

### ISSUE THREAD

**Issue by ashickurnoor** [Aluxian/Facebook-Messenger-Desktop#235]
It is a great application. But I am facing unicode font issue. Please have a look
<a href="http://imgur.com/YQQVTHQ"><img src="http://i.imgur.com/YQQVTHQ.png?1" title="source: imgur.com" /></a>

**Comment by Sytten** [comment]
Can you try the latest beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
We don't handle the font rendering so it must be a problem with the chromium browser.
If you still have that problem, please open a new issue.
