### ISSUE TITLE
gulp pack:win32 don't auto-create dist directory

### ISSUE THREAD

**Issue by VarunAgw** [Aluxian/Facebook-Messenger-Desktop#238]
I get this error on Windows 10 x64

```
Output: "D:\Facebook-Messenger-Desktop\dist\MessengerSetup.exe"
Can't open output file
Error - aborting creation process
[17:39:17] Finished 'pack:win32' after 17 s
```

Creating the `dist` directory manually fixed this

**Comment by Sytten** [comment]
Was fixed after you opened the issue, is not a problem anymore. Thanks.
Please take a look at our latest beta if your are still interested by the software.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
