### ISSUE TITLE
Notification bubble on the icon on dock not working (OSX Yosemite)

### ISSUE THREAD

**Issue by Sosinondodrore** [Aluxian/Facebook-Messenger-Desktop#240]
The notification bubble on the icon on the dock with a number in it that shows the number of new messages either blinks and dissapeares or doesn't show at all.

**Comment by muggahtee** [comment]
I also have this problem on 10.10.4 (14E46)

**Comment by msimon3** [comment]
+1

**Comment by Sytten** [comment]
Please try the new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If it is still an issue, please open a new issue.
