### ISSUE TITLE
Desync between client and server regarding active time?

### ISSUE THREAD

**Issue by ekolis** [Aluxian/Facebook-Messenger-Desktop#241]
"Active 1m ago" when user is actually active now, and "active 2m ago" or something when user was not active for a while (until I type something to "refresh" it, then it's 39m or whatever)

**Comment by Sytten** [comment]
This refresh time is handled by facebook, not our fault if its poorly handled. Sorry.
If you still want to use the application, please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by ekolis** [comment]
Really? That's odd; I do see "active now" on the official mobile app; I never see it on your app. The "refresh" issue I have noticed on the mobile app, though.

**Comment by Sytten** [comment]
I see the active now all the time :)
And yes facebook seems to have trouble with this active time.
