### ISSUE TITLE
The title flickering in title bar 

### ISSUE THREAD

**Issue by NoNameProvided** [Aluxian/Facebook-Messenger-Desktop#242]
GIF attached showing the issue. It is happening all the time as soon as I start messenger until I don't close it. (Windows 10 Insider Preview [Version 10.0.10532])

![Gif showing the issue](https://cloud.githubusercontent.com/assets/4706265/9820163/5e8f951c-58b2-11e5-917f-67ff69113f35.gif)

**Comment by saper-2** [comment]
I have this issue too, "Messanger" / "Facebook" text flickering...
Windows: Win 7 x64

**Comment by lucas13lab** [comment]
I have this issue Too

Windows 10 x64

**Comment by malithjkmt** [comment]
I gave up using this app months ago because of this issue. Sadness is that when I come back, that bug is still here :(
Windows 8.1 x64

**Comment by mrbax** [comment]
Issue still present even on first run after install.

**Comment by NoNameProvided** [comment]
After restarting the app, this issues should be gone, it only occurs on the first run or if you logout and login again.

**Comment by Sytten** [comment]
Is this still an issue?
Please try our new beta (see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458).

**Comment by krazyjakee** [comment]
Can confirm, it's only on first login/load. Note also that the CPU usage sky-rockets also.

**Comment by Sytten** [comment]
Which version used?
and is it on windows only?

**Comment by saper-2** [comment]
Hi,

I don't see this issue anymore, but now I'm on Win10.
My cpu usage was rather normal, if Messanger was hogging a lot of cpu I would just kick him out (I'm quiet advanced user and I monitor running processes, cpu & ram usage).

**Comment by krazyjakee** [comment]
@Sytten this issue only affects the windows client.
There is no version listed in the about menu or any other menu so I can't help you. It's the latest downloadable binary from the website.

**Comment by saper-2** [comment]
Yes, there is no version information. Even in exe file too.

**Comment by Sytten** [comment]
Well I have been releasing a beta (V1.5.0) that resolve most of the issues with the app.
Some have trouble with it on W10, but it should resolve the flickering title.
