### ISSUE TITLE
[High-Priority] Application doesnt re-open when closed.

### ISSUE THREAD

**Issue by Redy93** [Aluxian/Facebook-Messenger-Desktop#243]
Everytime I close messenger and I try to reopen it, it actually doesnt comes up. So, what I usually do is close the still running process in the task manager to re-open it again. Seens that the application doesnt actually sign out just by closing the window.

That's annoying, please, fix.

I'm using windows 8.1 64 bit.

**Comment by jackwilsdon** [comment]
This is most likely related to #239. I think my suggestion in that thread may be the root cause of it.

**Comment by Sytten** [comment]
When you close the application it goes in the system tray, thats why you think its not quiting properly.
This is not a bug, its actually a quite handy feature.
If you still the software, please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
