### ISSUE TITLE
Zoom feature similar to the browser one

### ISSUE THREAD

**Issue by alexandruantochi** [Aluxian/Facebook-Messenger-Desktop#244]
You could make a zoom feature even though the window is maxed out, similar to that of browsers (Firefox Ctrl +) for example. 

It's perfect if you are connected to a TV and you are sitting further away. Currently the text changes the size a little bit when you maximize the window.

**Comment by Sytten** [comment]
Yes this feature as been requested many time and will be implemented in a future beta.
Meanwhile please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
I will close this issue since we have many duplicates.
