### ISSUE TITLE
Wrong Popup

### ISSUE THREAD

**Issue by Redy93** [Aluxian/Facebook-Messenger-Desktop#245]
So, basically it doesnt open messenger at all, but this other window:

![image](https://cloud.githubusercontent.com/assets/11138391/9838666/690a08c8-5a39-11e5-9cb3-826add99c4d1.png)

I'm using windows 8.1.

**Comment by Sytten** [comment]
This is strange and you seem to be the only user affected. 
Please try our new beta (see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458).
There was probably a problem with the installation or removed some files by accident.
If you still have that problem, feel free to open a new issue
