### ISSUE TITLE
Doesn't seem to load properly.

### ISSUE THREAD

**Issue by Keyobii** [Aluxian/Facebook-Messenger-Desktop#246]
It won't load completely, I cannot call, or message anyone. I've tried reinstalling/running as admin/disabling anti-virus nothing has worked. 

![ss 2015-09-14 at 02 32 25](https://cloud.githubusercontent.com/assets/14272346/9846735/de7d9512-5a88-11e5-8846-e917c2b00999.jpg)

**Comment by Sytten** [comment]
Please try to delete the cache in appdata/local on windows.
Also, please try our new beta version.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you still have, feel free to open a new issue
