### ISSUE TITLE
No notifications on Linux

### ISSUE THREAD

**Issue by miguelzf** [Aluxian/Facebook-Messenger-Desktop#247]
Hi,

I've started using this app recently on Linux (didn't try it on other platforms),
and AFAICS there are no visual notifications, only sounds.
Sounds are too disturbing. I think the ideal notification would be a simple change
color in the taskbar window icon, or a flashing color (prefer simply a changed/bold color)

Honest feedback

**Comment by freefri** [comment]
For me the notifications open the default gnome notification with a preview of the message. You have to enable the notifications going to settings and click "Turn on desktop notifications"

**Comment by Sytten** [comment]
Notification are working well on linux right now,
Please try the new beta.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
