### ISSUE TITLE
The window title flashed improperly and no notification badge at dock icon on OSX

### ISSUE THREAD

**Issue by enginebai** [Aluxian/Facebook-Messenger-Desktop#252]
1. The window title changed quickly between the username who sent me a message and the app title.
<img width="92" alt="2015-09-21 10 11 23" src="https://cloud.githubusercontent.com/assets/3387462/9984388/2641469e-6049-11e5-80e4-2f8975368539.png">
<img width="106" alt="2015-09-21 10 11 42" src="https://cloud.githubusercontent.com/assets/3387462/9984394/310252a8-6049-11e5-9239-0888052f9899.png">

2. The notificaiton badge at dock icon does not show any number of unread message.
<img width="57" alt="2015-09-21 10 09 08" src="https://cloud.githubusercontent.com/assets/3387462/9984385/19d9eb72-6049-11e5-97d3-4048eb2d7fa8.png">

**Comment by bwbalazs** [comment]
I also have this problem on Mac OS X El Capitan.
I only experience flashing title on the first start, after closing and reopening the app it's working correctly.
However the lack of badges is annoying.

**Comment by Sytten** [comment]
The title change should now be slower in the new beta,
Ass for the other problem an issue is already open.
Please try out the beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
