### ISSUE TITLE
Ubuntu has experienced an internal error

### ISSUE THREAD

**Issue by orschiro** [Aluxian/Facebook-Messenger-Desktop#255]
Dear all, 

Each time I close the app it generates an error message dialog on Ubuntu 15.04.

Can someone reproduce this problem?

Thankfully,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/10094389/95f5b3c6-635f-11e5-9813-fe6bce2042b2.png)

**Comment by Igesef** [comment]
I'm experiencing the same issue on Ubuntu 14.04

**Comment by orschiro** [comment]
@Igesef 

Thanks for confirming. Is this application-specific or do you know if this happens with other nodejs applications, too? In that case I would report this back to the Ubuntu tracker.

**Comment by Igesef** [comment]
@orschiro 

It's application-specific. I've checked several other nw.js based applications and there were no such issues.

**Comment by orschiro** [comment]
Dear @Igesef,

Thank you for investigating this! Not that I have an immediate solution but maybe someone can trace this further. :+1: 

~ Robert

**Comment by aropop** [comment]
Same issue on ubuntu gnome 15.10

**Comment by Sytten** [comment]
Please try the new beta.
See this post: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Feel free to open a new issue if you still have problems.
