### ISSUE TITLE
Feature request: OTR encryption

### ISSUE THREAD

**Issue by selfagency** [Aluxian/Facebook-Messenger-Desktop#259]
Please add support for OTR encryption so that users may communicate over Facebook (mostly) securely.

There's a JS port [here](https://github.com/arlolra/otr).

**Comment by NoNameProvided** [comment]
This would require changes on the back-end of Facebook, so it couldn't be implemented.

**Comment by TheBlackViper1996** [comment]
Actually it wouldn't require any change on the back-end of Facebook to implement OTR as I use it all the time with Xabber (an Android messaging client)

**Comment by selfagency** [comment]
Indeed, OTR requires only an implementation in the client. As long as both people messaging use an app that has OTR support, you can use OTR over Facebook's messaging service. I use it with Adium currently.

**Comment by selfagency** [comment]
abandoning this ticket like this app's been abandoned
