### ISSUE TITLE
Feature Request: Add Facebook Messenger to the notification area on Linux

### ISSUE THREAD

**Issue by rick9791** [Aluxian/Facebook-Messenger-Desktop#261]
When opening Facebook Messenger, I would want that it would create an icon in the notification area:

![notification area](https://i.gyazo.com/16f47ba1f3f29c257e6fc96d416c2fb4.png)

Note that I am using LXDE (lxpanel).

**Comment by SoumenDass** [comment]
This would be much appreciated. I'm using Linuxmint Cinnamon DE.

**Comment by LastStarDust** [comment]
I am using Gnome 3 and I would love to have an icon in the notification area so the application can run in background and be opened only by clicking on the icon.

**Comment by Sytten** [comment]
This is fixed in the latest beta,
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
