### ISSUE TITLE
Request: Multiple threads at once

### ISSUE THREAD

**Issue by clarson8759** [Aluxian/Facebook-Messenger-Desktop#263]
Forgive me if this is to difficult to implement, or outside the scope of this project.

I really love the program, but I have a large monitor, and when I put it in full screen, the single thread I am using just spreads out.

It would be really awesome if it were possible to have multiple (2 or 3) full threads side-by-side at the same time.

If not, no worries. Thanks for making this awesome, beautiful tool!

**Comment by Sytten** [comment]
That won't be possible with the current framework, sorry.
But if you still like the app, please use its beta version.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it.
