### ISSUE TITLE
Dark themes colors

### ISSUE THREAD

**Issue by Lodufqa** [Aluxian/Facebook-Messenger-Desktop#265]
- Caller tittle should have color white instead of black-like in element with class "_17w2" (Probably) (color: white;)
- Link background should have "background-color:white" in element with class "_tih _3xn3 _3xn7" (Probably)
- Span in div (class _3eus (Probably)) "Last active ago title" in wide view should be white (color: white;)
- Input (class _58al (Probably)) "Search stickers" should have "background-color: white"
- Text color in settings->user_name (class _1ps0) should be white (color: white;)
- Text color in settings->Sounds_trigger (class _1pr_) should be also white (color: white;)

**Comment by Sytten** [comment]
Resolved in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
