### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by NoNameProvided** [Aluxian/Facebook-Messenger-Desktop#267]
@Aluxian 

The last commit was on 1. of August. Is the project abandoned?

**Comment by Aluxian** [comment]
Definitely not abandoned, I'm just having a hard time finding time for it.

On Fri, Oct 09, 2015 at 4:49 pm, Attila Oláh < notifications@github.com [notifications@github.com] > wrote:
@Aluxian [https://github.com/Aluxian]

The last commit was on 1. of August. Did the project abandoned?

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/267] .[https://github.com/notifications/beacon/ABWmdq9DZagWiO7KwgBxQFv3biIz3eqhks5o571ugaJpZM4GMGSM.gif]

**Comment by NoNameProvided** [comment]
Do you have time for review pull requests?

**Comment by Aluxian** [comment]
I don't sorry. Even if I merged it, I'd have to re-build everything and upload it + release the update. I'd rather use the time I have to work on the new Electron version.

**Comment by danielkornev** [comment]
Hello Aluxian, new Electron version sounds promising (given your passion for building the Electron Super Kit). What would be in the new version, though?

**Comment by cassiodoroVicinetti** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

Please close this

**Comment by Sytten** [comment]
@cassiodoroVicinetti Please tag me if you want me to see the message ;)
