### ISSUE TITLE
Picked up as threat by Avast

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#27]
Happened to me while downloading, reported by other 1 person.

**Comment by adityadalal924** [comment]
The latest release,v1.2.4, does not seem to have a false positive report from Avast

[VirusTotal](https://www.virustotal.com/en/file/bcbe96dd565ebcbb8506f962a68a35967add503f671b527506f8990aa1bfb522/analysis/1429282133/)

**Comment by Aluxian** [comment]
I will check again.

**Comment by Aluxian** [comment]
Avast is fine with it now.
