### ISSUE TITLE
Home and End key unexpected behavior

### ISSUE THREAD

**Issue by kevinwlau** [Aluxian/Facebook-Messenger-Desktop#272]
When typing in the chat box, hitting Home and End seem to send to the chat history above, rather than going to the front and end of the line in the chat box.

**Comment by Killmax** [comment]
Got the same bug on Mint 17.2 with Cinnamon.

**Comment by darrylr** [comment]
Same here, Windows 10. It's going to effect everyone because it's a change on Facebook's end, you can test it yourself on messenger.com. Pressing the up or down arrow keys emulate the old Home and End behaviour for me, but it's an annoyance for sure.

**Comment by Aurielle** [comment]
:+1: Would be glad for the fix directly in the app.

**Comment by kevinwlau** [comment]
I tested on messenger.com, but Home and End work perfectly fine there, as do up and down arrows.

**Comment by Aurielle** [comment]
Yes, I can confirm that as well, it seems like they fixed it. Just tested on messenger.com and then reloaded the client and home+end works as expected now.
