### ISSUE TITLE
ESC closes whole window

### ISSUE THREAD

**Issue by Dontsoft** [Aluxian/Facebook-Messenger-Desktop#275]
Close the Picture-View with ESC shuts down the whole app. Not just closes the picture windows.

**Comment by vinceh** [comment]
+1 done this a thousand times, and then you have to go to task manager and close all instances of Messenger to open it up again.

**Comment by Sytten** [comment]
This issue has been resolved in the latest beta,
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 for more information about it.
