### ISSUE TITLE
Dark theme - color of text in threadTitle is black which makes it almost unreadable 

### ISSUE THREAD

**Issue by localhost-dev** [Aluxian/Facebook-Messenger-Desktop#276]
Hi guys, there is a small issue with dark theme. 
Text in thread title is black and because of it it's hard to read it :)

Html code snippet:
```
<span class="_3oh-" data-reactid=".0.1.1.1.$threadTitle.0.0">
<span data-reactid=".0.1.1.1.$threadTitle.0.0.0">User Name</span>
</span>
```

**Comment by Sytten** [comment]
This is fixed in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
