### ISSUE TITLE
Missing Other's folder

### ISSUE THREAD

**Issue by jfreak53** [Aluxian/Facebook-Messenger-Desktop#279]
I like it, it's just missing one single feature. Well two that I have found.

1. It needs access to the other folder. Without this and Spam it really doesn't keep me from going to the web. It's like using it on my phone which I don't like.

2. It needs a tray bar icon so I can minimize it to the tray and not leave it sitting in my taskbar.

Other than that, great job!!

**Comment by Sytten** [comment]
Tray icon is solved.
No sure what you talk about when you seem the other folder.
Please remember that we are only a web-wrapper around messenger.com and we only provide the features facebook provides on the messenger.com page.

Please try our new beta.
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458

**Comment by Osyx** [comment]
Others folder is already there, just like in messenger.com. Press the gear icon and then "Message requests" and they are either already there or appear when you press "Show filtered messages".

**Comment by Sytten** [comment]
Thanks closed
