### ISSUE TITLE
Changeable themes feature

### ISSUE THREAD

**Issue by diegodelavega** [Aluxian/Facebook-Messenger-Desktop#28]
Is it possible to implement feature that allows user to change theme to dark one or specifically colours of elements and fonts which may be easier (and better IMHO)?
Thanks!

**Comment by Kingbalou** [comment]
Totally agree ! Maybe some options for an image as background of the app , or different color theme (randomly or not ) with different people we talking to , just like the Android 5 sms app.
But the app is perfect !

**Comment by Aluxian** [comment]
I will play with the CSS and see what I can do. Please keep in mind that this issue has lower priority than others.

**Comment by Kingbalou** [comment]
Don't worry ;)
Otherwise it run perfectly under Manjaro ArchLinux !

**Comment by Aluxian** [comment]
I'm happy to hear that :)

**Comment by jkaberg** [comment]
+1, a balanced dark theme would be very appreciated for thoes who never leaves thire caves (me) :laughing:

**Comment by adityadalal924** [comment]
**[Dark theme CSS (gist)](https://gist.github.com/adityadalal924/da310f784d786210fe93)** 

Source: [this](https://userstyles.org/styles/112397/facebook-messenger-the-dark-side) Stylish theme

**Comment by auscompgeek** [comment]
@adityadalal924 I keep the style in a Gist myself: https://gist.github.com/auscompgeek/f9f0dae3a1fd563b4435

**Comment by adityadalal924** [comment]
@auscompgeek When I posted, there was no gist for the CSS. Updated my comment to link to your Stylish theme :+1:

**Comment by auscompgeek** [comment]
@adityadalal924 If you take a look at the history, it's actually existed since day 0 :)

**Comment by auscompgeek** [comment]
For those interested in keeping track with development, I have now moved my dark theme to a GitHub repo: https://github.com/auscompgeek/fb-messenger-dark

**Comment by Aluxian** [comment]
Thanks, I’ll definitely update the themes in the next release.


	Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On 24 Jul 2015 at 13:51:12, David (notifications@github.com) wrote:

For those interested in keeping track with development, I have now moved my dark theme to a GitHub repo: https://github.com/auscompgeek/fb-messenger-dark
