### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by midnight917** [Aluxian/Facebook-Messenger-Desktop#282]
I can't install for some reason; I keep getting this error message. 

http://screencast.com/t/yOnOCsMnIlj

**Comment by djsigfried56** [comment]
Did you run the installer as admin?

**Comment by Sytten** [comment]
This should not be an issue anymore.
Please try our new beta. See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
