### ISSUE TITLE
Fixed application icon on Linux

### ISSUE THREAD

**Issue by Hori873** [Aluxian/Facebook-Messenger-Desktop#285]
Can you please set a default WM_CLASS for this application on Linux?
This way my DE can change this app's icon to my icon theme. All my icons are flat and square (Numix-Square theme) except for this app.
This is a very serious issue for me, as my desktop's aesthetics are very important.

**Comment by Killmax** [comment]
By my side, I got no problem with Numix-Circle on Cinnamon.
What is your DE?

You should try with numix-circle and then say here if you got the same results.

**Comment by Hori873** [comment]
GNOME 3.18. Also had this problem when I first tried this app on GNOME 3.14. Don't know about 3.16 tho as I didn't keep this app.
Same problem with Numix-Circle
As far as I know, GNOME relies on WM_CLASS in order to group windows in the taskbar/dock and to set their icons.
I made a simple bash script that can set the WM_CLASS once the application is started (also did it for WhatsApp) and it also checks for internet connectivity because the app will never finish loading if you launch it while you are disconnected, e.g. at startup. I can post the script here if it is allowed and anyone needs it

**Comment by yerbestpal** [comment]
Hori, I'm having similar problems with the WM_CLASS on i3wm. I basically need the WM_CLASS so i3 can force it to start on a certain workspace. Could you possible tell me it? I've tried a million different variants of messenger.

**Comment by Hori873** [comment]
It's pretty messed up but here you go: http://pastebin.com/TTm6bQmZ . It was made in a hurry but it works. Haven't got around to improve it since I don't really use this app that much

**Comment by Sytten** [comment]
This should be fixed in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If you still have problems, please open a new issue

**Comment by Hori873** [comment]
Hello, it is indeed fixed in the beta, thanks!

**Comment by Sytten** [comment]
Nice! Good to hear that :)
