### ISSUE TITLE
App goes to background when pressing Esc while viewing an image

### ISSUE THREAD

**Issue by eallik** [Aluxian/Facebook-Messenger-Desktop#295]
...and doesn't come back with Cmd+Tab — one has to manually click on the dock icon of app to foreground it.

This is on 1.4.3 and OS X 10.9.5.

**Comment by jackwilsdon** [comment]
Take a look at #178, #208, #209 (a fix for the issue) and #248. It may be the same issue?

**Comment by eallik** [comment]
Yes, these seem like the same issue! Is the fix already released or would I have to use the latest git master?

**Comment by jackwilsdon** [comment]
I'm not sure. It doesn't look like #209 has been merged, so master may not include the fix.

**Comment by Sytten** [comment]
I know whats the problem... I will correct it on my fork

**Comment by Sytten** [comment]
Problem solved.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
