### ISSUE TITLE
Cannot unzip on Windows

### ISSUE THREAD

**Issue by alexander-fischer** [Aluxian/Facebook-Messenger-Desktop#3]
After downloading, I tried to unzip the file with WinRAR and the standard Windows tool. With both it comes to the same result. The process stucks on 99% and after it ends, there is just an empty folder.
![messengerunzipfail](https://cloud.githubusercontent.com/assets/7881637/7101087/2902e290-e045-11e4-8c22-050d103f7864.PNG)

**Comment by Aluxian** [comment]
Since 1.2.0, an installer is used on Windows. No need to unzip anymore.
