### ISSUE TITLE
rpm package ??!!

### ISSUE THREAD

**Issue by MohamedTita** [Aluxian/Facebook-Messenger-Desktop#300]
what about .rpm ???

**Comment by jackwilsdon** [comment]
You can build an RPM package using `gulp pack:linux{32|64}:rpm`, however it doesn't look like one is being officially distributed.

**Comment by Sytten** [comment]
I will build them on my fork. Please check tomorrow.

**Comment by Sytten** [comment]
The only problem I see will be when you will want to update, since I cant know which package manager you use it automatically download the .deb
However, I found this updater: https://github.com/edjafarov/node-webkit-updater
I will try to implement it in messenger for desktop for easier updates.

**Comment by Sytten** [comment]
https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by ivanov17** [comment]
@Sytten thanks!

**Comment by Sytten** [comment]
No problem, tell me if you have any problem with it ;)

**Comment by Sytten** [comment]
The new beta release have rpm.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
