### ISSUE TITLE
can't uninstall 

### ISSUE THREAD

**Issue by felipe-milagres** [Aluxian/Facebook-Messenger-Desktop#302]
I tried to uninstall but...
1) the app isn't listed in "Programs and Features"
2) If I run Uninstall Messenger for Desktop.exe, the files still there

I am using windows 8.1

**Comment by heathernorvell** [comment]
I also cannot uninstall and i'm on windows 7.

**Comment by Sytten** [comment]
Check the uninstaller in the program directory.
The new version add it to the Programs and Features
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
