### ISSUE TITLE
No uninstaller in folder and it doesn't appear on "Add or remove programs" (windows 10)

### ISSUE THREAD

**Issue by Flerix** [Aluxian/Facebook-Messenger-Desktop#304]
As the title says, I can't find a way to uninstall the app, to free up some space, since I'm never using it anyway. Please help me with this one. :(

**Comment by Sytten** [comment]
Just delete the files in the program files. Thanks for reporting I will investigate...

**Comment by Sytten** [comment]
Resolved in the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
