### ISSUE TITLE
Chat windows not showing up

### ISSUE THREAD

**Issue by ltdan166** [Aluxian/Facebook-Messenger-Desktop#306]
Hello, 
I remembered trying to change the theme and my chat windows now doesn't load anymore.
I tried to uninstall the program, delete every traces of it in the registry and reinstall but nothing changes.

Do you have any idea what happened
![untitled](https://cloud.githubusercontent.com/assets/10234887/11912373/788f8f3c-a63a-11e5-9d89-5a2155f634a5.png)
 ?

**Comment by Sytten** [comment]
it is probably a bug with the framework nw.js, can't check since I don't have windows 10.
But you probably forgot to delete the Preference.json in AppData (so it keeps the faulty preference even when you reinstall)

**Comment by ltdan166** [comment]
Thanks man. It's the AppData folder that caused the problem.
