### ISSUE TITLE
Add "start minimized" option for windows please.

### ISSUE THREAD

**Issue by hoatongoc** [Aluxian/Facebook-Messenger-Desktop#308]
As the title, every time I start my PC, I have to close the window of this app. This is a bit annoying for me.

**Comment by Sytten** [comment]
That bugs me too, I will make in option for that. It should be too hard.

**Comment by Sytten** [comment]
Done! Just pushing to my fork. I will build the installers soon.

**Comment by hoatongoc** [comment]
Thanks :D

**Comment by Sytten** [comment]
https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by hoatongoc** [comment]
The installer can't even start on Windows 10?
So sad :(

**Comment by Sytten** [comment]
probably the packager I use isnt up to date. It a linux soft, I will check that...

**Comment by Sytten** [comment]
Should be working with the latest beta.
Please check https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
