### ISSUE TITLE
More than one sessions

### ISSUE THREAD

**Issue by champnaman** [Aluxian/Facebook-Messenger-Desktop#311]
It creates more than one session of this app. When I open the app from Start menu even when it was already running in the task bar, it creates it's another instance. 
I'm attaching a photo to make it more clear.

![untitled](https://cloud.githubusercontent.com/assets/5251592/12062206/d927a780-afbd-11e5-9199-b35a688152ed.png)

**Comment by Sytten** [comment]
Already resolved on my fork. Now only one instance of the app can be launched.
https://sytten.github.io/Facebook-Messenger-Desktop/
Cheers

**Comment by Sytten** [comment]
Resolved in the new beta release.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
