### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by cyberf4n** [Aluxian/Facebook-Messenger-Desktop#312]
Hi,
How can I make this minimize to tray? I am using archlinux

Thank you,

**Comment by Sytten** [comment]
Check my fork, its already resolved. Tell me if its working on arch.
Cheers

**Comment by nicholasamorim** [comment]
@Sytten just tried your fork and for information purposes, it works on Kubuntu 14.04.

**Comment by cyberf4n** [comment]
@Sytten works on Arch. Thanks a lot

**Comment by Sytten** [comment]
Good ;)

**Comment by davidmosna** [comment]
Working on Ubuntu 15.10 wily, thanks!

**Comment by davidmosna** [comment]
Works on Ubuntu 15.10 wily, thanks :)

**Comment by Sytten** [comment]
Resolved in the new beta release.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
