### ISSUE TITLE
Notifications on Windows 10

### ISSUE THREAD

**Issue by stephen714** [Aluxian/Facebook-Messenger-Desktop#313]
Great app!
A few issues, however!
I download the fork version today (2/1/16) but it still doesn't have a 'minimize to tray' option.  That would be great.
Also, the only notification on windows 10 is a sound.  Useful, but a popup would be awesome!

And perhaps a settings dialogue box to centralize everything?

Thanks!

**Comment by NoNameProvided** [comment]
There is a pop up,  just go to the settings (gear icon in the top left corner) and click on the turn on desktop notifications option.

**Comment by SimonMckeon** [comment]
On Windows 10, closing automatically minimizes to tray.

**Comment by shea-sollars** [comment]
Confirmed, notifications not working on Windows 10. I even tried forcing a notification in the developer tools, using the [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification).

**Comment by Sytten** [comment]
Should be resolved with the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Feel free to open a new issue if you still have problems.
