### ISSUE TITLE
Running without the SUID sandbox!

### ISSUE THREAD

**Issue by kaaboaye** [Aluxian/Facebook-Messenger-Desktop#315]
After build using "gulp build:linux64" command I can't start app

[user@pc:Facebook-Messenger-Desktop|master %]$ ./build/Messenger/linux64/Messenger
[9570:0104/175022:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

I'm using Arch linux

**Comment by jay-to-the-dee** [comment]
Getting this off the offical .deb on the web AND self-building using GULP :(

**Comment by Sytten** [comment]
This should not be an issue that prevents you from using the software.
Now its gone with the latest beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
