### ISSUE TITLE
REQUEST: Changing nicknames, chat colour, and chat emoji

### ISSUE THREAD

**Issue by imFlare** [Aluxian/Facebook-Messenger-Desktop#317]
Hey! so i heard that you can change nicknames, chat colour, and chat emoji on mobile, but i am unable to do this with the messenger. Is this possible to implement, or did i miss something?

Thank you! i love the app, its amazing!

**Comment by adamo000** [comment]
I love this app as well and I really miss for that options. It will be pleasure to use Messenger for desktop with this features on board :)

**Comment by supereii** [comment]
Same here. I would love to see that features on this app.

**Comment by NitsuSaiNeko** [comment]
Same. I currently change those using my phone but it would be really nice if I can just do it right in the messenger :D

**Comment by Sytten** [comment]
Heee this feature is available when you click on the information icon
