### ISSUE TITLE
Feature Request: On top option, contact is typing - indicator

### ISSUE THREAD

**Issue by adamo000** [Aluxian/Facebook-Messenger-Desktop#318]
Hi!

First of all I must tell that Messenger is one of the best app for facebook chat I've ever tested. 

I really miss two options not listed here. First one is a button which allows to put window on top. Second option that I miss in windows client is small icon or text, that other person is typing now to us (in active conversation). 

_________________________________________
Sorry for my bad English.

**Comment by NitsuSaiNeko** [comment]
I am able to see that people is currently typing though.
and the window on top feature, I just use a small program called Deskpin to pin any windows I want on top.

![ss 2016-02-01 at 10 51 29](https://cloud.githubusercontent.com/assets/12886318/12741989/67f67a2c-c936-11e5-91aa-74c4d3c0e0e9.png)

**Comment by Sytten** [comment]
Issue resolved then
