### ISSUE TITLE
Window Title Bug

### ISSUE THREAD

**Issue by lachycharts** [Aluxian/Facebook-Messenger-Desktop#319]
The window title both in the app and the task bar is constantly changing from "Facebook" to "Messenger" approximately 5 times per second. This always occurs and has happened since installation. Using Windows 7 Pro 64-bit.

**Comment by XeZrunner** [comment]
Can confirm, though only happens on first login, when it "detects" sign in from an unknown location and asks me whether I want to save the browser (I have that enabled in my Account settings). When I start up the app again, the bug is gone.

**Comment by ikishk** [comment]
I can confirm this behavior as well.  win7 x64.  after restart it no longer "flashes."

**Comment by Sytten** [comment]
Should be resolved.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
