### ISSUE TITLE
[REQ] In-app spellchecker

### ISSUE THREAD

**Issue by adidalal** [Aluxian/Facebook-Messenger-Desktop#32]
A spell-check, similar to that implemented in Chrome/Firefox would be great.

According to [this](https://github.com/nwjs/nw.js/issues/332) nw.js issue, it should be available in v0.13.

As a workaround until then, you can include a js spell checker like http://www.javascriptspellcheck.com/

**Comment by Aluxian** [comment]
Thanks, I will add this.

**Comment by orschiro** [comment]
Supporting this. A spell-check support would be great. Are multiple dictionaries possible?

**Comment by xanth** [comment]
Because of [JavaScript SpellChecks licence](http://www.javascriptspellcheck.com/Free) [Speller](https://github.com/past/speller/tree/master) may be a better standin till we have support in NW.JS

**Comment by toonamo** [comment]
this would be a really cool feature

**Comment by adityadalal924** [comment]
No need for a third-party JS, as it's now integrated into nw.js (as of 0.13.0-alpha1).
Use the `--enable-spell-checking` switch

(Though typo.js might be useful if waiting for a stable nw.js release....)

**Comment by thomasw** [comment]
:+1:

**Comment by wir3k** [comment]
i am vouching this idea aswell

**Comment by cannonfodderian** [comment]
This would be very useful,
