### ISSUE TITLE
App loading off the screen

### ISSUE THREAD

**Issue by gpn273** [Aluxian/Facebook-Messenger-Desktop#321]
Hi,

I've updated to the latest OS X (10.11.2) no so long ago and now the Facebook Messenger app now loads off the screen boundaries, I am unable to drag the app back down to the centre of the desktop as well. Would there be a configuration file which sets where the load app on the screen?

**Comment by Sytten** [comment]
Yes there is one. On mac I'm not very sure where it is located since I only use window and linux. Its a json file, so I imagine you can search for it...

**Comment by gpn273** [comment]
I was unable to find the file myself due to lack of information, however, I was unable to result the issue. I installed CCleaner and used it's built in uninstaller to remove the program and any traces of it, re-isntalled it and now the issue is resolved.
