### ISSUE TITLE
Video doesn't play

### ISSUE THREAD

**Issue by steelzeh** [Aluxian/Facebook-Messenger-Desktop#323]
Whenever someone sends me a video i can't see it in chat. Need to open facebook in browser to watch video.

**Comment by paflopes** [comment]
Same problem here (Ubuntu Gnome 14.04).

**Comment by NitsuSaiNeko** [comment]
same. Clicking on the video will try to play but it's all blacked out and nothing happens.

**Comment by Sytten** [comment]
Yes this is known and will be resolved in a future beta.
Meanwhile please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
