### ISSUE TITLE
Can't type Vietnamese :(

### ISSUE THREAD

**Issue by gaudorian** [Aluxian/Facebook-Messenger-Desktop#324]
I'm using Windows 10 Pro and just installed FB Messenger. But I can't type Vietnamese with Unikey (Application to type Vietnamese: http://unikey.org), I don't know why? 
Anyone can help me? Many thanks.

**Comment by hanhdt** [comment]
It work well for me, mate.

**Comment by minhman** [comment]
You need to open unikey with "Run as administration"

**Comment by Sytten** [comment]
Issue resolved
