### ISSUE TITLE
Can't create the installer on Windows because "dist" folder doesn't exist

### ISSUE THREAD

**Issue by wblondel** [Aluxian/Facebook-Messenger-Desktop#329]
Hi!

This is what happens at the end of the creation of the installer on Windows : 
```
Output: "C:\Facebook-Messenger-Desktop\dist\MessengerSetup.exe"
Can't open output file
Error - aborting creation process
```

I tried with Administrator rights but it does not solve the issue.

The only way to solve the issue is to create the "dist" folder before running the "gulp pack:win32" command.

**Comment by NoNameProvided** [comment]
Did you try to create a folder named 'dist' before you build it?

**Comment by wblondel** [comment]
It is the solution I provided :) "The only way to solve the issue is to create the "dist" folder before running the "gulp pack:win32" command."
