### ISSUE TITLE
Windows 7: White empty window

### ISSUE THREAD

**Issue by acseven** [Aluxian/Facebook-Messenger-Desktop#33]
Hi,
Thanks for developing this, but I can't seem to make it run on Windows 7 32bit. I get this empty white screen with app.html as a title.
Thanks
![scrn](https://cloud.githubusercontent.com/assets/1176371/7155229/f341b1d2-e354-11e4-8e8f-23015e7b39cf.png)

**Comment by adityadalal924** [comment]
Can you verify that going to the http://messenger.com site in your browser works?
If that works, try the following and report back:

1. Go to `./src/package.json`
2. Change `toolbar: false` to `true`
3. Build & Run the app
4. Click the settings icon near the address bar to get to the Chrome Dev Tools window
5. Look for errors, screenshot the output of that window and post here

**Comment by Aluxian** [comment]
@acseven Can you please download the latest version, right click somewhere inside the app, select "Open Dev Tools" and make a screenshot (or copy) of what you see in there?

**Comment by acseven** [comment]
I'm sorry for the delay on replying to your comments; I can't replicate my initial issue because I'm no longer in the same office as before. If I do get a chance to test this I will get back to you, but for now I would recommend closing this issue.

Thank you
