### ISSUE TITLE
Clips Infinite Loading

### ISSUE THREAD

**Issue by 6uui** [Aluxian/Facebook-Messenger-Desktop#331]
Clips do not work at all. They just go into a infinite loading.
![problem](https://cloud.githubusercontent.com/assets/16867021/12537883/eab97b0a-c2c2-11e5-81a4-7e5ee7c0e5f4.png)

**Comment by Sytten** [comment]
Known issue will be resolved in the next beta.
Meanwhile please check https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
