### ISSUE TITLE
Windows Notification doesn't show contact photo as suggested on website

### ISSUE THREAD

**Issue by G-Pereira** [Aluxian/Facebook-Messenger-Desktop#335]
It doesn't show any picture at all
BTW i have Windows 10

**Comment by Sytten** [comment]
Thats a wont fix for now. 
Maybe with the new chrome notifications we can do something.

**Comment by Sytten** [comment]
It now does with the new chrome notifications.
Please use the latest beta https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.1
