### ISSUE TITLE
Type a message not changing color with theme

### ISSUE THREAD

**Issue by soccernerd05** [Aluxian/Facebook-Messenger-Desktop#337]
I love this app, I've used it for months now and it's perfect. Unfortunately, just recently for some reason the type a message part of the app isn't changing theme along with the rest of the app. I'm attaching a picture to show what the issue is like. 
![messengercapture](https://cloud.githubusercontent.com/assets/16909181/12600424/47a55404-c45f-11e5-9840-1c93b1910f9f.PNG)

When I try to type, the text shows up in white and it is very difficult to read what I'm typing. I'm not sure how this happened but I'd greatly appreciate any help! 

Thanks!

**Comment by Majki** [comment]
Confirming on Linux Mint 17. 
![selection_102](https://cloud.githubusercontent.com/assets/1552256/12606630/459801fa-c4cf-11e5-9359-a1e0177d85a6.jpg)

**Comment by skjnldsv** [comment]
Same on Arch 4.3.3-3-ARCH

**Comment by iRuisu** [comment]
Ditto, same issue found on Windows.

**Comment by orangeSkySTUDio** [comment]
Temporary fix: Right click -> launch dev tools -> on the bottom tabs click on search -> search for 4rv3 -> click on it and make sure line 34 from the css above is focused -> modify background-color:rgba(255, 255, 255, .95) TO background-color:rgba(255, 255, 255, .05). Just remove the last 9 and add a 0 instead. Change will not save upon exiting application.

**Comment by orangeSkySTUDio** [comment]
![11](https://cloud.githubusercontent.com/assets/11435594/12625295/db9b9c0e-c53b-11e5-83de-aeeb098c0977.jpg)
![22](https://cloud.githubusercontent.com/assets/11435594/12625298/dba434ae-c53b-11e5-9008-b9d33734b11e.jpg)
![33](https://cloud.githubusercontent.com/assets/11435594/12625296/db9d9568-c53b-11e5-86f5-268940d029fb.jpg)
![44](https://cloud.githubusercontent.com/assets/11435594/12625297/db9f0e5c-c53b-11e5-8419-2ac084df595d.jpg)

**Comment by beyael** [comment]
On Windows, I get this error when I try to modify that line (and the color is not affected in any way).
![2016-01-27 11_34_13-new notification](https://cloud.githubusercontent.com/assets/16925653/12625754/044d2b56-c4ea-11e5-9b83-2e8f369120e2.png)

**Comment by orangeSkySTUDio** [comment]
Click on X on top ( or just press escape ) and try to modify it again. If not, exit the dev tools ( not messenger ), launch dev tools and now you have this list again. You can skip images 1-3 and just replace the 9 now.

**Comment by beyael** [comment]
Hmm I had done that before, but it didn't work.

Tried again right now and I could modify the line without issues (did nothing differently).

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Resolved
