### ISSUE TITLE
White "Type a message..." text box in dark mode

### ISSUE THREAD

**Issue by ayylmaoxx** [Aluxian/Facebook-Messenger-Desktop#338]
![screen shot 2016-01-28 at 12 50 24 am](https://cloud.githubusercontent.com/assets/16910591/12615347/4d11524e-c559-11e5-9c53-f2a7e422343c.jpg)
Facebook changed something and now the background of the message input text area is now white, while the text you type also stays white so it is invisible. You mind fixing that? :P

**Comment by mareksabo** [comment]
It is already opened as #337

**Comment by orangeSkySTUDio** [comment]
Temporary fix: Right click -> launch dev tools -> on the bottom tabs click on search -> search for 4rv3 -> click on it and make sure line 34 from the css above is focused -> MODIFY background-color:rgba(255, 255, 255, .95) TO background-color:rgba(255, 255, 255, .05). Just remove the last 9 and add a 0 instead. Change will not save upon exiting application.

**Comment by Majki** [comment]
@orangeSkySTUDio works

**Comment by beyael** [comment]
Sorry if double posting, but has anyone at any point while doing this "fix" experienced this issue?
![2016-01-27 11_34_13-new notification](https://cloud.githubusercontent.com/assets/16925653/12625915/c24da2ca-c4ea-11e5-9795-8b8b000b527d.png)

**Comment by orangeSkySTUDio** [comment]
Click on X on top ( or just press escape ) and try to modify it again. If not, exit the dev tools ( not messenger ), launch dev tools again and now you have this list already here. You can skip images 1-3 and just replace the 9 now.

**Comment by ajisma** [comment]
I can't save this because this error «Saving files is not enabled in hosted mode. Please inspect using chrome://inspect». Why this happens?

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
