### ISSUE TITLE
Message window is white on dark theme with version 1.4.3 on Linux

### ISSUE THREAD

**Issue by AtomicConglomerate** [Aluxian/Facebook-Messenger-Desktop#341]
See attached picture. 
![screenshot from 2016-01-28 16 07 30](https://cloud.githubusercontent.com/assets/14104403/12658883/b1052282-c5d9-11e5-85ed-32efba917395.png)

Only the background has a problem. The font remains a light font, which makes it really hard to see what is being typed with both dark and mosaic theme.

**Comment by Andriew** [comment]
I have same problem on windows 10.

**Comment by redwing55** [comment]
Just had the same problem on mac os x.  The textbox is white and the text can't be seen in it.  I've reloaded the program with no success.

**Comment by mac251** [comment]
I'm having the same issue with windows vista

**Comment by michalzubkowicz** [comment]
Same problem here, also with mosaic theme

**Comment by enoordam** [comment]
Same for me, dark theme and mosaic, Windows 10.

**Comment by Sypanite** [comment]
Mmm, this issue has been open for a few days now. I hope it gets sorted soon.

In the meantime, there's a temporary fix you can do by modifying the CSS - originally provided by orangeSkySTUDio on issue #337.

- Open the context menu in the Messenger window, select "Launch dev tools"
- Press the drop-down icon next to the gear
- Click the 'Search' tab
- Search for "4rv3"
- Modify "color:rgba(255, 255, 255, .95)" - change ".95" to changed to ".05"
- Close the window

This should fix it **for the current session**. You might get an error - if so, and it hasn't fixed it, try the whole process again.

**Comment by meyersbs** [comment]
I have the same issue (Ubuntu 15.10, 64 Bit) and Synpanite's suggested [fix](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/341#issuecomment-176840126) didn't work.

**Comment by michalzubkowicz** [comment]
Thx @Sypanite , it's working.

**Comment by rick9791** [comment]
Same issue here on Xubuntu 15.10, but @Sypanite's solution fixed the issue, thanks!

**Comment by ClearStaff** [comment]
For mosaic theme (and maybe black too) i added following style to the .css and compiled app from scratch:

```css
._4rv3 {
    background-color: rgba(255,255,255, 0);
}
```

**Comment by iRuisu** [comment]
Dude's working on the fixes for v2 according to his Twitter so we've just to patiently wait.

**Comment by salahuddinasjad** [comment]
@ClearStaff, how did you compiled the app?

**Comment by TPC3D** [comment]
Anybody have updates on this? The CSS fix worked for me, but I'm glad the dev doesn't seem to care, given it's been a month since the problem occurred. One of you mentioned his twitter, can you give a link?

Thanks.

**Comment by Sytten** [comment]
Will be fixed on my fork this weekend

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
