### ISSUE TITLE
Needs fork - abandoned

### ISSUE THREAD

**Issue by rmenessec** [Aluxian/Facebook-Messenger-Desktop#344]
Last commit was six months ago. Developer is still active on GitHub, but not on this project.

I have no experience with node.js - can someone pitch in and start fixing some of the smaller problems?

**Comment by Sytten** [comment]
see my fork some of the problems were fixed, but not all

**Comment by nevercast** [comment]
@Aluxian made a small commit recently. Hopefully development is moving again.

If not, perhaps it should be raised that someone take Contributor access of the project to handle fixes.

**Comment by Sytten** [comment]
The software is being rewritten. Be patient and meanwhile help my fork instead!

**Comment by nevercast** [comment]
Is your fork going to be mainlined? Do the builds currently come from your fork?

**Comment by Sytten** [comment]
Well I had a rough semester, but I should be able to do a release soon. Latest is quite old I noticed, but I had trouble updating the dependencies to NW.JS 0.14.0 and had no time to work on it. All help would be appreciated.

**Comment by nevercast** [comment]
I hear what you're saying, and I'd be happy to help your fork. But unless you're recognized by http://messengerfordesktop.com , your releases will be out of reach from the userbase. Hence why @Aluxian would need to setup automatic builds and provide a contributor to accept pull requests.

**Comment by Sytten** [comment]
no relevant anymore, please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
