### ISSUE TITLE
cannot play video

### ISSUE THREAD

**Issue by mario-cizmarik** [Aluxian/Facebook-Messenger-Desktop#347]
i can open recieved video from contact but can't play

**Comment by Marox44** [comment]
Indeed it would be really convenient to be able to play a videos inside the app. If I receive a video, it shows with a play button but need to go on website to watch it.

**Comment by Alex0826** [comment]
Same here =( Can't play back any video clips or audio messages while using the desktop app... please help

**Comment by Sytten** [comment]
NWJS doesnt support it yet

**Comment by Sytten** [comment]
Will be resolved soon, just need to change the lib.
Meanwhile please check https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
