### ISSUE TITLE
Messanger window not showing 

### ISSUE THREAD

**Issue by maher17** [Aluxian/Facebook-Messenger-Desktop#351]
I have installed Messanger for desktop 2 weeks ago , but Now when i run messanger ,it window don't show

**Comment by paland3** [comment]
I have the same issue. I reinstalled the app, the results is the same: when I open the app, the window is not showing.

**Comment by kaaboaye** [comment]
Kill process and restart its helping

**Comment by paland3** [comment]
Thanks for the answer. I tried to kill the process, I even reinstalled the
app. No success.

**Comment by kaaboaye** [comment]
Show me debug and give info about OS and if Linux GUI and check dependences

**Comment by paland3** [comment]
I am using windows 10, 64 bit.
How can I give you debug information? I can make snapshots about the event.

**Comment by Sytten** [comment]
NWJS doe not support windows 10 yet

**Comment by kaaboaye** [comment]
On my win10 I don't any problems, just sometimes I have to kill process

**Comment by kaaboaye** [comment]
And I don't now how to debug om windows :v

**Comment by Sytten** [comment]
Its not stable, probably the next version of NWJS will fully support it (I hope, its currently in beta last time I checked)... You can use the toolbar and search info from there I guess.

**Comment by paland3** [comment]
it worked fine before on Windows 10.I will try compatibility mode.

**Comment by kaaboaye** [comment]
If you know what is ziemniaczek write on kaaboaye#gmail.com

**Comment by AlxAlindayu** [comment]
i have a same problem about messenger any solution for windows 7 64bit ?

**Comment by kaaboaye** [comment]
May be you have AMD

**Comment by Sytten** [comment]
Windows 7 should be fine, its very well supported by NWJS. Try deleting the settings in Appdata and reinstall. You should also consider my fork if you want a more updated version.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
I suggest you delete the cache in the appdata, always helps.
Open a new issue if you still have that problem.

**Comment by maher17** [comment]
when i had windows 10 i just waited for 2 to 5(max) minutes  to the messanger show . thank so much for this awsome app !!!!
