### ISSUE TITLE
Add KDE Plasma 5 systray icon support

### ISSUE THREAD

**Issue by AlexisCaffa** [Aluxian/Facebook-Messenger-Desktop#352]
The application can not be minimized in the system tray.
Tested on Kubuntu

**Comment by cassiodoroVicinetti** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/296#issuecomment-168556880

**Comment by Sytten** [comment]
Please use https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
