### ISSUE TITLE
Crashes when escape key pressed

### ISSUE THREAD

**Issue by cadecairos** [Aluxian/Facebook-Messenger-Desktop#354]
On Ubuntu 15.10, The application crashes when I press the escape key.

Crash detials from terminal:
```
[12347:0212/113447:ERROR:channel.cc(305)] RawChannel read error (connection broken)
Failed to tell parent about crash.
```

system details
```
$ uname -srmov
Linux 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 GNU/Linux

```

**Comment by Sytten** [comment]
Its not a crash, its just a normal quit for the app (I know the error is strange).
I added a toolbar icon in my fork, so now it just go in background.

**Comment by cadecairos** [comment]
Well, a non-zero exit is technically a crash. Ubuntu will interpret this as a crash as long as it has an anomalous exit status.

I'm using Antergos linux now, and this issue isn't present.

**Comment by Sytten** [comment]
I have the same thing on linux mint, but I changed the behavior of the ESC button so I dont have your behavior (App quiting). I'm not sure, but I'm pretty confident its a NWJS problem...

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
