### ISSUE TITLE
Please add option to esc key close only the overlay.

### ISSUE THREAD

**Issue by jdso** [Aluxian/Facebook-Messenger-Desktop#356]
Esc key closes the window, but if you're in-browser only closes the overlay (e.g. if you're looking at a picture). My suggestion is if you're seeing a picture or watching a video esc key should close the overlay. if no overlay is present, then it should close the window.

**Comment by karansangha** [comment]
Can we make the escape key to close the window optional? I would much rather have it minimize the window or do nothing at all.

**Comment by jdso** [comment]
On 02/17/2016 02:32 AM, Karanvir Singh Sangha wrote:
>
> Can we make the escape key to close the window optional? I would much 
> rather have it minimize the window or do nothing at all.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/356#issuecomment-184982425>.
>

I would like to have the option to have it closing the overlay (1st 
press, if there's an overlay), and then minimizing the window as you 
said. I'm thinking about contributing to the project, gotta take some 
time to get into it !

**Comment by Sytten** [comment]
If you add the option please push to my fork which is much more up to date ;)
I wanted to fix that too, but currently dont have time to do it...

**Comment by Sytten** [comment]
Done
https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by mrrs6** [comment]
Thanks ! I'm cloning the repo and i plan to contribute soon :)

**Comment by Sytten** [comment]
Good, just create some PR if you want to add stuff on my fork.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
