### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by joeffel** [Aluxian/Facebook-Messenger-Desktop#357]
Please create a package for openSUSE Leap 42.1.

**Comment by Sytten** [comment]
check my fork

**Comment by joeffel** [comment]
Link please?

**Comment by Sytten** [comment]
Code: https://github.com/Sytten/Facebook-Messenger-Desktop
Website: https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by joeffel** [comment]
Thanks!

**Comment by Sytten** [comment]
No problem :)
