### ISSUE TITLE
TEXT FIELD

### ISSUE THREAD

**Issue by scramble0** [Aluxian/Facebook-Messenger-Desktop#358]
Using both DARK THEMES  keeps TEXT FIELD with WHITE background and WHITE text.... all white, you can NOT see  what you type

**Comment by CNIAngel** [comment]
I doubt they'll fix it, but a quick fix for it is to Launch Dev Tools and then search for the text field. It's called "div._4rv3". This edit will only work as long as you leave the application open. Like I said, quick fix.

**Comment by scramble0** [comment]
I knew I could edit the code but the question was WHERE. Thanks mate :)

It's extremely simple dunno how they screwed up that. Hope dev's see this and apply a fix.

Thanks again Grant.

**Comment by reklaimer** [comment]
So what exactly should we edit here to make the dark theme appear as it should in the text entry box? I've found the entry in the dev tools, but I'm not sure what to do next. I use this every day on my PC and its super irritating that I can't use the dark theme! Would love to get it to work, thanks!

**Comment by CNIAngel** [comment]
If you're still using this version of the Messenger Desktop Application, if you found _4rv3 then you'll want to edit this to make the text appear correctly. 

[http://i.imgur.com/4KPEOBI.png](url)

At this point I've started using a fork of this application that has fixed this issue and allows you to make custom themes. In case anyone is interested in that one too.

[https://sytten.github.io/Facebook-Messenger-Desktop/](url)
