### ISSUE TITLE
Adding a option to block "readed" post request

### ISSUE THREAD

**Issue by GAMELASTER** [Aluxian/Facebook-Messenger-Desktop#359]
Just add a switch to enable or disable a readed post request
https://www.messenger.com/ajax/mercury/change_read_status.php

**Comment by pyrforos** [comment]
can't  see it....

**Comment by GAMELASTER** [comment]
?

**Comment by pyrforos** [comment]
link  doesn't open..

**Comment by GAMELASTER** [comment]
@pyrforos  because that link is pointing to a Facebook Messenger script, what marks a someone messages as seen by me, so when execution of this script will be blocked, you can see messages without the opposite friend dont see a "seen" :-) . And you saw a white page because this script requires a some POST arguments :-)

**Comment by Sytten** [comment]
Why would you want someone to not see that you have seen their message. Strange...

**Comment by GAMELASTER** [comment]
@Sytten because I hate that when I seen the message but I cant reply, and the other side thinks im ignoring and blahblahblah... I hate it!

**Comment by Sytten** [comment]
Yes I see it would be nice, I currently have other priorities.
Maybe in the MFD 2, what do you think @Aluxian

**Comment by GAMELASTER** [comment]
@Sytten actually it is a easy task to do, in that time when I sent it I don't  have a lot of skills with Electron, now I could do it and send pull request. When I will got time I will do that :-) . It's just block of one HTTP request

**Comment by Sytten** [comment]
@GAMELASTER the software is actually based on NW.JS (0.14.5 for the V1.5.X branch)
Yes I guess that must be easy, me only concern is that it would probably mess up with the notification icon and title bar. Tell me when you got time so we can plan this together.

**Comment by Sytten** [comment]
This is probably what you want https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/462

**Comment by GAMELASTER** [comment]
@Sytten ah, yeah, NW.JS, I wrong remembered. When the pull request is made I can close this! :-) Thanks
