### ISSUE TITLE
[REQ] Chrome desktop notifications (Windows) 

### ISSUE THREAD

**Issue by emerts** [Aluxian/Facebook-Messenger-Desktop#36]
Is there possibility in NW.js or other way to change desktop notifications on Windows to Chrome style? (like gmail or even messenger.com as chrome app)

Bubble ones still looks like in WinXP, little ugly in Win8.1 or Win10.

**Comment by Aluxian** [comment]
@emerts I know, tooltips aren't proper notifications. I'm working on this.
