### ISSUE TITLE
Customizable display style of side bar

### ISSUE THREAD

**Issue by agajek** [Aluxian/Facebook-Messenger-Desktop#360]
Now sidebar by default shows last conversations with last message for each of them. Of course there is possibility to resize window and then sidebar only shows avatars of friends we chat lastly with. For me the nice option will be to select which of those two options I want to use no matter of window size, or add ability to resize sidebar.

**Comment by Sytten** [comment]
This is a wont fix for now, to complicated to implement. If you want to identify the necessary information in the html needed to rearrange it in the proper order, I would be glad to help you write the javascript needed to make the swap.
