### ISSUE TITLE
Won't download on Windows 10

### ISSUE THREAD

**Issue by maddie102899** [Aluxian/Facebook-Messenger-Desktop#361]
It won't download and keeps bringing up an error message. I've tried running it as an administrator, but it still comes up with the error message. It's was working earlier, but stopped so I re-downloaded it. That's when the error message came up when installing.

**Comment by Sytten** [comment]
NWJS inst compatible with windows 10 right now

**Comment by Sytten** [comment]
Without more information I cant help you, closing
