### ISSUE TITLE
Doesn't play sounds in Safari nor in the App (Mac OS X Yosemite)

### ISSUE THREAD

**Issue by InDoubt** [Aluxian/Facebook-Messenger-Desktop#362]
Messenger doesn't play sound clips in the Mac.
Neither Safari in its web form nor in Messenger desktop stand alone app.
The bubble shows in both, but when clicked to play the spinning circle goes forever.

Please advice,

Thank you!

**Comment by Sytten** [comment]
Normal behavior, NWJS doesnt support sound nor video right now

**Comment by Sytten** [comment]
Will be fixed in a near release for the app, ask apple for safari.
