### ISSUE TITLE
i get error when install in kubuntu 15.10

### ISSUE THREAD

**Issue by uebmaster** [Aluxian/Facebook-Messenger-Desktop#364]
Seleccionando el paquete messengerfordesktop previamente no seleccionado.
(Leyendo la base de datos ... 201488 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../Messenger_linux64.deb ...
Desempaquetando messengerfordesktop (1.4.3) ...
Configurando messengerfordesktop (1.4.3) ...
/var/lib/dpkg/info/messengerfordesktop.postinst: línea 7: desktop-file-install: orden no encontrada
dpkg: error al procesar el paquete messengerfordesktop (--install):
 el subproceso instalado el script post-installation devolvió el código de salida de error 127
Procesando disparadores para hicolor-icon-theme (0.15-0ubuntu1) ...

**Comment by Sytten** [comment]
Try my release
https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by uebmaster** [comment]
El Monday 29 February 2016 08:24:38 �mile Fugulin escribi�:
> Try my release
> https://sytten.github.io/Facebook-Messenger-Desktop/
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/
364#issuecommen
> t-190276170

Don't works, tell me this

Configurando messengerfordesktop (1.4.7) ...
/var/lib/dpkg/info/messengerfordesktop.postinst: l�nea 7: desktop-file-
install: orden no encontrada
dpkg: error al procesar el paquete messengerfordesktop (--install):
 el subproceso instalado el script post-installation devolvi� el c�digo de 
salida de error 127
Procesando disparadores para hicolor-icon-theme (0.15-0ubuntu1) ...

I am using kubuntu 15.04 and trying to install with gdebi

**Comment by Sytten** [comment]
Sorry I cant read that language,but try to delete all conf files in opt and then reinstall. Its strange because I provide a valid desktop file...

**Comment by uebmaster** [comment]
El Tuesday 01 March 2016 15:31:31 �mile Fugulin escribi�:
> Sorry I cant read that language,but try to delete all conf files in opt and
> then reinstall. Its strange because I provide a valid desktop file...
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/
364#issuecommen
> t-190965238
 I verified and i haven't conf files in the /opt folder

I don't know what is the problem, in ubuntu the program runs fine, is in 
kubuntu the problem.

**Comment by granthgh** [comment]
You need to install desktop-file-utils before installing messenger for desktop on kubuntu.

From command prompt type: sudo apt-get install desktop-file-utils

Once that is completed messengerfordesktop should install.

**Comment by Sytten** [comment]
Thanks for the tip, I will add it to a tip list I'm trying to come up with ;)

**Comment by Sytten** [comment]
I think the issue is resolved
