### ISSUE TITLE
Windows Compile not working

### ISSUE THREAD

**Issue by tenzanoni** [Aluxian/Facebook-Messenger-Desktop#366]
I tried to create installer using both gulp and NSIS but none of them work.
Messenger just keep running 3 task at background. Nothing show on screen or icon taskbar. Anyone knows how to fix this?
screenshot: http://prntscr.com/a7mi29

**Comment by rrsturua** [comment]
i have too the problem :(

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/453
If you still have problems feel free to open a new issue
