### ISSUE TITLE
Support OAuth rather than asking for facebook username and password

### ISSUE THREAD

**Issue by vboctor** [Aluxian/Facebook-Messenger-Desktop#367]
Why is the app using basic auth rather than OAuth?

**Comment by auscompgeek** [comment]
Messenger.com doesn't use OAuth.

**Comment by Sytten** [comment]
Add this is just a wrapper around the website

**Comment by Ugion** [comment]
This is just a webwrapper, the developer doesn't control the messenger.com website, Facebook itself does.

**Comment by Sytten** [comment]
Not relevant.
