### ISSUE TITLE
Theming isn't working properly

### ISSUE THREAD

**Issue by Unc3nZureD** [Aluxian/Facebook-Messenger-Desktop#368]
When applying a custom theme (non-white), the chat still appears as white, which is very ugly.

For example:
http://i.imgur.com/NP4EiUJ.png

Appears on:
- Latest version of Messenger
- Updated Windows 10 x64
- Both Mosaic & Dark versions

**Comment by Sytten** [comment]
https://github.com/Sytten/Facebook-Messenger-Desktop/issues/17

**Comment by Unc3nZureD** [comment]
Ah, sorry, didn't see that one :) Exactly the same. Thanks.

**Comment by Sytten** [comment]
I will apply the fix this weekend and build it again, stay tuned

**Comment by Sytten** [comment]
Release out
https://sytten.github.io/Facebook-Messenger-Desktop/

**Comment by jmessi** [comment]
@Sytten is that release gonna overwrite the current one installed? it has a warning saying that is a fork of the original release

**Comment by Unc3nZureD** [comment]
I've already installed that one and perfectly works :) Thanks @Sytten

**Comment by jmessi** [comment]
@Unc3nZureD @Sytten same here, looks perfect :3

**Comment by Sytten** [comment]
Yes I wrote the warning so there would be no confusion. You will receive a notification when I release my updates instead and I think I wrote my name as developer (not sure).
I'm happy to see that its working great :)

**Comment by jmessi** [comment]
Hey again! I noticed there seems to be another issue, not necessarily related with the theming. When changing the chat colors, only a few things change, but the bubbles remain the usual blue color. Here's a screenshot in attach

![screenshot 2016-03-06 21 31 47](https://cloud.githubusercontent.com/assets/17604189/13557346/9739bedc-e3e6-11e5-9b34-7978c687857f.png)

**Comment by Sytten** [comment]
Will take a look for the next release when I have some time...

**Comment by auscompgeek** [comment]
@jmessi Fixed in f2d795dc476d40fe811396bdd30e136a1539bce6 (see #369).

**Comment by Sytten** [comment]
Its fixed in my fork too ;)

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/453
