### ISSUE TITLE
Useless menu bar on Ubuntu

### ISSUE THREAD

**Issue by Dovaa** [Aluxian/Facebook-Messenger-Desktop#37]
![wut](http://i.imgur.com/gkCRtPr.png)
It's pretty useless having the buttons...

I'm on Ubuntu 14.04.2 x64

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/54b2b01a5626666228fdae7ef92b893849260cf7
