### ISSUE TITLE
Is there a way to mute the desktop app?

### ISSUE THREAD

**Issue by mrmayfield** [Aluxian/Facebook-Messenger-Desktop#370]
Can't seem to find a way to mute the sound that comes in on a new message. Any ideas? Is it in the UI and I just can't find it or does it not exist?

**Comment by auscompgeek** [comment]
Messenger.com gear menu -> Settings -> Sounds?

**Comment by mrmayfield** [comment]
Somehow couldn't find the gear last night. Thanks!
