### ISSUE TITLE
Not able to Uninstall the program

### ISSUE THREAD

**Issue by champnaman** [Aluxian/Facebook-Messenger-Desktop#371]
I want to remove this program but it is not listed in the Control Panel.

**Comment by iRuisu** [comment]
You can't have tried too hard looking for the uninstaller.. Simply searching for Messenger within the start menu will link you to the uninstaller.

**Comment by Sytten** [comment]
This should be resolved now. Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/453
