### ISSUE TITLE
Phantom tray icon

### ISSUE THREAD

**Issue by beppe9000** [Aluxian/Facebook-Messenger-Desktop#376]
I get this phenomenon randomly with both your web wrappers. Icon disappears but retains its functionality. I'm on Windows 10.

![2016-03-09_12-06-32](https://cloud.githubusercontent.com/assets/6625123/13906457/95c0d4d2-eed6-11e5-9af9-0e042973d8c6.png)

**Comment by Sytten** [comment]
NW.js still have some problems with windows 10. Even on my fork I have those problems...

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Try it with the latest beta. Feel free to open an issue again if its still happening.
