### ISSUE TITLE
image display fail on Ubuntu 15.10 64bit

### ISSUE THREAD

**Issue by yojo3000** [Aluxian/Facebook-Messenger-Desktop#377]
all images are not able to display normally on Ubuntu 15.10

**Comment by hazeem1991** [comment]
same here not cache problem

**Comment by hazeem1991** [comment]
![screenshot from 2016-03-28 11-21-06](https://cloud.githubusercontent.com/assets/18112493/14074108/34fbdc44-f4d7-11e5-9813-1616a93e05e3.png)
this is a screen shot for the problem

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
You can try to delete the cache (under .config in the home folder). Please be sure that you have the right permissions on the cache.
If you still have the problem feel free to open a new issue
