### ISSUE TITLE
Some messages showing blank content

### ISSUE THREAD

**Issue by grkstyla** [Aluxian/Facebook-Messenger-Desktop#378]
Hi Guys,

Windows 10 all updates,

All messages received that contain anything other than text are blank, they show senders DP sent date and time, but nothing else (see screenshot)

Using latest version, tried reinstalling and deleting appdata.

Used to work perfectly so im thinking maybe i did something wrong?
![0dbe8fd82e52ff9beb57ac137534e892](https://cloud.githubusercontent.com/assets/18106219/14068655/f1ff5a34-f4d5-11e5-9877-9a666956f7b7.png)

**Comment by Sytten** [comment]
Please see: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Feel free to open a new issue if the problems appears with the beta
