### ISSUE TITLE
Faint grey text on white background for new messages (OS X)

### ISSUE THREAD

**Issue by joshuanasiatka** [Aluxian/Facebook-Messenger-Desktop#379]
When writing messages the font color is a faint grey, close to #fafafa or #eee. It is practically invisible with the lack of contrast. This happens with dark mode and mosaic.

**Comment by nomaderr** [comment]
Same thing on Windows and Debian

**Comment by pmarcelll** [comment]
There's an actively maintained fork with a fixed font color, see: #296.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
