### ISSUE TITLE
Send audios and emojis

### ISSUE THREAD

**Issue by candestep** [Aluxian/Facebook-Messenger-Desktop#38]
I think it would be great to send audio notes by this application. Also, to have the emoji menu from Fb Messenger app (here's a list of those emojis that I mean: http://articulos.softonic.com/los-emoticonos-de-facebook ) would be truly nice too.

I'm using Snow Leopard and I'm really thankful with the support to this os. This app? I'm loving it! :+1:

**Comment by Aluxian** [comment]
I will think about it. In the meantime, on my Yosemite 10.10.3 I can press CTRL+CMD+SPACE to open a window with emoji's. I'm not sure you have this on Snow Leopard, but you can try.

**Comment by candestep** [comment]
I tried that but it looks like if it doesn't work on Snow Leopard. Thanks for answer to my suggestion, I really appreciate it. Also, I'll be aware of any news from this app. Seriously, it has made my "online life" easier. :laughing:

**Comment by Aluxian** [comment]
I can't add audio notes. Emoji support, most probably, will be added eventually on messenger.com. Yosemite users can use the keyboard shortcut.

**Comment by jackwilsdon** [comment]
I'm having some issues with sending emoji on OS X El Capitan. I'm using version 1.4.7.

I can open the OS X emoji picker fine, but clicking on an emoji or hitting enter on one makes it appear for a split second in the field before vanishing.

I don't have the same problem with messenger.com
