### ISSUE TITLE
No action on click on notification || UBUNTU 15.10

### ISSUE THREAD

**Issue by aleksandrmaksimoviclt** [Aluxian/Facebook-Messenger-Desktop#380]
**ISSUE:**
When i receive message, the notification is displayed in top right corner of my screen with sender photo and message. Clicking on that notification **doesn't** open chat with sender. Instead, notification is being blurred on mouse hover.

**What i have done:**
I have enabled the notification in settings -> "Turn on desktop notifications".

**Comment by felipemfp** [comment]
On Ubuntu, notification are like that. At least, Spotify notifications is being blurred on mouse hover.

**Comment by aleksandrmaksimoviclt** [comment]
@felipemfp This is rediculous.

**Comment by george-viaud** [comment]
Notifications should have click action (like bring focus to that app for example).  Configurable action would be even better.
