### ISSUE TITLE
Audio/Voice Message Not Playing

### ISSUE THREAD

**Issue by xtian23anthony** [Aluxian/Facebook-Messenger-Desktop#381]
Audio and/or Voice Message is not playing. When I try to play the audio or voice message that was sent to me, or that I sent to others, it's not playing. It's only showing that it's loading, but it doesn't play.

OS: Windows 10 Pro

![asdasd](https://cloud.githubusercontent.com/assets/18255231/14238729/c277ef88-fa66-11e5-851e-f13f27b10117.PNG)

**Comment by Sytten** [comment]
Normal behavior, NWJS doesnt support it

**Comment by Sytten** [comment]
This is known and will be resolved in the next beta.
Meanwhile please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
