### ISSUE TITLE
Using Messenger for Desktop after account deactivation 

### ISSUE THREAD

**Issue by nodzy** [Aluxian/Facebook-Messenger-Desktop#382]
I deactivated my Facebook account. I still can use Messenger on my phone, but unfortunately it doesn't work on Desktop version. 
When I try to log in, it doesn't give me any error, just refreshes login page.

**Comment by Sheefou** [comment]
The programs essentially is a web browser so you are logging in to a web browser check http://messenger.com(the website the program runs off of) to see if you can actually use the default facebook messenger in the browser and ensure its not a problem with the program itself

**Comment by zaratustra21** [comment]
nodzy i  have the same issue. I don't want to activate facebook again so why is this happening? Did you make it work?

**Comment by nodzy** [comment]
No, unfortunately not - it doesn't work for me.

2016-05-03 17:36 GMT+02:00 zaratustra21 <notifications@github.com>:

**Comment by nevercast** [comment]
I've attempted this also. Even if you create a "Messenger only" account with your phone number, you cannot login to the messenger.com/ service with it.

It requires you've a Facebook account, Messenger only accounts are not available outside of Mobile.

**Comment by Sytten** [comment]
I think the issue as been answered
