### ISSUE TITLE
CPU Core Wrecked

### ISSUE THREAD

**Issue by DavidLKing** [Aluxian/Facebook-Messenger-Desktop#389]
At risk of this being a duplicate of this [post](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/293), it appears Facebook-Messenger-Desktop has processes that are monopolizing a single core each on my machine. 

I'm running Ubuntu 16.04 and 14.04 on two different machines and am getting the same behavior.
Both /opt/MessengerForDesktop/Messenger and /opt/self/exe are both grabbing 100% of one core each. The full process names from `ps -ax` are as follows:
`972 ?        S      0:00 /opt/MessengerForDesktop/Messenger --type=zygote --no-sandbox --enable-crash-reporter`
`991 ?        Sl     0:12 /proc/self/exe --type=gpu-process --channel=967.0.2027141055 --no-sandbox --enable-crash-reporter --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,24,27,40,48 --disable-accelerated-video-decode --gpu-vendor-id=0x10de --gpu-device-id=0x1401 --gpu-driver-vendor=NVIDIA --gpu-driver-version=352.79 --enable-crash-reporter`

When I close the program, this behavior stops, and restarts when I restart the application. Thoughts and/or fixes would be greatly appreciated.

**Comment by DavidLKing** [comment]
Quite side note: I just noticed this does not occur when the application is minimized. Hope that helps!

**Comment by barbushin** [comment]
Same problem in Win 10x64. Using 1.4.3 version. If Messenger is not minimized, it's always using 10-15% of my Intel i7 CPU. May be it's because of some GIF stickers are played in background? Anyway, there is screenshot of Dev Tools Profile tab.

![image](https://cloud.githubusercontent.com/assets/683352/15121257/42a0b70c-164c-11e6-95cd-d857953e20c6.png)

**Comment by Sytten** [comment]
Should be resolved in the next release
