### ISSUE TITLE
"Type a message" area bg color not changing in Mosaic and Dark theme.

### ISSUE THREAD

**Issue by raniesantos** [Aluxian/Facebook-Messenger-Desktop#393]
The "Type a message" area (or div._4rv3) stays white when switching to the other two themes.
Using version 1.4.3 on Windows 7.

**Comment by wdanilo** [comment]
+1 The same happens on linux. Usign dark theme I cannot see the letters when typing - both letters and backgroudn are white.

**Comment by kchrysanthis** [comment]
same problem pls solution!!

**Comment by jackmanganiello** [comment]
Same problem here as well. Windows 10 64bit

**Comment by MaBeuLux88** [comment]
Same problem on Debian with 64 bits deb file. I guess it's just an error in the CSS files.

**Comment by Shadowfire2303** [comment]
Same issue here. I was able to change the values of the background color of the box, however the effect is only temporary.

**Comment by siimr** [comment]
I fixed it, but only for windows: 
https://drive.google.com/file/d/0B4QRd95ZH77ccFZMRnpPSktWXzg/view?usp=sharing

**Comment by wdanilo** [comment]
@siimr Could you make a normal pull request and fix it on other platforms too? It should not be complicated if it already works on Windows! :)

**Comment by Sytten** [comment]
Problem solved in my fork

**Comment by MaBeuLux88** [comment]
Thanks @Sytten. Moved to your version until the pending PRs are integrated here.

**Comment by Sytten** [comment]
They wont be ;) As said many time the program is being rewritten by the dev, but its painfully slow...

**Comment by wdanilo** [comment]
Oh so the application is being rewritten slowly and bugs with obvious fixes are not getting merged? Great! Keep it this way. Ok, I'm out of this.

**Comment by Sytten** [comment]
Well thats why you should come over to my fork :p

**Comment by Sytten** [comment]
This issue is resolved in the upcoming official release.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
