### ISSUE TITLE
Add a RPM Package

### ISSUE THREAD

**Issue by vikas-0** [Aluxian/Facebook-Messenger-Desktop#394]

**Comment by thomn** [comment]
It's not documented, but `gulp pack linux{32|64}:rpm` will generate a RPM package.

**Comment by Sytten** [comment]
Check my fork

**Comment by Sytten** [comment]
The new official release will have RPM builds, thanks for your patience

**Comment by mairin** [comment]
it's June, when is the next release with RPM?

**Comment by Sytten** [comment]
Yes and I have school, you can use my fork meanwhile. I will try to release a version next sunday if I get approval by my collaborator.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
