### ISSUE TITLE
Multiple Instances of messenger are opened in Windows 8

### ISSUE THREAD

**Issue by nikolodien** [Aluxian/Facebook-Messenger-Desktop#395]
When you close messenger and open again, a new instance is created for it as can be seen in the screenshot below.

![multiplemessenger](https://cloud.githubusercontent.com/assets/1100734/14921223/b25133be-0df6-11e6-955b-826b72c5e8fe.png)

**Comment by Sytten** [comment]
Handled in my fork

**Comment by Sytten** [comment]
The next official release will resolve it.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
