### ISSUE TITLE
Package for Ubuntu Touch

### ISSUE THREAD

**Issue by fihufil** [Aluxian/Facebook-Messenger-Desktop#397]
Ubuntu Touch is a young platform, which is basically Ubuntu for smartphones.
The platform support creating applications using HTML5 https://developer.ubuntu.com/en/phone/
And We as a community will appreciate your application to be available.
Although Ubuntu Touch is using Linux Kernel its NOT Android.

**Comment by Sytten** [comment]
Hum, maybe thats possible, but it will need a lot of work. We should probably wait for the need version of the program based on Electron before doing that move...

**Comment by Sytten** [comment]
EDIT: That wont be done
