### ISSUE TITLE
Can't see typing text when i change the Theme.

### ISSUE THREAD

**Issue by Miionu** [Aluxian/Facebook-Messenger-Desktop#398]
See below images from my computer : 

![darktheme](https://cloud.githubusercontent.com/assets/17688475/15098105/d64cdf7c-1533-11e6-9da8-4a89115a3089.PNG) DARK THEME

![defaulttheme](https://cloud.githubusercontent.com/assets/17688475/15098106/d64d5e34-1533-11e6-93e6-0038919fc38f.PNG) DEFAULT THEME

I don't really know how to change that definitively (i'm not a pro in programming ^^)
But i think it could be easily changed in the next patch ;)

Bye !

**Comment by siimr** [comment]
I just made my own fix for this. Dark theme and Mosaic theme inputs have been fixed in this zip. Just unpack and open. 
https://drive.google.com/file/d/0B4QRd95ZH77ccFZMRnpPSktWXzg/view?usp=sharing

**Comment by Miionu** [comment]
Oh perfect ! Thank you very much :) Great work

**Comment by Sytten** [comment]
The next official release will fix this.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
