### ISSUE TITLE
[Windows] Session still logged in when uninstalling then reinstalling

### ISSUE THREAD

**Issue by jacksparser** [Aluxian/Facebook-Messenger-Desktop#399]
OS: Windows 10 Build 10586.218
Procedure:
1. Login to Messenger for Desktop
2. Exit the app
3. Uninstall
4. Reinstall
5. Run the app

Expected Result:
1. App is opened in login screen

Actual Result:
1. Previous account is still logged in

**Comment by Sytten** [comment]
Its a known bug, will try to fix it on my fork

**Comment by Sytten** [comment]
Should be fixed by https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/e0bc24621633bdb7fe2349d6f96211f04dd0d457
