### ISSUE TITLE
Don't exit when closing the window on OS X

### ISSUE THREAD

**Issue by MSch** [Aluxian/Facebook-Messenger-Desktop#4]
Many "chat apps" (e.g. Slack, Campfire clients, Adium, etc) do not exit when their window is closed, instead closing the window (either via the close button in the upper left corder or Command-W) just hides the window, activating the application shows the window again.

**Comment by tomvest** [comment]
oh please please please fix that, it's driving me crazy
I always accidentaly quit it just because of muscle memory from other apps
otherwise great wrapper, thank you!

**Comment by denpatin** [comment]
:+1: 
Just downloaded the app and faced the problem that it got unloaded from memory when I clicked the X-button. Not so typical behaviour for chat apps, yes.

**Comment by Aluxian** [comment]
I admit that this also happens to me pretty often, hehe. I'll see what I can do.

**Comment by denpatin** [comment]
@Aluxian That would be really great if you do it.

And a special thanks to you for this nice app! :+1:

**Comment by Aluxian** [comment]
I did it, guys! If you want to get this now you'll have to build it yourself. I want to fix more stuff until I release another version.
