### ISSUE TITLE
Update checker

### ISSUE THREAD

**Issue by kioltk** [Aluxian/Facebook-Messenger-Desktop#40]
Maybe you can add the "Check for updates" button to a menu?
Or autoupdating would be awesome!
Thanks

**Comment by Aluxian** [comment]
The app checks for updates every time you open it. If there's a new version available, you'll be prompted to download it.

**Comment by kioltk** [comment]
Well, I didn't see the update in 1.10.

**Comment by Aluxian** [comment]
The auto-update feature was added in `1.2.0`. Please download the latest release, and you'll get updates from now on.

**Comment by kioltk** [comment]
Thanks.
