### ISSUE TITLE
Windows 10 Task kill

### ISSUE THREAD

**Issue by kdrewgonzales** [Aluxian/Facebook-Messenger-Desktop#401]
When I close messenger for desktop on windows ten, the task is still running in the task manager. For me to re-open Messenger, I have to kill the task from my task manager, then it'll re open. But If I close it, then try to open it again from my start menu, Messenger won't open.

**Comment by nevercast** [comment]
Messenger should minimize to the tray. Can you check that works.

**Comment by kdrewgonzales** [comment]
I'm on windows 10, version 1511?. Buildl 10586.318 and it doesn't minimize.

**Comment by nevercast** [comment]
I cannot replicate this with the current development version, so I can predict that it'll be fixed in the next release. I'll keep this issue open and check back with you after the next release. Thanks for the report.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
