### ISSUE TITLE
Stuck on loading screen?

### ISSUE THREAD

**Issue by iwakoscott** [Aluxian/Facebook-Messenger-Desktop#404]
I download the Linux-64 version off the main website however after running the installation and I run messenger application it is stuck on the loading screen:
![facebook](https://cloud.githubusercontent.com/assets/13685868/15197827/720558a8-1788-11e6-8324-e5566fbfe8ff.png)

I have tried killing it then rebooting and starting the app again. I also tried removing it and reinstalling it and I get the same issues.

**Comment by Sytten** [comment]
Whats your OS? Can you get me the debug log? 
I will try to fix it on my fork...

**Comment by iwakoscott** [comment]
I am not too familiar with how to send you the debug log for my problem. Could you please guide me in the right direction?

**Comment by Sytten** [comment]
You can right click to launch dev tools and give me the ouput.
Another option would be to launch the program from command line and check the ouput.

**Comment by iwakoscott** [comment]
![error](https://cloud.githubusercontent.com/assets/13685868/15261663/a60e6e42-1912-11e6-814c-1ac40e41fd18.png)

**Comment by Sytten** [comment]
Than you, we will look at that!

**Comment by nevercast** [comment]
Hi @iwakoscott 
Can you confirm this is still an issue, I'd like to eliminate that it was a temporary server issue. 
Thanks.

**Comment by iwakoscott** [comment]
@nevercast I can confirm that this is still an issue! I am still stuck on an infinite loading screen and yes that is a funny coincidence.

**Comment by nevercast** [comment]
I wonder if the SSL error is of significance. Can you check the Network log in the Dev Tools debugger?
Also are you able to access https://www.messenger.com/ ?

**Comment by Sytten** [comment]
This is not the only person who reported problem with ssl https://github.com/Sytten/Facebook-Messenger-Desktop/issues/23

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458 and https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/453
