### ISSUE TITLE
Request: [A default home screen]

### ISSUE THREAD

**Issue by sarthak-0415** [Aluxian/Facebook-Messenger-Desktop#405]
Right now on pressing escape it closes the application which is a little problematic.

There can be a feature which loads a default home screen on pressing escape button and closes the window using the usual close button

**Comment by Sytten** [comment]
Escape actually closes the window, not the application.

**Comment by sarthak-0415** [comment]
In linux it actually closes the application

**Comment by Sytten** [comment]
Yea, fixed in my fork

**Comment by nevercast** [comment]
Hello @sarthak-0415 

@Sytten and I have recently taken over this project. We've a new release planned for this week. Your issue with regarding escape closing the application will be bundled in that fix.
