### ISSUE TITLE
[Call for mighty developers] Looking for Maintainers

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#407]
Hello, everyone.

I know I've been inactive for a very very long time, and I'm deeply sorry. Knowing I wouldn't have the time to maintain the app appropriately, I should've let someone else maintain the repo. I regret being fooled by time, periclitating the future of MFD this way.

Now, knowing that in the following 2 months I won't have enough time for MFD again, I realise the best thing to do would be to let someone else maintain the repository and the app itself.

Therefore, I'd like to bring to everyone's attention that I'm looking for a maintainer (or more). We'll be in direct contact and I'll help as much as I can.

Impressed by his dedication and activity, I nominate @Sytten. However, if anyone else is willing to help this way, please comment below. What you'd have to do as maintainer(s):

- fix critical bugs
- manage the repository, along with issues and PRs
- release updates to the existing userbase
- keep in touch with me

Therefore, I won't ask for much of your time (e.g. to work on new features, unless you want to). All I ask is to help the app move forward. Active contributors will become partners and friends of mine :), besides being credited on the website and (possibly) in the app.

P.S. In the future, I still intend to update MFD to Electron and release MFD 2.

**Comment by Aluxian** [comment]
Nominees:
- [ ] Émile Fugulin @Sytten
- [ ] Josh Lloyd @nevercast

**Comment by nevercast** [comment]
I primarily nominate @Sytten as he has already put in a lot of effort in maintaining this project in his own fork and seems quite active on Gitter.

However secondly of course, I'd be more than happy to maintain MFD. Preferably with @Sytten unless for some reason he wouldn't want to maintain this project.

Thanks for all your hard work, @Aluxian

**Comment by cassiodoroVicinetti** [comment]
I nominate @Sytten too.

**Comment by Sytten** [comment]
Thanks guys! 
I would more than happy to maintain this application with @nevercast. I know I cant do it alone anyway (being a full-time student myself).
Al lot of new fixes are ready to be released, and I had planned to work on bug fix today.

@cassiodoroVicinetti your help will always be appreciated!

**Comment by Aluxian** [comment]
@Sytten

Regarding Franz, I think we're at an advantage with the app name and the domain (we're more "discoverable"). I personally don't like the idea of having an all-in-one app, so MFD and Whatsie will target those users who, like me, prefer separate apps (but not only those).

See the discussion on Gitter regarding MFD 2.

**Comment by MarcinWieczorek** [comment]
I'm happy to see the project is alive again!
I'm waiting for new versions for my messengerfordesktop-git ArchLinux package

**Comment by nevercast** [comment]
@MarcinWieczorek We are currently moving the project to an updated version of nwjs. But after this is done, we should have working Linux builds for Deb at least, from that point I'd be more than happy to work with you ensuring it works on Arch.

**Comment by MarcinWieczorek** [comment]
You can count on me.
marcin@marcin.co is my email :)

**Comment by nevercast** [comment]
@Aluxian I'll let you decide when there is enough maintainers, but close when you feel we're at that stage :)

**Comment by Aluxian** [comment]
I think you two are enough for now.

@MarcinWieczorek If you want to help (we'd really appreciate it!) just chat to us on Gitter and see what issues you can work on or whatever you can do to help MFD.

**Comment by Sytten** [comment]
I re

**Comment by MarcinWieczorek** [comment]
But why?

**Comment by cassiodoroVicinetti** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
