### ISSUE TITLE
Taskbar placement in Xfce

### ISSUE THREAD

**Issue by cryoff** [Aluxian/Facebook-Messenger-Desktop#410]
I have the following issue. The entry for Messenger moves in the taskbar panel of Xfce whenever the new message arrives. It is quite weird behavior which seemingly has something to do with notifications but I could not find how to change that.
The entity in the taskbar constantly "jumps" from the first position to its real position.

**Comment by Sytten** [comment]
It is quite possible that its an issue with your taskbar system. The implementation of NW.JS (GTK) isnt always working great with different systems. Will need further investigation.

**Comment by cryoff** [comment]
Can I provide any valuable information for further investigation?

**Comment by Sytten** [comment]
@nevercast Have any idea?

**Comment by nevercast** [comment]
Could be related to the linux icon blinking bug. Perhaps we should fix that and see if this one is resolved in the process

**Comment by Sytten** [comment]
Maybe...

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
If its not working still, then please open a new issue :)
