### ISSUE TITLE
Context Menu shows up in incorrect position

### ISSUE THREAD

**Issue by nevercast** [Aluxian/Facebook-Messenger-Desktop#412]
On Windows, the context menu shows up in the wrong place. 
Perhaps incorrect parent window context?

**Comment by nevercast** [comment]
When running in Mixed Context mode. This is not an issue. Will investigate further.

**Comment by nevercast** [comment]
This was meant to be fixed by https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/748f8dfeafdf5d8fb1c44a482fc0e37c20e79ebd however it seems still be an issue on OSX https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/414#issuecomment-219719833

**Comment by Sytten** [comment]
Fixed by simply deleting it for now...
