### ISSUE TITLE
Bug in the dark theme bubble

### ISSUE THREAD

**Issue by 19darion91** [Aluxian/Facebook-Messenger-Desktop#417]
So when I put the Dark theme, the message bubble stays white... with white text as I type so I can't see what I'm typing.
This is on Ubuntu Mate 16.04
![untitled](https://cloud.githubusercontent.com/assets/7683375/15319692/10460c7a-1c24-11e6-8c06-7ac0a4d5ca84.png)
 (It says Hello)

**Comment by Eons-coding** [comment]
Same on Linux Mint DE, it's quite problematic since the white theme litteraly blind me ^^

**Comment by Sytten** [comment]
This will be fixed in the new release coming very shortly!
As you probably seen, me and @nevercast are now official maintainers.

**Comment by legendaris** [comment]
I have the same issue in Windows 10

**Comment by 19darion91** [comment]
Sytten, I just installed your fork and it works perfectly. The thing that can be improved is the dark theme to use the default chat bubble settings, that will give it the ability to change chat color. Basically the same option that this team has https://userstyles.org/styles/122582/dark-facebook-messenger-fully-black (I've been using it for a while in windows 10 as a chrome desktop app with this theme and the theme works properly with messenger's options for changing chat colors)

**Comment by Sytten** [comment]
I will take a look at it. Thanks. Keep an eye on this Repo, we will soon release a new official release with a LOT of bug fixing!

**Comment by Sytten** [comment]
See https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
