### ISSUE TITLE
Messenger title is nwjs on OSX

### ISSUE THREAD

**Issue by nevercast** [Aluxian/Facebook-Messenger-Desktop#418]
![](https://cloud.githubusercontent.com/assets/1418870/15323963/14cc6b76-1c4d-11e6-9bd8-16c3956b7247.png)

**Comment by Sytten** [comment]
Fix https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/414/commits/999d286893468933ef78b70f93d248fb068527e4
