### ISSUE TITLE
Make "Close with ESC" default to False

### ISSUE THREAD

**Issue by nevercast** [Aluxian/Facebook-Messenger-Desktop#419]
Per the title.

Those that prefer the feature are a minority. https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/414#issuecomment-219719833

**Comment by Sytten** [comment]
Done https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/cc8f216fa606b9ee41cb81b0c95dc2de2b5a0b44
