### ISSUE TITLE
I cant find option to change theme

### ISSUE THREAD

**Issue by kasalolek** [Aluxian/Facebook-Messenger-Desktop#422]
In linux version ther is no option to change theme to dark

**Comment by Sunderfield** [comment]
Options menu appears when you right click the messenger icon in your taskbar.

**Comment by zatherz** [comment]
The menu didn't appear for me when I right clicked the icon in the task bar (only the DE's standard context menu appeared), but it did work when I right clicked inside the program.

**Comment by Sytten** [comment]
This is fixed in the next release

**Comment by sarthak-0415** [comment]
and when is the next release?

**Comment by Sytten** [comment]
As soon as I can get the mac build from Aluxian

**Comment by Sytten** [comment]
Please try the release:
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.4.8
