### ISSUE TITLE
Virustotal finds an adware

### ISSUE THREAD

**Issue by akolpakov19** [Aluxian/Facebook-Messenger-Desktop#423]
During the analyzing of the messenger installer virustotal.com finds and adware  	**Adware.AddLyrics.Win32.8327** 
Screenshot attached
![messanger_virus](https://cloud.githubusercontent.com/assets/10233620/15449349/50e02cf2-1f7b-11e6-9356-b869551fa27e.JPG)

**Comment by nevercast** [comment]
AddLyrics installs itself as a Chrome Extension. There is likely similar boilerplate code as MFD is a Chrome Application.

Zillya probably uses some poor heuristics. Thanks for letting us know, @akolpakov19

**Comment by akolpakov19** [comment]
Ok, I see, thank you @nevercast  for the quick reply.

**Comment by Sytten** [comment]
Closing issue

**Comment by karasuhebi** [comment]
Why was this closed? The installer still pushes adware on you.

**Comment by Sytten** [comment]
Not the same issue since this is about the old installer.
