### ISSUE TITLE
Facebook messenger PPA?

### ISSUE THREAD

**Issue by gameslayer** [Aluxian/Facebook-Messenger-Desktop#424]
Can we get a PPA for Linux? this will be a lot easier and a better solution for app updates on Linux.

**Comment by Aluxian** [comment]
Messenger for Desktop 2 will have one for sure.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sun, May 22, 2016 at 4:40 PM, gameslayer < notifications@github.com [notifications@github.com] > wrote:
Can we get a PPA for Linux? this will be a lot easier and a better solution for app updates on Linux.

**Comment by gameslayer** [comment]
Awesome! let me know when you make one I do want to add this to the store I am making for Linux

http://cdfrosty.wix.com/store

**Comment by Majki** [comment]
> Messenger for Desktop 2 

Woot Any more details about that?

**Comment by Aluxian** [comment]
It'll run on Electron, it'll have more features, it'll consume less battery. :)

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Mon, May 23, 2016 at 10:54 PM, Majki < notifications@github.com [notifications@github.com] > wrote:
Messenger for Desktop 2

Woot Any more details about that?

**Comment by 19darion91** [comment]
I know that it is "rude" to ask. But any e.t.a. for Messenger for Desktop 2?

**Comment by gameslayer** [comment]
When does facebook messenger 2 come out? I also have a question what exe process on messenger?

**Comment by Sytten** [comment]
I think I might add a PPA if I have some time later. I need to work on the update system for V1.5.0
