### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by 19darion91** [Aluxian/Facebook-Messenger-Desktop#425]
@Sytten for what I can see in the Issue part for this app, there is a version 1.4.8 and 1.4.9 around. How can I install them and where to get them. When I download the Aluxian app from the web page it is version 1.4.3 and your fork is version 1.4.7 when downloaded from your page. And pls. don't tell me to build it... :D For some reason I'm having an extremely hard time setting up gulp in windows.

**Comment by Sytten** [comment]
V1.4.8 is a milestone, that means its being currently developed and it will be release soon. My goal is to release V1.4.8 next week if we can tweak some remaining details.
Dont worry we will make builds for everyone when its ready :)

**Comment by 19darion91** [comment]
Ok, thanks! One more question, will the update be available in your fork or in Aluxian's veriosn?

**Comment by Sytten** [comment]
They will be available in both :)
