### ISSUE TITLE
many issues with dark themes

### ISSUE THREAD

**Issue by cabban** [Aluxian/Facebook-Messenger-Desktop#426]
love this apllication, but many many issues with the black theme windows , wrong color on many places cant see text etc
hope u fix this _=)  need white text and sub bar black or with anyway black text color , now its white on white 

![3](https://cloud.githubusercontent.com/assets/19514493/15581180/9f2a6dc0-236b-11e6-8972-6ab21c52994c.jpg)
![2](https://cloud.githubusercontent.com/assets/19514493/15581181/9f2c5518-236b-11e6-9aa5-fd49d301be22.jpg)
![1](https://cloud.githubusercontent.com/assets/19514493/15581182/9f2cf3d8-236b-11e6-9937-264a254f2c55.jpg)

**Comment by Felluz** [comment]
I agree, had to use default theme cause of this...sad..hope get fix soon!!!

**Comment by ethannu** [comment]
I am using autohide menu. When hovering over menu, selected friend and search bar are transparent.
Issue is not affecting default theme.

![msgscreen](https://cloud.githubusercontent.com/assets/10129507/15626706/74953f4c-24cc-11e6-9493-ae0d69090d2d.png)

**Comment by tristankhalil** [comment]
Please fix! I wanted to use the dark/mosaic themes but I can't read what I'm typing so I always switch back to the default theme :( 

![screenshot_14 png 429x677](https://cloud.githubusercontent.com/assets/12205893/15668203/9c36f7e8-274c-11e6-9ecd-8871c841d5e0.png)

**Comment by Sytten** [comment]
I fixed most of dark theme problems for the next release...
If you want to help me. Give the css class of the objects that are wrong and it will then be very easy for me to fix them.

**Comment by skyli91** [comment]
It doesn't look like this at all with 1.4.7 :o 
![image](https://cloud.githubusercontent.com/assets/7442913/15774536/2ce826c2-297d-11e6-98f6-dec602e196e7.png)

**Comment by Felluz** [comment]
and how to install the 1.4.7 version? please tell us!!

**Comment by tristankhalil** [comment]
@skyli91  How to install 1.4.7? Mine is 1.4.3 and says it's the latest version.

**Comment by Sytten** [comment]
Yes its my build (on my fork), but I now am one the official maintainer of the app. I will do a release really soon. You can install my fork builds meanwhile if you want.

**Comment by tristankhalil** [comment]
@Sytten sadly i don't have any idea how to do that. LOL I just came here to report.

**Comment by lilchancep** [comment]
@tristankhalil

 https://github.com/Sytten/Facebook-Messenger-Desktop/releases/tag/v1.4.7

There is the link to version 1.4.7

**Comment by tristankhalil** [comment]
@lilchancep WOW thank you!

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
