### ISSUE TITLE
MFD doesn't allow me to paste links

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#428]
> I installed Win10 FB Messenger software on my PC but it doesn't allow me to paste links. The official Win10 Messenger software (off the Win 10 store) does.

Received by email from Eric.

**Comment by Sytten** [comment]
Strange I dont have this issue on W7

**Comment by Sytten** [comment]
Since we cant debug with that little information, I'm closing
