### ISSUE TITLE
Control + Backspace

### ISSUE THREAD

**Issue by Musaka96** [Aluxian/Facebook-Messenger-Desktop#429]
Using Control + Backspace deletes the whole word as expected, but it wont delete the space, so u cant use it to quickly delete a couple of words or the whole thing. It not that i can use PgUp and PgDn, its just that it bugs me cuz i use Ctrl.

**Comment by Sytten** [comment]
Thank you for reporting that, but I'm sorry to say that we wont fix that because its a lot of work for such a little feature. I encourage you to try to propose a fix and PR it!
