### ISSUE TITLE
Bringing Messenger icon back after message.

### ISSUE THREAD

**Issue by zaxad23** [Aluxian/Facebook-Messenger-Desktop#43]
That's my plan:

1. You have Messenger app opened.
2. You receive a message from X.
3. In system tray, app replaced a Messenger icon to X's profile picture.
4. When checked message, bring back Messenger icon.

P.S. Sorry for my English :us:

**Comment by Aluxian** [comment]
I, personally, don't like this behaviour. I think a badge is enough, sorry.
