### ISSUE TITLE
Connection error drains CPU heavily on Windows

### ISSUE THREAD

**Issue by adrianblp** [Aluxian/Facebook-Messenger-Desktop#430]
I just had something weird happen. I had some form of connection error with the Messenger client, the icon changed to have the red thing in the corner and started blinking, no big deal. I started up Overwatch and my frame rate dropped from high double digits to below single digit, my GPU stats looked OK so I thought it was something with the GPU being under heavy load. I closed down more or less all my programs without any change in performance, I saw Messenger blinking like crazy and right as I closed it down my performance was back to normal.

From this I can only assume that the CPU drain and messenger being in the state of a connection error are related, which seems to be a serious problem.

**Comment by Sytten** [comment]
The next version prevents the icon from changing more than once per second, so it should resolve mostly your problem.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
