### ISSUE TITLE
Can't connect Messenger.com over Sock v4 proxy

### ISSUE THREAD

**Issue by thangngoit** [Aluxian/Facebook-Messenger-Desktop#432]
Can't connect Messenger.com over Sock v4 proxy

**Comment by Sytten** [comment]
If you can provide more information about that, currently I cant help you.

**Comment by thangngoit** [comment]
Thanks u. I provide more information as bellow:
Setting proxy in Firefox
- Proxy: manual proxy configuration
-Type: SOCKS host v4
Screen shot: [http://i.imgur.com/n2edjuV.jpg](url)

SOCK host by create ssh connection to ssh machine to bypass Network fillter.

**Comment by Sytten** [comment]
So if I understand you correctly you want to have the possibility to add a sock v4 proxy. That should be easy since its a chromium browser running. You should be able to do it yourself, I might add a button to open the menu in a future version.

**Comment by thangngoit** [comment]
Thank you for your support :)
