### ISSUE TITLE
Development Branch Bugs (OSX)

### ISSUE THREAD

**Issue by lilchancep** [Aluxian/Facebook-Messenger-Desktop#436]
- [x] Dock Badge Persistent

> I received a message and checked it but the application icon still shows 1 unread message. Even completely closing and re-opening messenger does not clear the badge on its dock icon. 

- [ ] Crazy High energy impact

> Energy impact when the messenger window is not minimized to the dock is 10-20, when receiving a message it peaks around 30. i would imagine this would destroy a laptop battery.

# Testing in Progress

**Comment by Sytten** [comment]
Issue of High energy impact is widespread for all platforms due to the 12 fps refresh rate (I think). I currently don't know how to fix it...

Dock badge issue will we fixed before release...

**Comment by Sytten** [comment]
Dock badge should be fixed (took my 4h to find :P)

Working on the high energy consumption. I will release BETA builds later tonight.

**Comment by Sytten** [comment]
BETA will be up during the day!!!

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
