### ISSUE TITLE
Voice/Video calls in APP and not MESSENGER.com

### ISSUE THREAD

**Issue by BurkeKnight** [Aluxian/Facebook-Messenger-Desktop#439]
Would like to see the Voice and video call buttons in app actually be able to do the calls in app, instead of opening the browser to Messenger.com. I'd not noticed, until tried to make such a call, that they were only links. To me, that is a bit sloppy, especially since there's **NOTHING** stating this **ANYWHERE**.

**Comment by Aluxian** [comment]
@Sytten @nevercast They open in the browser? Last time I used video calls (months ago) it opened in a new window. There's a piece of code somewhere that decides whether to open it in the browser or in a new window, I think a condition can be added there to fix this.

**Comment by Sytten** [comment]
Since its still your build in the production I guess Facebook changed their API. I will take a look this weekend :+1: 

@BurkeKnight Thank you for reporting...

**Comment by BurkeKnight** [comment]
Yes, opens in new window. Browser window.

**Comment by Sytten** [comment]
Yes I just exprienced it, I will investigate

**Comment by BurkeKnight** [comment]
@Aluxian That is what mean. It's a program, not a browser window, which is why it should open in the actual program, not in new window, or browser. Like @Sytten seems to understand.

**Comment by Sytten** [comment]
hahahaha I found the problem. Uncheck the setting Open links in browser and voila!

**Comment by Sytten** [comment]
I will fix this in the the beta.1 (if I can make the beta.0 available, waiting on you @Aluxian )

**Comment by Sytten** [comment]
Fixed: https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/1f76ab2e7d7ecccb6b4e1add5a75f1559c0bd1e7
Will be in the next beta release.
