### ISSUE TITLE
Website previews are MASSIVE

### ISSUE THREAD

**Issue by rikai** [Aluxian/Facebook-Messenger-Desktop#440]
When a link is posted, the preview image for them is MASSIVE

For example:
![image](https://cloud.githubusercontent.com/assets/515221/15983037/af2b0cc6-2f4f-11e6-8b58-3b5bdf5a96dc.png)

It takes up almost a 1/4 of my screen at 2560x1440 and over half the chat window which seems kind of excessive.

**Comment by Sytten** [comment]
We have lots of problem with DPI screens. I currently dont plan to work on this before release 1.5.0 and since I dont own a screen like that my self it will be hard to debug.
Remember that MFD is only a wrapper, so if facebook doesnt handle it well, there is little we can do...

**Comment by rikai** [comment]
Thats the confusing part, i don't see the same issue on the web-based Messenger. Technically this isn't even a HiDPI screen, just 1440p... Have the same issue on a 1080p screen as well.

**Comment by Sytten** [comment]
Do you use chromium/chrome with the web base messenger? Its seems very odd to me since I dont touch the html page in any way...

**Comment by rikai** [comment]
Sorry for the delayed respons.

Yes, i do indeed use chrome when using the web messenger.

**Comment by Sytten** [comment]
I also happen to find the preview a little bit big (not as big as yours), but I have no solution for you right now. I guess I would have to mess up with the html of the page to reduce it (which I find strange considering that I dont touch the rendering part). 
I will mark it as a todo, but I dont promise anything :/

**Comment by skyli91** [comment]
It should be just a css edit.
This is for me at fullscreen, and the same happens in chrome too so it must be css. I also wonder why i have to add a space after a link to have a preview.  :D
![image](https://cloud.githubusercontent.com/assets/7442913/16445777/879c692c-3de4-11e6-972f-139f9b891bde.png)

**Comment by skyli91** [comment]
._3058._15gf {
    max-width: 800px;
}

i can only put it to theme's css or somehow globally? like base.css? (i should move my edits with the scrollbar there too.

**Comment by skyli91** [comment]
made a pull request, it should work: https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/464

**Comment by Sytten** [comment]
Yea apply for each css page, should work. 
All the images have the same class?

**Comment by skyli91** [comment]
It worked in chrome browser :)

**Comment by Sytten** [comment]
Good its merged, will be in the next beta (maybe this weekend, if I'm done moving to my new apartment).
