### ISSUE TITLE
Window title is changing constantly

### ISSUE THREAD

**Issue by stelariusinfinitek** [Aluxian/Facebook-Messenger-Desktop#441]
I'm using the latest version of Facebook-Messenger-Desktop. I had this bug for a long time.

I'm using Arch Linux with Xfce4. The window title is changing like crazy between "Facebook" and "Messenger". Like 4 times per second. 

(Putem vorbi și în română :) )

**Comment by Sytten** [comment]
I never encountered this problem. Is it only when you receive a message? Maybe the regex we use isn't working well in your language...

**Comment by Aluxian** [comment]
@Sytten Yeah, we have that regex... I think we could [throttle](https://www.npmjs.com/package/lodash.throttle) the function that updates the title.

**Comment by Aluxian** [comment]
(putem, dar nu ne inteleg toti :) )

**Comment by Sytten** [comment]
Yes its throttle in the beta version, but it wont fix the issue entirely. Probably will have to change the way we check for new messages.

**Comment by Sytten** [comment]
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
Open a new issue if its still doing that with the beta
