### ISSUE TITLE
App crashes on Linux when attempting to drag an image onto the window

### ISSUE THREAD

**Issue by zesterer** [Aluxian/Facebook-Messenger-Desktop#442]
The title explains it all.

**Comment by Aluxian** [comment]
Does it show a dialog? An error message anywhere? Let's debug this:

1. Open your terminal
2. Enter `export DEBUG=whatsie:*`
3. Enter `whatsie`

**Comment by Aluxian** [comment]
_(ignore my previous (deleted) comment, I thought this was for Aluxian/Whatsie (again)...)_

**Comment by Sytten** [comment]
Can you be more specific, I used this app for more than a year without encountering this problem...
I need a test case to reproduce it.
Can you also provide the distribution you are using...

**Comment by Sytten** [comment]
Since we dont have more information I'm closing the issue
