### ISSUE TITLE
Links opening in external window instead of browser

### ISSUE THREAD

**Issue by Jcoraline** [Aluxian/Facebook-Messenger-Desktop#443]
Hi,

I really enjoy using the app, but a while ago it changed so all links would open in an external small window and ask me to leave facebook. Before it used to just open the links directly in my browser. I end up copying and pasting the link into my browser so I can actually access more of the site. 

I hope that description made sense, I thought it worked much better as it was before. 

![screen shot 2016-06-12 at 01 01 01](https://cloud.githubusercontent.com/assets/19880599/15987841/457b5020-3039-11e6-8106-fd15e21ea20f.png)

**Comment by Sytten** [comment]
Have you checked the related setting?

**Comment by Sytten** [comment]
Not any feedback, closing
