### ISSUE TITLE
Background processes don't end on close (Win10)

### ISSUE THREAD

**Issue by elainevdw** [Aluxian/Facebook-Messenger-Desktop#445]
I can't always relaunch Messenger after closing it. I've noticed that if I go into Task Manager, there will be four Messenger.exe background processes. If I end those tasks, I can then relaunch Messenger. [Here's a screenshot](https://elainevdw.tinytake.com/sf/NzQ1NTg2XzM0MjIyNTA) of my Task Manager after closing the program. I'm on Win 10 64-bit if that helps.

Thanks for an awesome little desktop app!

**Comment by Sytten** [comment]
W10 wasn't handled very well with the framework version used in that release, I think it will be resolved with the beta I will release this week.

**Comment by Frantik02** [comment]
When you close the main window, the app is actually minimized to the system tray. You should be able to see the Messenger Icon hidden in the system tray menu.

**Comment by elainevdw** [comment]
Wow... how on earth did I miss that???????? Geez I feel like a n00b now. Thanks.

**Comment by Sytten** [comment]
Great, resolved. Didnt thought about that haha
