### ISSUE TITLE
Drafted Messages

### ISSUE THREAD

**Issue by ohmel** [Aluxian/Facebook-Messenger-Desktop#446]
I accidentally pasted a large excel content in the input box on one of my contacts. The app just stopped there and won't respond. I restarted the app and it loaded that contact message history but the message I pasted was still there like it was put into drafts where in the last message you want to send is still saved there and it made the app unresponsive just as when I click that contact. I tried also to uninstall this app and re-install it, didn't work. That thing I pasted keeps showing on that textbox for that contact alone. All my contacts are working fine... I can use the app with other contacts but for that particular contact the app becomes unresponsive. Is there any thing I can do to take that drafted message?

**Comment by Aluxian** [comment]
Hey, please try these methods:

- Go to https://www.messenger.com/ and try to clear the message from there
- If your browser gets stuck as well, try with a more powerful PC (maybe a friend's or a coworker's); my reasoning is that doing so, the browser won't freeze anymore and you'll get to clear that message
- Use Messenger on your smartphone and delete the message there
- I don't know if this would work, but... maybe some actions on Facebook reset the message; so you could try to unfriend that person and befriend them again (explain the situation to them first)
- Contact Facebook to resolve it for you

I'll post here if I get other ideas.

**Comment by Sytten** [comment]
Clear the cache would be the best solution I imagine

**Comment by Sytten** [comment]
I will close the issue, if you need more help please open a new issue :)
