### ISSUE TITLE
Ability to Disable Esc Button

### ISSUE THREAD

**Issue by mjbrancato** [Aluxian/Facebook-Messenger-Desktop#449]
Every time I press the escape window to exit out of a view, the whole app closes. I was wondering if it was possible or to have an option to disable the ESC key from quiting the application. This is in Xubuntu 16.0.4

**Comment by team6612** [comment]
Same requirement. I need to press Esc when using Chinese input method sometimes. But it closed the entire window accidently. I'm using Windows version.

**Comment by Sytten** [comment]
I'm working on a new stable release with these fixes. Still have some problems on windows, will be out soon.

**Comment by Sytten** [comment]
Please try the beta:
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.4.8
