### ISSUE TITLE
Add to tray option like Whatsie in Linux

### ISSUE THREAD

**Issue by ar13pit** [Aluxian/Facebook-Messenger-Desktop#451]
Hi it would be great to have the add to tray option in Linux.

**Comment by Aluxian** [comment]
Hey, Messenger for Desktop 2 will have this. ETA: this summer!

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sat, Jun 18, 2016 at 9:26 PM, Arpit Aggarwal < notifications@github.com [notifications@github.com] > wrote:
Hi it would be great to have the add to tray option in Linux.

**Comment by ar13pit** [comment]
Cool. Thanks.
