### ISSUE TITLE
Official testers

### ISSUE THREAD

**Issue by Sytten** [Aluxian/Facebook-Messenger-Desktop#455]
Hi,

I need you guys to test out the new release before its published to everybody.
You can find it here:
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.4.8

For all problems, please open an issue with [Beta 1.4.8] in the title. Thank you!

I'm currently searching for official testers on Windows and Mac because I don't have the time to test the software on those platforms.

Sytten

**Comment by ForumLiker** [comment]
![2016-06-26 15-57-29](https://cloud.githubusercontent.com/assets/11502792/16361574/977718cc-3b9d-11e6-933e-900e51d83f6d.png)

**Comment by Sytten** [comment]
Have you tried deleting the cache?

**Comment by ForumLiker** [comment]
$HOME/.config/Messenger
/opt/MessengerForDesktop
Remove, and then set a new version. did not help.

**Comment by Sytten** [comment]
Can you try something for me? Uncheck the setting open links in browser and type in the console: window.open('https://www.messenger.com')

I'm really lost with this SSL problem...

**Comment by ForumLiker** [comment]
Uncheck tick and the console has entered....
Opened empty box.
Error in console
localStorage: [Exception: DOMException: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs.]
sessionStorage: [Exception: DOMException: Failed to read the 'sessionStorage' property from 'Window': Storage is disabled inside 'data:' URLs.]
![2016-06-26 22-31-58](https://cloud.githubusercontent.com/assets/11502792/16363507/f4539c78-3bd4-11e6-816a-6360671053a2.png)

**Comment by Sytten** [comment]
If you try some other site instead of messenger.com?
So have reported that the v1.5.0-beta.0 is working for them, you might want to try it out also.

**Comment by Sytten** [comment]
I will close this issue since its not relevant anymore, but I wont delete it.
