### ISSUE TITLE
Option to disable or delay notification sounds.

### ISSUE THREAD

**Issue by mzso** [Aluxian/Facebook-Messenger-Desktop#456]
Hi

What I'd like is an option to mute notifications. In some circumstances the sounds are undesirable.

What would be even nicer is auto disabling or even better delaying the notification sound when there's another program is running in full-screen mode.

**Comment by Sytten** [comment]
If you have sound notifications then youre probably the only one here right :)
You can mute the sound via the facebook settings.

**Comment by mzso** [comment]
Well, I was using the stable version. Anyways, I'm guessing it will return. I didn't know about the facebook setting.

PS:
BTW what happened to the sound?

**Comment by Sytten** [comment]
The sound never worked, at least for everybody here :)
But its due to a lib ffmpeg which is currently compiled without the MP3 decoder. 
I will replace those lib in a future release.

**Comment by mzso** [comment]
Huh. I had sound here yesterday with 1.4.3.

**Comment by Sytten** [comment]
Sound notification maybe then, but not sounds in general (if you try to play an mp3 for example).
I actually never tested the sound notifications...

**Comment by Sytten** [comment]
EDIT: Sound notification are there if you activate them in the facebook preferences. 
We should put an option for it in our settings.

As for delay I don't think its a good idea to wait if another program is full screen, that would be hard to detect in the first place on all platforms and would probably create strange side effects sometime...

**Comment by mzso** [comment]
[**@Sytten**](https://github.com/Sytten) commented on [2016. júl. 4. 06:04 CEST](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/456#issuecomment-230200883 "2016-07-04T04:04:51Z - Replied by Github Reply Comments"):
> EDIT: Sound notification are there if you activate them in the facebook preferences.   
> 
> We should put an option for it in our settings.
> 
> As for delay I don't think its a good idea to wait if another program is full screen, that would be hard to detect in the first place on all platforms and would probably create strange side effects sometime...

Hi!
You closed this, but I don't see an option for it. Did you decide against it?

**Comment by Sytten** [comment]
Well I don't see the point of adding another option for sound notifications when you can disable them in the facebook options.
As for delay, I just don't think its a good idea.
