### ISSUE TITLE
Information and help needed

### ISSUE THREAD

**Issue by Sytten** [Aluxian/Facebook-Messenger-Desktop#458]
Hi,

I'm currently the official maintainer for Messenger For Desktop. I'm opening this issue, because I feel a bit overwhelmed with the project right now. With finals coming soon that won't get any better.
I think @Aluxian, you can understand that.

What I need most right now is:
- Testers on windows and mac who know how to report issues (meaning they know how to debug webapps)
- Git maintainer to parse the issues and close the duplicates (can't find my way in more than 200 issues)
- Maybe a developer since I didn't heard a word from @nevercast for the past month.

I know its a lot to ask, but I won't be able to continue like that...

Even if you don't want to be an official tester or anything else, you can still help me by using the latest beta and reporting the issues with the tag [v1.5.0-beta.x] (change x for the beta number). Currently:
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.0

@Aluxian also asked me to do a release with the old version of NWJS (0.12.3), I know some people on Linux have trouble with it, but if you can help with this release too I would be glad (use the tag [v1.4.8] when opening an issue):
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.4.8

Finally, I created a wiki (https://github.com/Aluxian/Facebook-Messenger-Desktop/wiki) to regroup all the tips and information about the software. Feel free to help me populate it.

Thank you all for your support and I hope you enjoy the software!

**Comment by cassiodoroVicinetti** [comment]
Nice to hear that the project has a new maintainer!

I will try to give my little help, although I have very little free time.

**Comment by Sytten** [comment]
Thanks @cassiodoroVicinetti, you helped me on my fork and I really appreciate it!

**Comment by GAMELASTER** [comment]
I will try to help with this awesome thing, I can test on every platform, so nice + I have a lot of research of work the messenger.com app. Actually, I don't have a lot of time to look all issues and trying it to solve, but you could notify me on issue what you don't have time to solve or just any reason, I will try to do it! Anyway, I'm happy the @Aluxian add new contributor as he said me on e-mail and thanks @Sytten to investing your time in this!

**Comment by orschiro** [comment]
Dear @Sytten,

I just gave the latest Beta a try on Ubuntu 16.04 and it works great!

I especially like the new tray icon. :smiley: 

Thank you for your work!

~Robert

**Comment by Sytten** [comment]
@orschiro Good, great to hear that!

@GAMELASTER I mark the issues with the milestone corresponding to their release. If you want you can pick one that isn't assigned and fix it :)
A nice feature would be to add shorcuts in the app, this request has been reported many times. Someones forked the software and incorporate it (see https://github.com/dkess/Facebook-Messenger-Desktop), but his modifications are based on the old master branch (all dev now is in the V1.5.X branch) and I'm not sure the code is very clean.
That feature would allow us to enable a zoom function easily, which is another feature that has been requested many times.

**Comment by fabpin** [comment]
Hi, Sytten, i want to join like a developer, on the project, just need know, you use NW.js like a framework for develop this awesome project? just i need, for start the documentation of the project, and the confirmation about for the future development will develop with this framework?

**Comment by Sytten** [comment]
Hi @fabpin, yes we use NW.JS as our framework.
Aluxian wants to move to electron eventually, but don't know when it will be ready for release. I plan to continue to support the version based on NW.JS because I like this framework and releases are now sync with the chromium releases.
We don't have an official documentation though it would be nice to have one, the code needs a major refactoring and help on that would be nice.
The best way to get started would be to chat with me on gitter and test stuff on your own.

I'm currently working on the beta.1 version, you can see the milestone. If you see an issue that you would like to help on, I suggest you fork the repository and work on it. I currently don't have the right to make you an official contributor, we must first ask @Aluxian.

**Comment by Aluxian** [comment]
I think having @Sytten as an official maintainer is enough (i.e. he's doing a great job already). Anyone who wants to help is very welcome to send PRs, chat with us on Gitter, provide feedback and test releases.

**Comment by Sytten** [comment]
yep understand that perfectly. PR is a good way to contribute anyway.

**Comment by Sytten** [comment]
I will work on the next beta today.
Might have time to release it tonight (eastern time) or tomorrow night.
Stay tuned.
