### ISSUE TITLE
Press Esc key to close window

### ISSUE THREAD

**Issue by silentw** [Aluxian/Facebook-Messenger-Desktop#46]
Optional!

**Comment by ulgens** [comment]
ESC is not "close" button. We already have universal shorcut for that: `Alt + F4`

**Comment by silentw** [comment]
Most of the IM applications (like Pidgin) has that option, since Windows Live Messenger that option exists. I got used to it so now I can't live without it.

I think it's more comfortable than using the combination of two buttons instead of a simple button.

**Comment by Aluxian** [comment]
@silentw Are you using Windows?

**Comment by silentw** [comment]
Yes, Windows 8.1 Pro

----- Mensagem Original -----
De: "Aluxian" <notifications@github.com>
Enviado: ‎23/‎04/‎2015 20:17
Para: "Aluxian/Facebook-Messenger-Desktop" <Facebook-Messenger-Desktop@noreply.github.com>
Cc: "Ricardo" <siilentw@gmail.com>
Assunto: Re: [Facebook-Messenger-Desktop] Press Esc key to close window (#46)

@silentw Are you using Windows?

**Comment by kaaboaye** [comment]
It can be hard to do because this is only client for messenger.com

**Comment by silentw** [comment]
I know, but when you press Esc key it would be just as you close the window using the "X" button.
