### ISSUE TITLE
Crash at close Ubuntu 16.04

### ISSUE THREAD

**Issue by Kingbalou** [Aluxian/Facebook-Messenger-Desktop#465]
Hi ,
when i close the messenger app 
Ubuntu always says that there a problem and had to send a report.

**Comment by Sytten** [comment]
What version are you using?
Have you tried the latest beta? (See #458)
Can't do anything with the information you give here.

**Comment by Kingbalou** [comment]
No more crash report when i close the app with beta.
What information do you need ?

**Comment by Sytten** [comment]
Well thats good, if you any problem please open a new issue ;)
