### ISSUE TITLE
Cannot change to dark theme

### ISSUE THREAD

**Issue by TPC3D** [Aluxian/Facebook-Messenger-Desktop#468]
Perhaps this was caused because of [this](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/459), but I can no longer switch themes, it appears. There is no option for it under the settings menu, and with the rightclick menu(context menu?) disabled I don't know how else to do it.

Sorry if I'm missing something obvious, I moved from v1.4.3 to the beta v1.5.0 just to fix the dark mode, however, again, I can't seem to switch to it at all now.

Let me also apologize as I've never used github before so perhaps I'm doing something wrong here. and again, there's always the possibility I missed something somewhere, so if so, I apologize.

I'm running Windows 10. Any help is appreciated!

Thanks!

**Comment by Sytten** [comment]
Hi! Thanks for using the beta!
When you right-click on the tray icon you can find the setting related to themes.

Here is an example on linux.
![screenshot from 2016-06-30 13 24 21](https://cloud.githubusercontent.com/assets/2366731/16497646/165c87aa-3ec6-11e6-9902-c0314ddda703.png)

**Comment by TPC3D** [comment]
Thank you, sir! I apologize if I missed that in the changelogs anywhere!

**Comment by Sytten** [comment]
Not a problem! The tray icon was present from some time now :)
