### ISSUE TITLE
Dark Theme Button Missing?

### ISSUE THREAD

**Issue by soccernerd05** [Aluxian/Facebook-Messenger-Desktop#469]
As of today the dark theme button has been missing from both the website and the messenger desktop app, please fix this issue!

**Comment by Sytten** [comment]
Not sure want your talking about. Please provide at least a screen capture.
Also what version are you using? I have been upgrading the software to version 1.5.0-beta.0 lately.

**Comment by soccernerd05** [comment]
![no dark theme](https://cloud.githubusercontent.com/assets/16909181/16543035/42d5cefa-4087-11e6-8480-e4bf63f9d8e7.png)

There used to be a button that would switch the site/app into a dark theme from the regular theme. I've circled in red where the button used to be. I am using the website, I have also been updated to the most recent version of the app and tried it on that but it still doesn't work. If there's anything else that needs to be provided please let me know as the issue still hasn't been resolved.

**Comment by Sytten** [comment]
Facebook deleted it. Not our fault at all and really not an issue about our software. Please contact Facebook for that.
However, we do provide an option to switch to a dark mode. If your right/left click on tray icon you will see the theme sub-menu from which you can decide theme.
You won't get the dark theme in your web browser, but you will have it in the app.
