### ISSUE TITLE
Linux SSL_ERROR_ENCRYPTION_FAILURE Causes Not To Load the Page

### ISSUE THREAD

**Issue by erayerdin** [Aluxian/Facebook-Messenger-Desktop#474]
The title of app is `app.html` as below:

![image](https://cloud.githubusercontent.com/assets/2399084/16597009/57656c3e-42ff-11e6-803a-df2e1cf49723.png)

And the terminal output is as below:

    [2226:0705/221719:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
    ATTENTION: default value of option force_s3tc_enable overridden by environment.
    [2246:0705/221719:ERROR:sync_control_vsync_provider.cc(60)] glXGetSyncValuesOML should not return TRUE with a media stream counter of 0.
    [2226:0705/221719:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR

The page does not load and stucks as in image above.

***

# System Information

	Architecture:          x86_64
	CPU op-mode(s):        32-bit, 64-bit
	Byte Order:            Little Endian
	CPU(s):                2
	On-line CPU(s) list:   0,1
	Thread(s) per core:    1
	Core(s) per socket:    2
	Socket(s):             1
	NUMA node(s):          1
	Vendor ID:             GenuineIntel
	CPU family:            6
	Model:                 23
	Model name:            Intel(R) Pentium(R) CPU        T4400  @ 2.20GHz
	Stepping:              10
	CPU MHz:               1200.000
	CPU max MHz:           2200,0000
	CPU min MHz:           1200,0000
	BogoMIPS:              4388.57
	L1d cache:             32K
	L1i cache:             32K
	L2 cache:              1024K
	NUMA node0 CPU(s):     0,1

# Occuring Platforms

    Ubuntu 14.04
    Ubuntu 16.04

**Comment by ivanovsaleksejs** [comment]
The same error:

`[5333:0706/125112:WARNING:nss_ssl_util.cc(374)] Unknown SSL error -12218 (SSL_ERROR_ENCRYPTION_FAILURE) mapped to net::ERR_SSL_PROTOCOL_ERROR`

Platform:
> Description:    Ubuntu 14.04.4 LTS
> Release:        14.04

**Comment by mehdi-alouane** [comment]
here the solution #453

**Comment by erayerdin** [comment]
Not solved on Xubuntu 16.04 by #453 .

Current latest (1.5.0 beta) uninstalled
1.4.8 installed
Still same

However, issue seems to be duplicate of #453, so anyone having the same issue should go there. Issue closed.
