### ISSUE TITLE
Not loading in windows 10

### ISSUE THREAD

**Issue by sheldonhull** [Aluxian/Facebook-Messenger-Desktop#475]
I've been unable to load on two seperate systems with windows 10
I've tried the troubleshooting compatibility, and running as admin, windows 7 compat, etc. Nothing is working. 

Anyone else experiencing the issue on windows 10?

**Comment by sheldonhull** [comment]
Correction, windows 10 professional correctly opened it now after reloading. I will try Windows 10 Enterprise later and see if i'm still having it fail

**Comment by Sytten** [comment]
Have you tried the latest beta?

**Comment by Sytten** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/479
