### ISSUE TITLE
I don't have notifications

### ISSUE THREAD

**Issue by AkiyoSSJ** [Aluxian/Facebook-Messenger-Desktop#478]
The notifications are turned on but I don't receive when someone sends me a message, even the Facebook Messenger icon from the taskbar doesn't has the orange glow. I have Windows 10.

**Comment by Sytten** [comment]
What version do you use?
Are you sure that they are on, sometime they seem to disable themselves...

**Comment by AkiyoSSJ** [comment]
I have 1.4.3 . 
Yes they are enabled.

**Comment by Sytten** [comment]
No idea then, it should be working.
You can test the v1.5.0 beta if you want.
Can't really help if I don't have error logs or more information.
