### ISSUE TITLE
Can't running beta version on windows 10.

### ISSUE THREAD

**Issue by StayAwake14** [Aluxian/Facebook-Messenger-Desktop#479]
Hi. I just have read the list of fixes in the beta version and finally I thought I can run a new version with fixed themes but I can't because an application just opens the window with a title "Messenger - Connecting" and it can't to connect. Any ideas? or it is just code issue?

**Comment by Sytten** [comment]
Not code issue, the version is working fine.
Try to clear the cache (see the wiki for that).
Also make sure your are connected to the internet when you launch the software, can cause problems if you are not.

**Comment by StayAwake14** [comment]
Did it and it still not working.

**Comment by Sytten** [comment]
Can't help you much with so little information...

**Comment by StayAwake14** [comment]
https://scr.hu/pRN9Gn

I am connected to the internet so (?)...

**Comment by Sytten** [comment]
1. Try running as administrator
2. Try launching it using the command prompt and see the errors they give you.

Also can you right click on the tray icon?
It is really strange why its not working.

**Comment by nsudds** [comment]
I had the same "connecting" issues running the beta 1.48 edition but after switching to beta 1.50 it's working fine for me on Windows 10.   Just wanted to share.  I noticed that I had to re-login with the 1.50 update so I'm wondering if that has something to do with it because the update to 1.48 didn't prompt a new login it just got hung up at the connecting stage.

**Comment by Sytten** [comment]
Ho I didn't thought about that, it was too obvious for me...
Yes the V1.4.8 broken recently, the real beta is V1.5.0-beta.0.
I will change the website to point to it.

I'm currently uploading V1.5.0-beta.1 if you want to test it it will be up in the next hours :P

**Comment by StayAwake14** [comment]
Yes, I can test it. Thanks.

**Comment by Sytten** [comment]
Did the V1.5.0 helped?

**Comment by StayAwake14** [comment]
Yes. It works perfectly. Thanks a lot!
