### ISSUE TITLE
Support for Firefox products

### ISSUE THREAD

**Issue by Airon90** [Aluxian/Facebook-Messenger-Desktop#48]
Hi, 
As long as http://messenger.com/login doesn't work on Firefox OS (I don't know why), is it possible to create an app for Firefox products (Firefox OS, Firefox for Android, Firefox Desktop, Firefox for Tablet)?

Here is the doc to build a open webapp for Firefox: https://developer.mozilla.org/en-US/Apps
You can test it on Firefox OS simulator: https://developer.mozilla.org/en-US/docs/Tools/Firefox_OS_Simulator

**Comment by Aluxian** [comment]
Why doesn't http://messenger.com/login work for Firefox OS?

**Comment by Airon90** [comment]
If I go to login page it just redirect me to the home page.
I don't even know where to file this bug.
However thank you very much!

**Comment by Aluxian** [comment]
What country are you from? It might be that the website redirects some visitors. I'm not sure, but what I'm sure of is that something like this has happened before: some users wouldn't see the login form on the homepage and had to manually go to /login.

**Comment by Airon90** [comment]
I'm from Italy. I can login on my PC (Firefox under Arch Linux) but not from my smartphone (T2 Flame with latest Firefox OS). 
I never saw the "Login" button in the home page: I always had to manually go to /login ;)

**Comment by Aluxian** [comment]
I'm not going to support Firefox products, sorry.
