### ISSUE TITLE
Notifications in beta version

### ISSUE THREAD

**Issue by mosley93** [Aluxian/Facebook-Messenger-Desktop#481]
Hi, I installed 1.50 beta version of Messenger for desktop and I found out that the notifications display different way than it used to on the older version that I had. I'm using Windows 8.1 so I'm not used to look for notification on the right bottom corner of my screen, because all other apps notifications display in upper right cornet. Also I think the previous version of notification was better because in new ones there is too much text (you could disable the link to messenger,com) but far more important the white color of notification is harder to read than on blue one (I very often browse web, use file explorer or office which also have white background, so when the notification displays it isn't contrast enough to what I have on my screen). Putting it simple could you please revert the notifications to previous version?

**Comment by Sytten** [comment]
Hi!
The new notification are chrome-like notification.
We can't change it back to the native one for now since we don't control that process (handled by the framework we use).
Thanks for reporting and sorry we can't help you ;/

**Comment by cassiodoroVicinetti** [comment]
https://github.com/nwjs/nw.js/issues/4560#issuecomment-240387166
