### ISSUE TITLE
App fails to start.

### ISSUE THREAD

**Issue by TheBlackViper1996** [Aluxian/Facebook-Messenger-Desktop#482]
Whenever I launch the app the title says "app.html" and displays the loading animation constantly.
The app worked previously, it is the latest version (1.4.3) and has not been upgraded from a previous version, it is a clean install on a brand new laptop.
When I enter the Developer Tools it displays this error "Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR   https://www.messenger.com/login"

I am running Elementary OS Freya (Ubuntu 14.04) 64bit

**Comment by Sytten** [comment]
Have you tried the latest beta?

**Comment by hal08n** [comment]
Can't get either the beta (1.4.8) or the stable version to work on Ubuntu 14.04.  Same experience as Black Viper with 1.4.3; Beta (upgrade) brings up a blank window that says "Connecting" and won't close.  No idea what the issues are but right now it's not much use on Ubuntu.  Also no way to uninstall from the Ubuntu software center.

**Comment by Sytten** [comment]
Try with V1.5.0. On Ubuntu most people had trouble with the previous versions.

**Comment by Sytten** [comment]
SSL errors have been reported to be resolved with the beta https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.1

**Comment by Cellhawk** [comment]
Getting something similar here.
![untitled](https://cloud.githubusercontent.com/assets/8853211/18629509/37c5ca98-7e66-11e6-9875-5edc6f7cfbfd.png)
Loading for ages, then it just stays blank, without the loading animation.

**Comment by Sytten** [comment]
Windows store is not our version.

**Comment by Cellhawk** [comment]
I can see that. After a while, I can say it's horrible. Any suggestions with your version of messenger?

**Comment by Sytten** [comment]
I suggest you uninstall everything and clear the cache (see the wiki for that).
Then install A) https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.1
or B) https://github.com/Sytten/Facebook-Messenger-Desktop/releases/tag/v1.5.0 (My fork).
This should work.

**Comment by Cellhawk** [comment]
Downloaded the 1.5.0 "non-beta", works like a charm. Sadly, I won't have the latest update features, but still good, thank you.

**Comment by Sytten** [comment]
glad to hear. Well you could switch when the V2 will be more stable.
Give me a star if you like my fork ;)
