### ISSUE TITLE
Start in the background

### ISSUE THREAD

**Issue by g4be** [Aluxian/Facebook-Messenger-Desktop#483]
When the system start up and the `Launch on Startup` option is enabled, the app window pop up automatically. Sometimes it's a bit annoying and every time you should close it (I use notifications).
It would be awesome if there were an options which start the app in the background, so only "small icon" will be appeared on the system tray, whithout the window on the task bar.

**Comment by Sytten** [comment]
This is fixed in the beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
