### ISSUE TITLE
WM_CLASS is unavailable

### ISSUE THREAD

**Issue by mantasjk** [Aluxian/Facebook-Messenger-Desktop#484]
On linux you can use WM_CLASS name of an application to bind launch and running application icons to one by adding WM_CLASS name to .desktop file, so there isn't a duplicate of it in the tool bar. Messenger hasn't got any WM_CLASS assigned to it and so there are always two icons in the tool bar.

**Comment by Sytten** [comment]
Done in the beta, please use it
