### ISSUE TITLE
Beta doesn't connect

### ISSUE THREAD

**Issue by mantasjk** [Aluxian/Facebook-Messenger-Desktop#485]
On Ubuntu 16.04 messenger v1.4.8 doesn't connect. After launch a white window appears which says in the title "Messenger - Connecting" but it never does and also the whole window freezes/crashes which makes it impossible to close with X button.

**Comment by okgolove** [comment]
+1
I have the same problem. Fedora 23.

**Comment by Sytten** [comment]
Yes please use V1.5.0 previous version have known problems.
