### ISSUE TITLE
Visual Bug on Dark Theme

### ISSUE THREAD

**Issue by robiXxu** [Aluxian/Facebook-Messenger-Desktop#486]
On linux and also on mac version (don't know if also on windows but it's very likely)
When using the dark theme the textarea (message box is white also the text is white
just a CSS problem 

![darkthemebug](https://cloud.githubusercontent.com/assets/1962141/16894223/ca5b6c64-4b58-11e6-97d3-fcb3ed15a0f6.png)

**Comment by robiXxu** [comment]
the text in this case is selected

**Comment by Sytten** [comment]
Please use the stable, its been fixed

**Comment by robiXxu** [comment]
in the version from website isn't fixed and i also tried a stable release (v1.4.3) still not fixed...anyway..i'm gonna use my build.. 😎

**Comment by Sytten** [comment]
I meant the beta
