### ISSUE TITLE
Settings menu has issues displaying options

### ISSUE THREAD

**Issue by gandl** [Aluxian/Facebook-Messenger-Desktop#50]
Option for "Sounds" works fine, but the one for "Notifications" isn't properly displayed and can't be set. 
![messengererror](https://cloud.githubusercontent.com/assets/5646070/7332258/0348edd6-eb37-11e4-9297-741aef89343e.png)

I'm running 1.3.0 on Linux with Gnome 3.16. This issues was also present in the 1.2.4 version.

**Comment by Aluxian** [comment]
This is a bug with messenger.com itself. You should try resizing the window.
