### ISSUE TITLE
Tray icon is really big in taskbar

### ISSUE THREAD

**Issue by carmelo12341** [Aluxian/Facebook-Messenger-Desktop#500]
![screenshot_20160806_223028](https://cloud.githubusercontent.com/assets/9203764/17460312/d246bc2a-5c25-11e6-9988-948b7ff11ded.png)
I'm in Arch Linux and kde, that is how the tray icon looks

**Comment by Sytten** [comment]
We had some trouble with the tray icon at some point, now it seemed to be resolved for most people. Problems are mostly due to bad platform support from the framework and there is little we can do about it.

**Comment by cassiodoroVicinetti** [comment]
https://github.com/Sytten/Facebook-Messenger-Desktop/pull/8#issuecomment-229300302
