### ISSUE TITLE
Using Dark or Mosaic theme, the message box to type in is white

### ISSUE THREAD

**Issue by revalationist** [Aluxian/Facebook-Messenger-Desktop#502]
On its own, this is jarring and an odd stylistic choice, but the most annoying part is how the text seems to have been recolored to white and so it's practically invisible: http://i.imgur.com/8RDiw1r.png

It's slightly better with the Mosaic theme, but still.

I'm on Windows 10 (anniversary update) using v1.4.3

**Comment by Koolstr** [comment]
Still true for me as well, many months after the problem first arose.

Regardless though, the issue was fixed in [a fork by Sytten](https://sytten.github.io/Facebook-Messenger-Desktop/) (thank you so much dude!)

**Comment by revalationist** [comment]
Thankfully I found it was fixed in the new beta release. http://i.imgur.com/gONeehQ.png

**Comment by Sytten** [comment]
Yea just use the latest beta :P
