### ISSUE TITLE
Dark Theme Typing Text

### ISSUE THREAD

**Issue by AliasDidge** [Aluxian/Facebook-Messenger-Desktop#503]
So.... it would be nice to have the text you are typing as a message be something that you can see. It is the default white as with all the other text pieces in the dark theme. I tried changing it myself in the css, but I guess I didn't really know what I was doing. I think it's something that should be fixed in the overall theme though.

**Comment by ipeychinov** [comment]
You can fix that by unchecking the ![background-color](https://cloud.githubusercontent.com/assets/7293296/17644209/7106e55c-6189-11e6-94c3-a3521426048e.PNG) unfortunately it is not a very good solution, as you will have to do it every time you launch the app. Better than nothing I guess.

**Comment by AliasDidge** [comment]
But can't you just modify the css? I tried doing that like this: 
![capture](https://cloud.githubusercontent.com/assets/8867407/17654272/2f46a5c6-626f-11e6-952d-b473183e8b88.JPG)

**Comment by ipeychinov** [comment]
As far as I'm aware all the css lives [here](http://static.xx.fbcdn.net/rsrc.php/v2/yR/r/hE7IQLfIMoU.css) rather than locally on your pc, essentially the app is just a "web view", sort of, and you can't change the source, so essentially any changes you make only last until you 'refresh' the app/page. Then again I could be wrong, web has never been my forte.

**Comment by AliasDidge** [comment]
Why would the developer have source code then? Why am I able to download and build my own version of the program? Yes, there are web dev tools incorporated into it, but it is a desktop application. The dark theme is not even possible with the web version so that doesn’t even make sense. It would be nice to hear from the dev or someone that knows what they are talking about.

**Comment by Sytten** [comment]
Please use the beta, this is all fixed already
