### ISSUE TITLE
How to run application without generation exe file?

### ISSUE THREAD

**Issue by Lobster3** [Aluxian/Facebook-Messenger-Desktop#504]
Hello.

I am trying to run facebook messenger desktop without building executable. Just like any other app.

I am using "nw.exe Facebook-Messenger-Desktop-master" but it does not work. I've tried different commits and releases, but still no luck. Once run, three ns.js processes is started, but application window never appear. Processes are just stay forever and nothing happens.

What am i doing wrong?

**Comment by Sytten** [comment]
You must do it in the src file ;)
