### ISSUE TITLE
[Esc] key closes/quits messenger for desktop all together in Linux?

### ISSUE THREAD

**Issue by TheChuckster** [Aluxian/Facebook-Messenger-Desktop#507]
Any way to disable this behavior or at least make it so [Esc] hides/minimizes the app instead of exiting it?

Pretty annoying because most apps don't quit on [Esc], and I habitually use this key a lot to do things like try to close the giant pop-over image previews in FMD.

**Comment by keeferrourke** [comment]
Agreed, this is really annoying. Exit key shortcut should default to CTRL + Q  (CMD + Q on macOS).

**Comment by Sytten** [comment]
Fixed in the beta
