### ISSUE TITLE
Message bar does not change color when changing themes

### ISSUE THREAD

**Issue by joshc133** [Aluxian/Facebook-Messenger-Desktop#509]
Windows 7 (64 bit)
Dual Monitors

Message bar (where you type your actual message contents) does not change color to match theme, although message text does. This is not a problem for the default theme, but it is making the dark / mosaic themes nearly impossible to use as the message in progress text becomes light (correct behaviour) while the message background stays light (incorrect behavior).

![default](https://cloud.githubusercontent.com/assets/3443204/17754010/7fecb83e-64a0-11e6-93aa-4bde658fcc3d.PNG)

![dark or mosaic](https://cloud.githubusercontent.com/assets/3443204/17754025/970a71be-64a0-11e6-9d22-9f754d71a130.PNG)

**Comment by animismus** [comment]
I have the same issue!

**Comment by randalvance** [comment]
Tried version 1.5 beta and I don't encounter the issue anymore.

**Comment by joshc133** [comment]
@randalvance In the 1.5 beta release notes it says high CPU usage while window is visible. Do you experience this issue?

**Comment by randalvance** [comment]
![image](https://cloud.githubusercontent.com/assets/3318476/17797863/ebc38b1e-65fe-11e6-82b1-2d5e8dc5de30.png)
Don't seem to be consuming much CPU or Memory.

**Comment by ubergonmx** [comment]
I have the same issue, but to make it match:
1.) Open Launch Dev Tools
2.) Click magnifying glass
3.) Switch to messenger, hover and click the Chat bar
![image](https://cloud.githubusercontent.com/assets/12420631/17837283/b5ba2282-67e1-11e6-9a20-e7809218e1fe.png)
4.) Change `background-color` value to `#181818`
![image](https://cloud.githubusercontent.com/assets/12420631/17837292/080b8846-67e2-11e6-96b0-adb7b497f038.png)

There you have it

**Comment by Sytten** [comment]
Fixed in the beta
