### ISSUE TITLE
CURRENT DEVELOPMENT STATUS

### ISSUE THREAD

**Issue by Sytten** [Aluxian/Facebook-Messenger-Desktop#513]
Hi guys,

I wanted to keep you updated about the status of the software.
So currently we have a beta going on that fixes most of the reported bugs (Please us it!)

But the best thing is that we are moving for NW.JS to Electron for the next big release.
That means that no further development will be made in the current dev branch V1.5.X and we don`t plan to make a stable out of it.

The new code is in the branch develop and we are still working on it to make a stable that will be released soon.
For those who want a preview of it, I suggest you try to build it and give it a shot.
Any comments/suggestions will be appreciated.

Cheers!

**Comment by Yonezpt** [comment]
I am curious about the reasons behind the change to Electron, could you explain?

**Comment by Sytten** [comment]
Not my decision, @Aluxian
