### ISSUE TITLE
App appears in Task Manager as "nwjs (32 bit)" instead of "Messenger (32 bit)" or something like that

### ISSUE THREAD

**Issue by ekolis** [Aluxian/Facebook-Messenger-Desktop#521]
This is on Windows 10

**Comment by randalvance** [comment]
V2.0 doesn't have this bug anymore because they moved to electron.

**Comment by ekolis** [comment]
v2.0? Where is that? Is it stable enough for everyday use?

**Comment by randalvance** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases

It's beta so it will have bugs. But I am using it now as my daily driver.

**Comment by ekolis** [comment]
Cool!
