### ISSUE TITLE
Windows 8 Notifcations Don't Open App

### ISSUE THREAD

**Issue by enoordam** [Aluxian/Facebook-Messenger-Desktop#53]
I really like the new Windows 8 notifications in the latest version (1.3.0), but there is one issue. Clicking on the notification does not bring up the application.

**Comment by emerts** [comment]
+1

**Comment by alopix** [comment]
+1

**Comment by Aluxian** [comment]
Does this still happen in the newest release?

**Comment by enoordam** [comment]
Just tested on version 1.3.2 and it's still not working.
