### ISSUE TITLE
"Dark" or "Mosiac" theme, text in text box hard too see.

### ISSUE THREAD

**Issue by kaiserrath** [Aluxian/Facebook-Messenger-Desktop#531]
When using "Dark" or "Mosiac" theme, it makes the text written in the text box for sending messages very, very hard to see.

This is an issue I've had for quite some time now.
Perhaps, it could be fixed sometime. Thanks

![screenshot_1](https://cloud.githubusercontent.com/assets/21279894/18028345/db86f526-6c41-11e6-9ab5-19373af20ba5.jpg)

**Comment by Sytten** [comment]
This has been fixed in the latest betas
