### ISSUE TITLE
Direct link forwarding

### ISSUE THREAD

**Issue by orschiro** [Aluxian/Facebook-Messenger-Desktop#54]
Dear @Aluxian,

I noticed that all links opened from within Messenger are opened in the browser as follows:

```
http://www.messenger.com/l.php?u=
```

Is it necessary to do this URL forwarding? Can't we just open the links directly?

The reason I am bothered by this is that it first opens facebook.com asking me whether I really want to follow the link.

Thanks!

Robert

**Comment by orschiro** [comment]
Thanks for addressing it so quickly!

**Comment by Aluxian** [comment]
You're welcome! :)
