### ISSUE TITLE
Program is unstable all around

### ISSUE THREAD

**Issue by jasoncollege24** [Aluxian/Facebook-Messenger-Desktop#548]
Half the time, Messenger for Desktop won't open. In instances like this, checking the Windows task manager shows 4 background processes for it, but none will show the program window. The only option to resolve this is uninstalling and reinstalling the app.

Signing out, and signing back in causes messenger to display a blank white HTML page inside the program window, but nothing else.

Has been known to crash kinda often by either refusing to connect, or closing.

Current OS is Windows 10 - 64-bits, but these problems have appeared in all versions of Windows that I've installed it on. (Windows 7, 8, 8.1, and 10)

In this condition, this app is not viable for every day use.

**Comment by Sytten** [comment]
What version are you using?
The application is pretty stable on V1.5.0-beta.1 and no major issues with.
Try to clear your cache (see the wiki for that) and reinstall a beta version.

**Comment by jasoncollege24** [comment]
Whatever version was available for stable download on August 27th of this year. Looking at the Wiki, I'd guess 1.4.3

I appreciate the suggestion, but I generally stay away from beta software on my main computer, and at the moment, i do not have a suitable test environment.

2 days ago, I found something else that works, and appears to be quite stable. Good luck!
