### ISSUE TITLE
Unable update to the most recent version (2.0.2)

### ISSUE THREAD

**Issue by sbunciak** [Aluxian/Facebook-Messenger-Desktop#556]
* Operating system: El Capitan
* Messenger for Desktop version: 1.4.3

During app startup a popup apprears asking whether I want to download & update now. I hit OK and nothing happens.

**Comment by Aluxian** [comment]
We'll take care of that. In the meantime, please use our downloads page: https://github.com/Aluxian/Facebook-Messenger-Desktop/releases

**Comment by sheldonhull** [comment]
Please review this link immediately to prevent possible malware/adware issues. If I'm wrong I'm hoping for further updates there. 

https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/804
