### ISSUE TITLE
Press enter after search

### ISSUE THREAD

**Issue by arthurpenguin** [Aluxian/Facebook-Messenger-Desktop#56]
In the search bar, after typing the name of a person, it brings up a list of chats with people with that name. Pressing enter after the search should make the chat window of the first person on that list pop up on the chat window.

**Comment by kaaboaye** [comment]
If I understand you it's messenger.com problem.

**Comment by emerts** [comment]
You have to press arrow down and enter, to open messge to first person in search list

**Comment by Aluxian** [comment]
I won't add this.
