### ISSUE TITLE
Voice call and Video call crash(Windows version)

### ISSUE THREAD

**Issue by edwardhu** [Aluxian/Facebook-Messenger-Desktop#57]
While I wanna chat with friends with webcam video or voice phone call, the application crash after I clicked the phone call button and video call button.

**Comment by emerts** [comment]
+1

**Comment by v8commodore** [comment]
+1 here too

**Comment by Aluxian** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/24
