### ISSUE TITLE
App crashes after checking for updates

### ISSUE THREAD

**Issue by samuelcouch** [Aluxian/Facebook-Messenger-Desktop#58]
I've been able to reproduce this several times now --
* Launch the app
* `Messenger` menu --> select `Check for updates`
* Dialogue comes back `You're using the latest version: 1.3.0`
* Click `OK`
* _crash_

**Comment by Aluxian** [comment]
I get this too... I think it's a nw.js bug.

**Comment by Aluxian** [comment]
Finally fixed this! https://github.com/Aluxian/Facebook-Messenger-Desktop/commit/cd62db59483c926c3e0a5ec07142978f38fffeb6
