### ISSUE TITLE
won't load

### ISSUE THREAD

**Issue by blyatman66** [Aluxian/Facebook-Messenger-Desktop#584]
* Operating system: linux mint 17.3 mate
* Messenger for Desktop version: unsure, downloaded from website
the app gets to the loading screen and doesn't progress any further meaning i cannot login or even use the app for that matter, it works just fine on my linux mint 18 cinnamon desktop but for some reason won't on my 17.3 mate laptop. i have uninstalled and reinstalled several times and this did not fix the problem.

**Comment by gdgunnars** [comment]
Same problem here, works great on laptop also running 16.04 but not on my desktop

OS: Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.4.0-36-generic

Just stuck on loading screen 
not sure if this helps but paste anyway, screenshot from the console while stuck on the loading screen
[http://imgur.com/a/IylpM](url)

**Comment by Sytten** [comment]
If you guys are not using a beta version then its normal and known issue.
Download the V2 or V1.5.0-beta.1 version and you will be fine.

**Comment by gdgunnars** [comment]
I thought I had the beta on my desktop, but apparently I had it on my laptop.. Sry for troubles
