### ISSUE TITLE
Hide left sidebar doesn't work and themes too (Windows 7 Pro)

### ISSUE THREAD

**Issue by coffeecore** [Aluxian/Facebook-Messenger-Desktop#59]
Hi

I try this app and it's good, but option "Auto-hide sidebar" doesn't work. I enabled and the left sidebar stays.

I also try to select another theme, and it doesn't work. The CSS doesn't change, special thing to do ?

Thanks

**Comment by Aluxian** [comment]
Hey, please try the following steps:

1. [Download the latest version (1.3.1)](https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.3.1)
2. Open the app, right-click and select `Open Dev Tools`
3. Try to change the theme again
4. Paste here what you see in the console

**Comment by coffeecore** [comment]
thanks ! all is good with 1.3.1.

**Comment by Aluxian** [comment]
@coffeecore  Great! :)
