### ISSUE TITLE
Start minimized when windows starts

### ISSUE THREAD

**Issue by osnoser1** [Aluxian/Facebook-Messenger-Desktop#60]
Optional!

**Comment by semack** [comment]
vote +1

**Comment by jkaberg** [comment]
+1 :)

**Comment by tudor07** [comment]
It would be nice +1

**Comment by mcyo** [comment]
+1

**Comment by Markieta** [comment]
+1

Doesn't even work using shortcut property Run: "Minimized" in `shell:startup`.

This might be a deal breaker for me.

**Comment by poisonborz** [comment]
+1

**Comment by fermmm** [comment]
+1 vote

**Comment by mszmatuszewski** [comment]
+1

**Comment by HRoland1** [comment]
+1 :))

**Comment by ekolis** [comment]
Isn't this possible now in 1.x? But the feature is missing from 2.0.0-beta...

**Comment by ekolis** [comment]
Oh wait, it's there, but not from the menu bar, only the taskbar icon menu...
