### ISSUE TITLE
VOICE MESSAGES

### ISSUE THREAD

**Issue by abdelhamidabid** [Aluxian/Facebook-Messenger-Desktop#61]
HOPE THER WILL BE VOICE MESSAGES LIKE THE ORIGINAL MASSENGER AND VIDEO CALLS WITHOUT PROBLEMS AND CRACHES

**Comment by Aluxian** [comment]
I still don't know why it crashes... anyway, this is tracked in another issue.
As for voice messages, this will probably be added on messenger.com.
