### ISSUE TITLE
[Win - v1.3.1] Some issues after update

### ISSUE THREAD

**Issue by minde281** [Aluxian/Facebook-Messenger-Desktop#64]
After I updated to 1.3.1 the program no longer shows at the task bar, and it's also removed from "ALT + TAB"-choices. The only way to open the window now is to click the symbol in the tray: 
![image](https://cloud.githubusercontent.com/assets/5879965/7450746/dbc71e04-f248-11e4-905a-cdb123c0cb3d.png)

**Comment by alopix** [comment]
Same issue here. Would be nice to still have it in the ALT+TAB choices - especially when a window is open!

**Comment by carlosmkb** [comment]
Same here! :(
It would be nice to continue to have the program minimized in the task bar...

**Comment by Aluxian** [comment]
Sorry, this wasn't intended. Fixed in 1.3.2.
