### ISSUE TITLE
Can not start minimized

### ISSUE THREAD

**Issue by psydex** [Aluxian/Facebook-Messenger-Desktop#71]
So I finally ditch Skype and since Messenger for Desktop  now has a little red dot (on it's taskbar icon) I thought it's the perfect replacement. 

I'm having trouble making this to run with Windows - MINIMIZED. I added a shortcut to "Startup" folder but couldn't manage to make it run minimized.

Method #1: http://prntscr.com/71g4x3
Method #2: http://prntscr.com/71g5bf

Both methods failed. How do I make it start with Windows minimized?

**Comment by Aluxian** [comment]
This is something I'm still working on, and it's tracked here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/60. Sorry for the late response.
