### ISSUE TITLE
Reply from notification (Mac)

### ISSUE THREAD

**Issue by iBobik** [Aluxian/Facebook-Messenger-Desktop#73]
Most IM apps on OS X support replying by form in notification. Could you add this feature there?

https://www.dropbox.com/s/kaqu8m7381nj8xr/Skype%20notfications%20reply.mov?dl=0

**Comment by Aluxian** [comment]
I couldn't find any CLI tools for OS X that can create reply-able notifications. NW.js doesn't support this either. It will, however, support rich notifications (#79) which should include the ability to reply to messages.

**Comment by iBobik** [comment]
If somebody will look for OS X replyable notfications, there is http://www.goofyapp.com/ (similar to this app, but build in Cocoa).
