### ISSUE TITLE
Voice messages don't play

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#76]
"Im on Linux (Ubuntu 14.04/elementary OS Freya) and if i get an Voice Messenge, i cant play it. It loads but nothing happens. Ive reinstalled Java but it didnt worked"

**Comment by qstyler** [comment]
I'm on Mac OS X 10.10.4 (14E26a)
Messages aren't playing either.

**Comment by toonamo** [comment]
on windows and voice messages don't play, there isn't a option that i can find to send one either.

**Comment by maciekwyka** [comment]
Any news about this bug? Voice Message does not play :(

**Comment by Sytten** [comment]
Should be resolved with latest beta
https://github.com/Aluxian/Facebook-Messenger-Desktop/releases/tag/v1.5.0-beta.1
