### ISSUE TITLE
Possible "virus" in update 1.3.3

### ISSUE THREAD

**Issue by candestep** [Aluxian/Facebook-Messenger-Desktop#77]
My Avast detect a possible virus infection in the .dmg file of the installer of the new update (1.3.3). I can't keep using the last version if I don't update to the new one and I can't also install the new one because the antivirus deletes some files inside of the installer and corrupts it.
I'm using Snow Leopard, what should I do? Is this new version totally secure?

![virus](https://cloud.githubusercontent.com/assets/11972094/7507694/f84a92b0-f430-11e4-9c11-01aa0b2fbd93.jpg)

**Comment by nicatronTg** [comment]
Well, first of all, the infection variant it lists is for **Win32**, not OS X. Second of all, according to VirusTotal, the [latest revision is clean](https://www.virustotal.com/en/file/e95f5009907134b190403af98e007b74bec65c8b147541b1307e34f669c01237/analysis/1430972359/).
