### ISSUE TITLE
Hard to see the date and Link's mosaic subject and

### ISSUE THREAD

**Issue by kometchtech** [Aluxian/Facebook-Messenger-Desktop#80]
With mosaic theme, date and Link the same theme dark and difficult to see.
These strings could change into something bright?

![snip20150510_1](https://cloud.githubusercontent.com/assets/5137077/7550738/5930eb8c-f6a8-11e4-8290-ccf5b6a1fbd2.png)

**Comment by Aluxian** [comment]
I've just updated some stylesheets and I will release an app update today or tomorrow. After you update, please re-open the issue if the text is still hard to see.

**Comment by kometchtech** [comment]
Determine which is correct.
Thank you for your support!
