### ISSUE TITLE
Wrong behavior when started without network

### ISSUE THREAD

**Issue by iBobik** [Aluxian/Facebook-Messenger-Desktop#81]
When app started on network disconnected it looks like this:
![messagner screenshot](https://cloud.githubusercontent.com/assets/614232/7551326/083edbf8-f685-11e4-9c76-9b8f678f7f46.PNG)
It will be better to show some human readable message.

Then app should listen on system's event about active network and try to reload webapp inside.

**Comment by iBobik** [comment]
In today's version, It shows weired message when reloading:
![snimek obrazovky 2015-05-16 v 17 34 24](https://cloud.githubusercontent.com/assets/614232/7666839/84dd7778-fbf3-11e4-9904-3afc8b172931.PNG)

**Comment by Aluxian** [comment]
Since 1.4.0, the app keeps reloading every 15 seconds until it connects to the internet.
