### ISSUE TITLE
Native notifications in Plasma 5 (KDE)

### ISSUE THREAD

**Issue by fatino** [Aluxian/Facebook-Messenger-Desktop#82]
Hi,
I was kinda misled by native notification claim on main page. There is no notification for Plasma 5 desktop environment. At least it doesn't work in latest 5.3 plasma 5.10 frameworks.
Could we have support for them?

**Comment by ferdau** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/79

I think this will be your best chance of getting notifications...

**Comment by fatino** [comment]
Sorry chrome notifications don't satisfy me. I'd rather keep my desktop consistant.

**Comment by Aluxian** [comment]
Unsupported environments will get chromium notifications (#79) since I can't support every desktop :(

**Comment by Jzarecta** [comment]
Well thats why there is a freedesktop notification agreement on the linux space.
https://wiki.archlinux.org/index.php/Desktop_notifications
