### ISSUE TITLE
Notifications badge feature doesn't seem to work at all..

### ISSUE THREAD

**Issue by bwat47** [Aluxian/Facebook-Messenger-Desktop#83]
I've tried this app on several pc's running windows 8.1. The home page says it has a feature for notification badges on windows and osx:

"Notifications badge in the dock/taskbar for OS X and Windows"

This doesn't seem to work at all as far as I can tell, when I have the app minimized or unfocused and get a message nothing happens to the taskbar icon, no badge for unread notifications. I do get the windows 8 toast notifications on the top right but that's it.

I'm running the latest 1.3.3 version

**Comment by alopix** [comment]
Works on Windows 8.1 and latest 1.3.3 for me.
Notification shows up in upper right corner just like any other Windows 8 notification.
In addition there's a red dot in the systembar.

Either closed or open.

**Comment by bwat47** [comment]
well I had left my computer on last night with messenger open and when I used it this morning I had a red notification badge on the taskbar, so it looks like it started working. Not sure what changed, yesterday I had gotten several messages when the application was minimized and it wasn't giving me any badge, but it looks like its working now so I guess I will close this
