### ISSUE TITLE
App crashes when trying to call/video call

### ISSUE THREAD

**Issue by tsuby** [Aluxian/Facebook-Messenger-Desktop#84]
On Windows 8.1. 
Great app, btw! Congrats!
Tine sus munca buna.

**Comment by mrbumpy409** [comment]
This happens for me as well on Kubuntu 14.04 64-bit. Running Messenger for Desktop from the command line provides no useful output from the crash.

**Comment by tnga** [comment]
Event on my UMI (Ubuntu 14.04 32-bit).

**Comment by Aluxian** [comment]
Duplicate of #24
