### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by harchus** [Aluxian/Facebook-Messenger-Desktop#86]
It woould be awesome to have the drag and drop option for pictures/videos.

**Comment by Aluxian** [comment]
It will be supported when messenger.com adds this. Since facebook.com has it, there's no doubt they will it to messenger.com too.

**Comment by sernick** [comment]
Actually, you can send images via drag&drop, but it only works when you drop file on the textbox. Chrome44/Ubuntu14.10

**Comment by Aluxian** [comment]
If it only works in Chrome 44 then we'll have to wait for nwjs to integrate it.
I still think we just need to wait for Facebook to implement a solution that
works for everyone. I have Chrome 43 on OS X 10.10 and it doesn't work, not even
on the text box.


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Sun, May 31, 2015 at 3:49 pm, Matt < notifications@github.com [notifications@github.com] > wrote:
Actually, you can send images via drag&drop, but it only works when you drop
file on the textbox. Chrome44/Ubuntu14.10

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/86#issuecomment-107173266] .[https://github.com/notifications/beacon/ABWmdnw4SOnE5P2SpunfZcxqdAOTj9inks5oOvrEgaJpZM4EZTBT.gif]
