### ISSUE TITLE
Notifications in elementaryOS

### ISSUE THREAD

**Issue by thedead4fun** [Aluxian/Facebook-Messenger-Desktop#87]
It doesn't work :/

**Comment by sernick** [comment]
i bet NW.js doesn't support pantheon-notifications, you need to use notify-osd as notification provider

**Comment by ferdau** [comment]
https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/79

Will probably help this.

**Comment by lucasnota** [comment]
it was working for me

**Comment by bil-elmoussaoui** [comment]
I can confirm it's not working :s

**Comment by Aluxian** [comment]
Unsupported environments will get chromium notifications (#79) since I can't support every desktop :(
