### ISSUE TITLE
Still running after closing

### ISSUE THREAD

**Issue by FGuyet** [Aluxian/Facebook-Messenger-Desktop#88]
Hi, 

The program is still running after I close the window (by clicking the red button). I see it in my Task Manager (I'm on Windows 8). I still hear the notifications and I can't launch another window of Messenger.
![capture](https://cloud.githubusercontent.com/assets/9808627/7642033/16291708-fa8e-11e4-8e1f-4cb9c78f7dd9.PNG)

**Comment by HRoland1** [comment]
Cause it just minimizes to the system tray. You have to right click and Quit Messenger on the tray icon :)
![screenshot_000033-2015-05-14 23_09_51](https://cloud.githubusercontent.com/assets/12371411/7642075/5dc8a0ec-fa8e-11e4-8188-eb6f56ef77f6.png)

**Comment by FGuyet** [comment]
Oh ok ! That's weird but fine :) Thanks for your answer !

2015-05-14 23:10 GMT+02:00 HRoland1 <notifications@github.com>:

> Cause it just minimizes to the system tray. You have to right click and
> Quit Messenger on the tray icon :)
> [image: screenshot_000033-2015-05-14 23_09_51]
> <https://cloud.githubusercontent.com/assets/12371411/7642075/5dc8a0ec-fa8e-11e4-8188-eb6f56ef77f6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/88#issuecomment-102170371>
> .
>



-- 
Florian GUYET
Étudiant ingénieur en GI02
Université de Technologie de Compiègne
Tel: (+33)7 50 33 72 49
