### ISSUE TITLE
Integration with Ubuntu Unity

### ISSUE THREAD

**Issue by alexander-i-k** [Aluxian/Facebook-Messenger-Desktop#91]
Hi, are you planning to better integrate with ubuntu unity? as for me, it would be cool

**Comment by jordanjay29** [comment]
At the very least, a separate notification icon for the Unity bar would be a plus.

**Comment by Aluxian** [comment]
Duplicate of https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/41
