### ISSUE TITLE
Is typing? **feature request**

### ISSUE THREAD

**Issue by nicomalig** [Aluxian/Facebook-Messenger-Desktop#94]
It'd be amazing if this has the little ellipses when the other person is typing. It'd be carbon-copy Facebook Messenger/iMessage!

**Comment by faizaanceg** [comment]
I think that can be resolved only by Facebook not by this app. Plus, AFAIK the app does have this feature

**Comment by Aluxian** [comment]
Yes, it does have this feature. If you don't see it then most probably it's the other person's fault. I, for example, can block a certain URL/API endpoint so the app can't request it, thus can't report my status. See if it works with different people.
