### ISSUE TITLE
Improved Notification Behavior in Windows

### ISSUE THREAD

**Issue by livinlarge** [Aluxian/Facebook-Messenger-Desktop#95]
Hello,

the messenger's notification behavior could be improved:

when someone is writing me and the app is running in background, i see a (seemingly randomly) blinking "1" badge in the menu bar (windows 7). the blinking is irritating and is not very good from a UX point of view. i catch myself checking the app itself as i can not keep track of incoming messages in a reliable way.

in skype e.g. this is solved better: the app-tile in the menu bar is colored in golden(?) and you get a "1" which stays and does not blink. 

have not tested the mac desktop app but i think the notification behavior can be improved. this is just a UX design perspective. i have no idea about coding.

thank you. i love the software. just installed it today and despite the notifications it is very convenient.

best
arno

edit: also a little "1" badge next to the icon in the tray area would maybe be better than a text notification?!

**Comment by Aluxian** [comment]
Tha badge isn't supposed to blink, the bug is tracked here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/123
