### ISSUE TITLE
Pressing X could minimize to taskbar by default?

### ISSUE THREAD

**Issue by livinlarge** [Aluxian/Facebook-Messenger-Desktop#96]
Pressing the close button on the app window could minimize to taskbar by default? This seems a preferrable solution to me compared to X minimizes to tray because i have just randomly blinking badges next to the tray icon which tell me if there are new messages. this is not very reliable

**Comment by Aluxian** [comment]
This is the default behaviour as of `1.3.2`. Please try the latest release and re-open the issue if it's not fixed.

**Comment by Aluxian** [comment]
I've just rechecked this and indeed, pressing the close button closes the window and only the tray icon is visible. In my opinion, this is the right behaviour because that's what the close button is supposed to do. If you want to minimise it to the taskbar, then use the "minimise" button.

**Comment by cassiodoroVicinetti** [comment]
@Aluxian The behaviour you are describing (i.e. "pressing the close button closes the window and only the tray icon is visible") is in Windows, but in Linux (at least on Debian KDE x64) is different: pressing the close button quits altogether the application (of course the tray icon is no more visible). (I'm using release 1.4.2)

**Comment by Aluxian** [comment]
@cassiodoroVicinetti The close button exits the app on Linux because the tray icon doesn't work for every distro.
